### ISSUE TITLE
[IOS] When setting minimumDate to new Date() the picker doesn't show correct initial value and set always  new Date()

### ISSUE THREAD

**Issue by atlkuk** [react-native-datetimepicker/datetimepicker#139]
# Bug

## Environment info

`react-native info` output:

```bash
"react-native": "0.61.5"
"@react-native-community/datetimepicker": "^2.2.3",
```

Describe what you expected to happen:

1. I expect to init the picker with ```this.state.date```
2. Instead it initialize with ```new Date()```

## Reproducible sample code

```
<DateTimePicker
       style={{width:'100%', backgroundColor: 'white', position: 'absolute', bottom: 0, zIndex: 10}}
       value={this.state.date}
       mode={this.state.mode}
       is24Hour={true}
       onChange={this.onChangePicker}
       minimumDate={new Date()}
/>
```

**Comment by shinigami3000** [comment]
+1
i had initialised my datePicker with new Date() but provided the maximum date of 14 years back. the picker shows the correct date but  when i select the date it returns new Date(). i guess onChange is not getting called with the maximum date

**Comment by vonovak** [comment]
hello @atlkuk, it's not clear what `this.state.date` is in your example. Please provide full snippet that is runnable, otherwise this is not actionable, thanks.

**Comment by bigescalade** [comment]
Having the same issue:

`maxDate = 2020-01-31T00:00:00
minDate = 2020-01-01T00:00:00`

`    <DateTimePickerModal
      isVisible={visible}
      maximumDate={maxDate}
      minimumDate={minDate}
      mode={dateOnly ? 'date' : 'datetime'}
      onCancel={() => setVisible(false)}
      onConfirm={(date) => {
        setVisible(false)
        onChange(name, date.toISOString())
      }}
    />`

In this case, the date picker opens up to 31 Jan 2020, pressing the confirm button sets the date to todays date rather than 31 Jan 2020. Works fine on Android

**Comment by Vasault** [comment]
unfortunately i'm having the same issue, at least on ios

**Comment by dakkafex** [comment]
ditto, using `miniumDate` will always cause the picker to reset to that date

**Comment by LucBarbier-tech** [comment]
Got the same issue recently with maximumDate, i fixed it by setting the time manually if i receive a new Date()
```
  const onChange = (selectedDate: Date) => {
    if (selectedDate.setHours(0, 0, 0, 0) === new Date().setHours(0, 0, 0, 0)) {
      selectedDate = new Date(new Date().setFullYear(new Date().getFullYear() - 18));
    }
  }
```
