### ISSUE TITLE
Android display Spinner DateFormat Reorder 

### ISSUE THREAD

**Issue by pranatha** [react-native-datetimepicker/datetimepicker#140]
# Question

Current default date picker with spinner mode is showing
**'MM/DD/YYYY'** format

How can i reorder it to **'DD/MM/YYYY'** when the spinner dialog show?
Is there any props i should pass,
i'm not able to find the documentation for this
Thank you.

**Comment by chitrasreenivas** [comment]
Hi did you find the solutions?

**Comment by Shashank-Yara** [comment]
Any solutions?

**Comment by vonovak** [comment]
hello 🙂 ,
this is now documented here https://github.com/react-native-datetimepicker/datetimepicker#localization-note

basically, the spinner will behave according to the app locale:

czech:

![o_portrait](https://user-images.githubusercontent.com/1566403/158025208-c28d5682-a8d8-4caa-b4da-1040c32ac1ff.png)

english:
![o_cz](https://user-images.githubusercontent.com/1566403/158025205-d7e1ab7d-d1d9-42b2-a842-f3e7b4a8e635.png)
