### ISSUE TITLE
iOS linker warning about duplicate method implementations

### ISSUE THREAD

**Issue by TomSwift** [react-native-datetimepicker/datetimepicker#184]
I'm seeing this warning from the native linker:

`ld: warning: meta method 'UIDatePickerMode:' in category from /Users/nicholashodapp/Library/Developer/Xcode/DerivedData/Remitly-aouvfdqqojlkkyatnrqzidccuurd/Build/Products/Debug-iphonesimulator/RNDateTimePicker/libRNDateTimePicker.a(RNDateTimePickerManager.o) conflicts with same method from another category
`

I believe [this](https://github.com/react-native-community/datetimepicker/blob/b91df07581d2c576feaae23e9a314897a07cd8c6/ios/RNDateTimePickerManager.m#L17) code in react-native-community/datetimepicker is conflicting with [this](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) code in react-native.   

It's not clear to me how I can omit including the React Native "Core" DatePicker; if that's possible then this likely isn't a real issue.

**Comment by vonovak** [comment]
hi! Thanks for reporting!

> It's not clear to me how I can omit including the React Native "Core" DatePicker; if that's possible then this likely isn't a real issue.

Personally, I don't think it's possible to do this nicely even though I'm sure it'd be possible to eg. patch RN core and get rid of this.

We should probably rename this because the datepicker will stay in the core for another stable release or two I guess

**Comment by bakhadev** [comment]
Same error
ld: warning: meta method 'UIDatePickerMode:' in category from /Users/admin/Library/Developer/Xcode/DerivedData/FarmoishCourierN-dazbhadjvjgpppbrkjzsrawgavcm/Build/Intermediates.noindex/ArchiveIntermediates/FarmoishCourierN/BuildProductsPath/Release-iphoneos/RNDateTimePicker/libRNDateTimePicker.a(RNDateTimePickerManager.o) conflicts with same method from another category

**Comment by JeremiahUL** [comment]
@vonovak Please was anything done to resolve this

**Comment by abelara** [comment]
I'm also getting the same warning.

Meta method 'UIDatePickerMode:' in category from /Users/edyloubaselonia/Library/Developer/Xcode/DerivedData/BlevinsincApp-fvfyqgaltdwyqdaolswvcvzpkyan/Build/Products/Debug-iphoneos/RNDateTimePicker/libRNDateTimePicker.a(RNDateTimePickerManager.o) conflicts with same method from another category

**Comment by Guuz** [comment]
Is it safe to ignore this warning? (i get it too)

**Comment by danilobuerger** [comment]
@Guuz it depends. If the method added via the categories is identical, then yes.

**Comment by 99uno** [comment]
Same here!

**Comment by PraveenTiruveedula** [comment]
Same here 
ld: warning: method '+UIDatePickerMode:' in category from /Users/username/Library/Developer/Xcode/DerivedData/Project-hfgjuzvwxkrpkiavrpljpyvqcimh/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTDatePickerManager.o) conflicts with same method from another category

**Comment by billnbell** [comment]
let's rename this to avoid the conflict.

**Comment by nomi9995** [comment]
update xcode to 12.5 will resolve problem or you can rename `UIDatePickerMode` to any other name in[RCTDatePickerManager.m](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and use  [cocoapods-patch](https://github.com/DoubleSymmetry/cocoapods-patch) on react-native

**Comment by TomSwift** [comment]
> update xcode to 12.5 will resolve problem or you can rename `UIDatePickerMode` to any other name in [RCTDatePickerManager.m](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and use [cocoapods-patch](https://github.com/DoubleSymmetry/cocoapods-patch) on react-native

How does upgrading to XCode 12.5 resolve this?  I'm on XCode 12.5 and still have this issue.

**Comment by binitgurzu** [comment]
+1

**Comment by binitgurzu** [comment]
still looking for solutions

**Comment by jimmihagenTrifcta** [comment]
this stops Expo EAS builds from working

**Comment by jkoutavas** [comment]
Seeing this warning with Xcode 12.5.1. It doesn't seem to be a problem for our app, but it is something we'd like to see addressed.

**Comment by rdjpalmer** [comment]
Does anyone have this working with EAS builds? I'm trying to migrate over at the moment.

> let's rename this to avoid the conflict.

Is it as simple as this? I'm happy to give this a crack if someone can point me in the right direction (instances to rename) and how to get the project running for development. I tried but failed to get the tests to pass with zero code changes.

**Comment by Maker-Mark** [comment]
@jimmihagenTrifecta Any ideas on how to fix this in EAS? I'm seeing this for EXPO's modules ie 
› Linking   MyApp » MyApp
⚠️  ld: method '-hasEnqueuedUICommands' in category from /Users/expo/Library/Developer/Xcode/DerivedData/MyApp-dtwttoustbxxbybkskymiaziukhb/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Debug-iphoneos/expo-dev-menu/libexpo-dev-menu.a(DevMenuREANodesManager.o) conflicts with same method from another category
⚠️  ld: method '-runSyncUIUpdatesWithObserver:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/MyApp-dtwttoustbxxbybkskymiaziukhb/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Debug-iphoneos/expo-dev-menu/libexpo-dev-menu.a(DevMenuREANodesManager.o) conflicts with same method from another category

**Comment by NxsHbb** [comment]
Getting same warning

**Comment by 610consulting** [comment]
I got that error too, any solution yet?

**Comment by TomSwift** [comment]
I suspect the reason this hasn't been fixed is because of how the ObjC macro `RCT_ENUM_CONVERTER` works.  Changing the conflicting method name isn't straightforward because it must mirror the type name (i.e. 'UIDatePickerMode`).

I've silenced the warning in my application by patching React Native to remove (by commenting out) the `RCTConvert (UIDatePicker` category.   The ideal fix would be for React Native to remove this deprecated component altogether.

**Comment by shupac** [comment]
+1

**Comment by btroia** [comment]
> I've silenced the warning in my application by patching React Native to remove (by commenting out) the `RCTConvert (UIDatePicker` category. The ideal fix would be for React Native to remove this deprecated component altogether.

Hi, any chance you could share your patch? I'm having the same issue and tried patching the file via `patch-package` but no luck. Thanks in advance 💪

**Comment by 000xuandu** [comment]
`
ld: method '+UIDatePickerMode:' in category from /Users/mac/Library/Developer/Xcode/DerivedData/CVSimply-fvfmdfibgexpzoftpwvfgxndmwlj/Build/Products/Debug-iphonesimulator/react-native-date-picker/libreact-native-date-picker.a(RNDatePickerManager.o) conflicts with same method from another category
`

` "react-native-date-picker": "^3.4.3",`

**Comment by joaquinbian** [comment]
i have this issue as well... any update?

**Comment by ShepSims** [comment]
We're getting this as well, still no valid fixes from anyone?

**Comment by billnbell** [comment]
try a rm-rf node_modules && yarn install

**Comment by ShepSims** [comment]
> 

Didnt change anything

**Comment by ShepSims** [comment]
> try a rm-rf node_modules && yarn install

Didnt do anything

**Comment by rohitverma-dev29** [comment]
Having same issue

**Comment by NxsHbb** [comment]
It's been two years and the issue is still there....

**Comment by rohitverma-dev29** [comment]
Will this ever be fixed? I cannot push any updates through EAS

**Comment by joaquinbian** [comment]
Honestly I don't know if it is ok, but I renamed `UIDatePickerMode` in [RCTDatePickerManager.h](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.h) and I did the same in [RCTDatePickerManager](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and the build didn't  stop any more... I hope this works, but please let me know if it no the best solution :pray:

**Comment by rohitverma-dev29** [comment]
> Honestly I don't know if it is ok, but I renamed `UIDatePickerMode` in [RCTDatePickerManager.h](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.h) and I did the same in [RCTDatePickerManager](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and the build didn't stop any more... I hope this works, but please let me know if it is not the best solution 🙏

Thanks, Joaquin! Sorry I am a bit of a noob when it comes to editing node modules. For the .m file did you only rename the instance of UIDatePickerMode in line 19? And for the .h file did you replace both instances on line 13, only the one in the parenthesis, or the one outside? Thank you!!!

**Comment by joaquinbian** [comment]
> 

Hello! Yes, that's what I did, I also commented `@interface RCTConvert (UIDatePicker)` in RCTDatePickerManager.h. And keep in mind that in RCTDatePickerManager.m  `UIDatePickerMode`  appears more than one time (I think 2 times), you would have to replace them all!

**Comment by joaquinbian** [comment]
> > Honestly I don't know if it is ok, but I renamed `UIDatePickerMode` in [RCTDatePickerManager.h](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.h) and I did the same in [RCTDatePickerManager](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and the build didn't stop any more... I hope this works, but please let me know if it is not the best solution pray
> 
> Thanks, Joaquin! Sorry I am a bit of a noob when it comes to editing node modules. For the .m file did you only rename the instance of UIDatePickerMode in line 19? And for the .h file did you replace both instances on line 13, only the one in the parenthesis, or the one outside? Thank you!!!


Hello! Yes, that's what I did, I also commented @interface RCTConvert (UIDatePicker) in RCTDatePickerManager.h. And keep in mind that in RCTDatePickerManager.m UIDatePickerMode appears more than one time (I think 2 times), you would have to replace them all!

**Comment by rohitverma-dev29** [comment]
> > > Honestly I don't know if it is ok, but I renamed `UIDatePickerMode` in [RCTDatePickerManager.h](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.h) and I did the same in [RCTDatePickerManager](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and the build didn't stop any more... I hope this works, but please let me know if it is not the best solution pray
> > 
> > 
> > Thanks, Joaquin! Sorry I am a bit of a noob when it comes to editing node modules. For the .m file did you only rename the instance of UIDatePickerMode in line 19? And for the .h file did you replace both instances on line 13, only the one in the parenthesis, or the one outside? Thank you!!!
> 
> Hello! Yes, that's what I did, I also commented `@interface RCTConvert (UIDatePicker)` in RCTDatePickerManager.h. And keep in mind that in RCTDatePickerManager.m `UIDatePickerMode` appears more than one time (I think 2 times), you would have to replace them all!

Thanks for all your help! My EAS builds are working now! Hopefully this issue doesn't rear its ugly head at another inconvenient time

**Comment by LudoLamerre** [comment]
> Honestly I don't know if it is ok, but I renamed `UIDatePickerMode` in [RCTDatePickerManager.h](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.h) and I did the same in [RCTDatePickerManager](https://github.com/facebook/react-native/blob/9bb7e067471571cb1b85e145d56e573688918f46/React/Views/RCTDatePickerManager.m#L19) and the build didn't stop any more... I hope this works, but please let me know if it is not the best solution 🙏

Thanks for your solution. It's possible to have your diff file or simply your `RCTDatePickerManager.m and `RCTDatePickerManager.h` files because the modifications not work for me.
Thank you very much !!!

**Comment by joaquinbian** [comment]
Sure @LudoLamerre :smile: 
![Screenshot from 2022-06-16 10-11-02](https://user-images.githubusercontent.com/69210391/174078542-b233c74e-f74d-4fe3-99fc-e71af310d32b.png)
![Screenshot from 2022-06-16 10-11-02](https://user-images.githubusercontent.com/69210391/174078562-7ebbe6ef-c837-4b19-90f3-0e6ff59f9ef1.png)

**Comment by joaquinbian** [comment]
@LudoLamerre Hello! In RCTDatePickerManager.m it appears more than one time, did you replace all of them?

**Comment by LudoLamerre** [comment]
@joaquinbian Hi, Thank you for your answer. Yes I did but I think that the react-native RCTDatePickerManager is used by WebView package so I can't fixe this issue like that 😓.

**Comment by rdjpalmer** [comment]
@joaquinbian Could you share your patch via [patch-package](https://github.com/ds300/patch-package)?

**Comment by rohitverma-dev29** [comment]
Editing the RCTDatePickerManager.m and RCTDatePickerManager.h files is no longer working for me. Could we please receive some guidance on the proper way to handle this so EAS builds will work?

**Comment by bjm88** [comment]
Still an issue for me, removing node_modules didn't help, on xcode 13.2.....

**Comment by moygoca1** [comment]
Im having same issue this is causing Expo eas build to fail

**Comment by moygoca1** [comment]
After taking a closer look this realized that those are just warnings that are not the ones failing the build, for those having issues with eas build in expo the actual error was this https://github.com/expo/expo/issues/20350 at least in my case.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Date picker was remove from the core, hence this issue should no longer be present: https://reactnative.dev/docs/datepickerios

Thank you 🙂
