### ISSUE TITLE
Change the default first day of the week on Android platform.

### ISSUE THREAD

**Issue by dev-pacific22** [react-native-datetimepicker/datetimepicker#196]
I want to change the first day of the week, currently, by default, Monday is  Is it possible to change the first day of the week on DatePicker in Android, (I can see that there is property firstDayOfWeek is available for Windows platform only.)

**Comment by vonovak** [comment]
this should be possible with https://developer.android.com/reference/android/widget/DatePicker#setFirstDayOfWeek(int)

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 8.1.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
