### ISSUE TITLE
Ability to hide day from date picker

### ISSUE THREAD

**Issue by sarahshuffle** [react-native-datetimepicker/datetimepicker#200]
Would it be possible to configure the date picker to only show the month & year, without the day picker?

**Comment by luancurti** [comment]
I search about this option and I found this implementation for Android: https://stackoverflow.com/questions/10673842/android-hide-date-field-in-datepickerdialog/26720826

and this for iOS:
https://stackoverflow.com/questions/44559014/how-to-hide-days-in-uidatepicker

but the current version of this component doesn't have this option. Feel free to contribute

**Comment by vonovak** [comment]
looking at [this answer](https://stackoverflow.com/a/26720826/2070942) for android, that looks fine but I'm not so sure about the accepted ios implementation; I'm not liking it much - if someone plans to implement this, please consult us beforehand. Thanks!

**Comment by vonovak** [comment]
this is not possible with the native ios picker and so it cannot be done. With this, I'm closing the issue. Thank you
