### ISSUE TITLE
[Android a11y] - Screen reader keeps reading through disabled dates

### ISSUE THREAD

**Issue by kevinrodriguez-io** [react-native-datetimepicker/datetimepicker#223]
# Bug report

## Summary
There's a weird specific bug on screen-readers for android where disabled dates are being read, I'm creating the issue to seek for help, because this can even be a bug on the Android native SDK. The issue happens when you're using a screen reader, it keeps reading the dates even if they're not tappable on Android.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/Projects/@boltsource/react-native/node_modules/.bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 2.4.2

## Steps to reproduce

- Use/install the example app on android
- On an android device/emulator install/enable TalkBack
- Tweak the app a little bit to show disabled dates from now on, for example, `maxDate={new Date(2020, 07, 16)}`
- The auto-reader will read the days starting from today to the end of the month, even if the dates are disabled
    - Note this can't be reproduced by tapping directly on the buttons, since they're disabled.

Describe what you expected to happen:

1. The screen reader only reads elements that are tappable

## Reproducible sample code
- You can use the example on this repo, just add `maxDate={new Date()}`

**Comment by luancurti** [comment]
@kevinrodriguez-io  We don't have plans to implement this feel free to contribute

**Comment by vonovak** [comment]
hello and thanks for reporting

> this can even be a bug on the Android native SDK

I'm afraid that is the case and we cannot do anything about it but feel free to open another issue if you believe the library can do better here.

thank you
