### ISSUE TITLE
Add ability to close picker on componentWillUnmount

### ISSUE THREAD

**Issue by AlexeyNovikov** [react-native-datetimepicker/datetimepicker#236]
# Feature request
Is this possible to add an imperative way to close picker?

## Why it is needed
We cannot call setState on `componentWillUnmount` now, so it would be helpful to close picker by calling a function.

**Comment by mvanroon** [comment]
can't you call setState in the code that causes the view te be unmounted?

**Comment by timetarget** [comment]
> can't you call setState in the code that causes the view te be unmounted?

One major case I have is to hide Picker if there was a navigation transition. I suppose it will be inconvenient to implement such logic on the router side.

**Comment by mvanroon** [comment]
what causes the navigation transition? is it's something inside your screen, you can call setState there before navigating

**Comment by timetarget** [comment]
@mvanroon it is a push notification. when a user taps on it he should be redirected somewhere.

**Comment by AlexeyNovikov** [comment]
@mvanroon it is a push notification. when a user taps on it he should be redirected somewhere.

**Comment by walterdl** [comment]
Same problem over here.

**Comment by walterdl** [comment]
@AlexeyNovikov did you solved it?

**Comment by timetarget** [comment]
> @AlexeyNovikov did you solved it?

no

**Comment by vonovak** [comment]
closed via https://github.com/react-native-datetimepicker/datetimepicker/pull/337
