### ISSUE TITLE
RNDateTimePicker fails compiling with TypeScript when adding the "display" option

### ISSUE THREAD

**Issue by Fulguritude** [react-native-datetimepicker/datetimepicker#237]
The following code

```
 {show && (
                <RNDateTimePicker
                    testID="dateTimePicker"
                    value={date}
                    mode={mode}
                    onChange={onChange}
                    display="spinner"
                />
)}
```

does not compile with TypeScript, with the following error:

```
Type '{ testID: string; value: Date; mode: TimeModeString; display: "spinner"; onChange: (event: Event, selectedDate: Date | undefined) => void; }' is not assignable to type '(IntrinsicAttributes & Readonly<Readonly<ViewProps & BaseOptions & { maximumDate?: Date | undefined; minimumDate?: Date | undefined; }> & { ...; }> & { ...; }) | (IntrinsicAttributes & ... 1 more ... & { ...; })'.Property 'display' does not exist on type 'IntrinsicAttributes & Readonly<Readonly<ViewProps & BaseOptions & { maximumDate?: Date | undefined; minimumDate?: Date | undefined; }> & { ...; }> & { ...; }'
```

This is because of the "display" field. Why ?

The type RNDateTimePicker is defined `declare const RNDateTimePicker: FC<IOSNativeProps | AndroidNativeProps>;`, and the "display" field does not exist in `IOSNativeProps`, so providing it for a cross-platform app breaks this, because it only applies to one half of the dependent type union.

My fix was to add `display?: Display;` to line 96 of `@react-native-community/datetimepicker/index.d.ts`, in the type declaration of IOSNativeProps. This allows compilation, and shouldn't cause any issues in iOS because the "display" field does not exist for it, and thus should not cause incoherent behavior.

However, adding this to the codebase would suggest that this field DOES exist on iOS when it actually doesn't, which is not ideal, so I suppose you could find a better fix.

Thanks.

**Comment by sjchmiela** [comment]
I bumped into this issue too and what I did was something along the lines of:
```tsx
<DateTimePicker
  // ...
  {...(Platform.OS === "android" ? { display: "spinner" } : {})}
/>
```
(I'm not objecting to what you say in your post, in fact I kind of agree, just putting my two cents out there!) Hope you find it useful!

**Comment by Saeid-Barzegar** [comment]
Have the same issue.
it says "Type '**string**' is not assignable to type '**never**'."

**Comment by Saeid-Barzegar** [comment]
@vonovak , it's happening cause of a props conflict. 
fixed with change the prop's name to "**displayPicker**"
![image](https://user-images.githubusercontent.com/10572916/102317141-037a3000-3fb2-11eb-895d-53480fb85a1c.png)

**Comment by vonovak** [comment]
Hello 👋 ,
I tried to reproduce this issue and was not able to do it. I believe it should be resolved.

With that, I'm closing the issue,
Thank you! 🙂
