### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by corradio** [react-native-datetimepicker/datetimepicker#24]
Is it possible to pass a style `fontSize` and `fontFamily`? It currently doesn't work.

**Comment by BenjErgizerBunny** [comment]
@corradio  did you ever find a solution to this?  I'm also having this problem and even more importantly, I need to be able to change the text color since I have a dark background

**Comment by corradio** [comment]
Unfortunately I did not find a solution for this :/

**Comment by bsbechtel** [comment]
Any comment from the maintainers on this? I'd really like this feature as well.

**Comment by vonovak** [comment]
for changing font color, that seems kinda possible, see [SO](https://stackoverflow.com/questions/20875054/change-uidatepicker-font-color)

as for Android, some customization can probably be done by editing some theme-related xml files. I do not have plan to add this, feel free to contribute. Thank you.

**Comment by elallaouielmehdi** [comment]
Hi, i run into the same error, i did use the customStyle dateText, and it did work fine for me 
customStyles={{

            dateIcon: {
              width:0,
              height:0,
              },
              dateInput:
              {
                borderWidth: 0, 
                position:'absolute',
                left: 0,
                
              },
              dateText:
              {
                fontFamily:'raleway',
                color: Colors.gray_light,
              }
          }}
