### ISSUE TITLE
Can react-native-community/datetimepicker handle 2 date pickers widgets on same page?

### ISSUE THREAD

**Issue by skijooma** [react-native-datetimepicker/datetimepicker#259]
What I want to achieve here is having 2 widgets set different dates. What I am getting is, when I set with either one of them, only one onChange() runs, hence always sets for only one date pickers regardless of calling different onChange methods, and having different states for each one of them. Please help me know if this is possible, and possibly how I can implement it. Thanks.

**Comment by student513** [comment]
I got a same issue. I assigned a onChange function for each DateTimePicker.  But only the first DateTimePicker works well. The change of the rest of the DateTimePicker is reflected in the first DateTimePicker.

**Comment by skijooma** [comment]
Thanks for feedback @student513 
My workaround was, I maintained only one onChange() that sets the state variables of either one of the two corresponding DateTime pickers based on which widget was clicked. For each widget, I also maintain a boolean state variable that is set to true when it's clicked (in its onPress()), then turned off again after retrieving the respective DateTime value.

**Comment by aqeebimtiaz** [comment]
I used multiple `DateTimePicker` for every `TextInput` element and only one `onChange()` function. All I had to do was make sure their visibility stays hidden until the TextInput was clicked.

Thank you so much for all the hints! :)
