### ISSUE TITLE
Custom value/placeholder separate from value property

### ISSUE THREAD

**Issue by actuallymentor** [react-native-datetimepicker/datetimepicker#271]
# Feature request

Instead of the default `Mon Jan 01 2020` representation of `value=` add a property `label=` that does not touch the internal date/time but allows for arbitrary inputs like `monday` or `tomorrow`.

## Why it is needed

Locale support is very limited for many use cases.

## Possible implementation

Add new property and replace the visual output with it.

### Code sample

```js
<DateTimePicker
	mode='date'
	label='today'
	display='spinner'
	value={ new Date() }
	onChange={ this.pickDate }
 />
```

**Comment by vonovak** [comment]
hello, thanks for the suggestion. I'm closing it because it does not follow https://github.com/react-native-datetimepicker/datetimepicker#props

Please open a new feature request that explains how this can be done, thank you!
