### ISSUE TITLE
locale are not supported on android

### ISSUE THREAD

**Issue by tomilton** [react-native-datetimepicker/datetimepicker#272]
![Locale](https://user-images.githubusercontent.com/5742462/92648331-e2b58680-f2ae-11ea-9cf2-f2134bb06928.PNG)
![LocaleImpl](https://user-images.githubusercontent.com/5742462/92648342-e77a3a80-f2ae-11ea-9ee4-3ba9f49071cc.PNG)

It is necessary to show in Spanish, for Latin American countries.

**Comment by PrimulaX** [comment]
As @vonovak said there is currently no plan to implement this by the maintainers.

**Comment by dcx86** [comment]
Same problem here!
@vonovak how is that they decided to implement for ios but not for android? the feature is  like half done.

**Comment by PrimulaX** [comment]
@dcx86 Seems there is no way to override system default locale on Android as its possible on iOS.

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
