### ISSUE TITLE
Accessibility: Setting locale does not change the read up value by Voiceover on time or minute wheels

### ISSUE THREAD

**Issue by lissau** [react-native-datetimepicker/datetimepicker#274]
## Summary

IOS: Setting the `locale` property only changes the read up value by voiceover on the date wheel and not on the time or minute wheels. 

## Environment info

`react-native info` output:

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 54.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.1, 27.0.0, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-bridge: 2.0.1
    react-native-create-library: 3.1.2

Library version: 3.0.2

## Steps to reproduce

1. Render a DateTimePicker component anywhere:

`		<DateTimePicker
			style={{ width: "100%" }}
			value={new Date()}
			mode={"datetime"}
		/>`

2. Change your phone setting to english

3. Enable Voiceover on iOS: Settings -> Accessibility -> VoiceOver -> Enable 
Note: Swiping right/left select the next/previous element on the screen. Single click selects and element and double tap activates it element.

4. Double tap home button and swipe left and double click to change back into the app with the DateTimePicker component.

5. Change up and down on the time and minute wheels to hear it reads "xx o'clock" or "xx minutes"

6. Double tap home button again and change back into settings

7. Disable voice over

8. Change your phone setting to anything but english ( for instance Danish )

9. Enable the locale property:
`		<DateTimePicker
			style={{ width: "100%" }}
			value={new Date()}
			mode={"datetime"}
			locale={"da"}
		/>`

10. Enable voiceover 

12. Switch back into the app and see that the date has changed to match the selected locale

12. Change up and down on the time and minute wheels to hear it still reads  "xx o'clock" or "xx minutes", but just in a different language

Describe what you expected to happen:

1. Changing the locale property, would make Voice over read the value of the hour and minute wheels in the selected locale in the same way it does in iOS calendar app

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
