### ISSUE TITLE
Minute interval not working with last expo and last datetimepicker

### ISSUE THREAD

**Issue by Deagle50** [react-native-datetimepicker/datetimepicker#275]
Expo 37.0.12
DateTimePicker: 3.0.2

Hi, I'm trying to use the minute interval feature, but it's not working at all on my Samsung Galaxy Tab A 10.1 2019 (SM-T515) with Android 10 and One UI 2.1, it just selects the exact time, not the nearest interval.

```
<DateTimePicker
     value={this.state.initialDate}//Date with ISO 8601 format
     // The mode of the picker, "date" or "time", taken from props
     mode={this.props.mode}//String with the mode
     // Not working this one
     minuteInterval={5}
     // Maximum selectable date will be today's one
     maximumDate={new Date()}
     // Calls this function to change date
     onChange={this.onChange}/>
```

It's happening the same as #238, but with the latest versions of both Expo and DateTimePicker.

**Comment by vonovak** [comment]
closed via https://github.com/react-native-datetimepicker/datetimepicker/pull/360
