### ISSUE TITLE
DateTime Formatting option

### ISSUE THREAD

**Issue by pritamsoni-hsr** [react-native-datetimepicker/datetimepicker#278]
# Feature request

## Why it is needed
iOS allows us to configure data time formatting, MM-YYYY, or DDD-MM and so on.

## Possible implementation

[react-native-datepicker](https://github.com/xgfe/react-native-datepicker)
![ios](http://xgfe.github.io/react-native-datepicker/img/react-native-datepicker-ios.gif)

**Comment by chobits4** [comment]
you can set `local` and mode for it , such as:
> mode="datetime" and locale="zh_CN"
