### ISSUE TITLE
Hide the picker while the app is running in the background / inactive

### ISSUE THREAD

**Issue by pro-nasa** [react-native-datetimepicker/datetimepicker#279]
```js
const appState = useAppState()
const [show, setShow] = useState(false)

useEffect(() => {
  if (appState.match(/inactive|background/)) {
    setShow(false)
  }
}, [appState])
```

The state changes correctly, but hiding the picker is terminated when the app is going on to the background

**Comment by pro-nasa** [comment]
There is likely a general problem with hiding a picker without clicking on the buttons (Cancel / OK)

**Comment by pavermakov** [comment]
I had a similar issue a while ago. However, I could not find a proper solution. Here is my question on stackoverflow:

https://stackoverflow.com/questions/55604706/how-to-close-android-datepicker-in-react-native

I am thinking about writing a pure js datepicker component.

**Comment by pro-nasa** [comment]
All I had to do was put in the PIN Code view in the native modal, but that was my case

**Comment by pro-nasa** [comment]
@pavermakov Unfortunately in this version value of an instance is `undefined` (by ref)

**Comment by vonovak** [comment]
Hello 👋 ,
this issues should be resolved with the v6 and probably even v5.

With that, I'm closing the issue,
Thank you! 🙂
