### ISSUE TITLE
does it support picker format like 'YYYY-MM-DD HH:mm'

### ISSUE THREAD

**Issue by chj-damon** [react-native-datetimepicker/datetimepicker#282]
# Question
currently, mode='datetime' means it will display `month-day-AM/PM-hour-minute`, how can I make the picker like `year-month-day-hour-minute`

**Comment by chobits4** [comment]
mode="datetime" and locale="zh_CN"

**Comment by chj-damon** [comment]
@chobits4  not the exactly format as I expected.

**Comment by EneRgYCZ** [comment]
In my case I used `.toLocaleDateString()` but you cand use `.toUTSCString()` or `.toISOString()` depending on your use case.

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
