### ISSUE TITLE
Different UI on iOS 14

### ISSUE THREAD

**Issue by pavermakov** [react-native-datetimepicker/datetimepicker#285]
## Summary

I am currently preparing my app for the iOS 14. I have noticed that the date picker is not what it used to be.

Here is what it looks like on iOS 13.7:

<img width="395" alt="Снимок экрана 2020-09-21 в 16 31 16" src="https://user-images.githubusercontent.com/10779996/93776147-f0162d80-fc2b-11ea-990d-295829d7de77.png">

Here is the iOS 14 version:
<img width="383" alt="Снимок экрана 2020-09-21 в 16 22 57" src="https://user-images.githubusercontent.com/10779996/93776428-2d7abb00-fc2c-11ea-8b59-830605576f7b.png">

<img width="383" alt="Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-21 at 16 23 01" src="https://user-images.githubusercontent.com/10779996/93776669-7894ce00-fc2c-11ea-942e-6243a7077d0e.png">

There is now an extra step, instead of spinning the wheel, I need to press it to trigger another calendar popup.

I use `display: "spinner"` prop.

Is there any way I can still use the wheel on iOS 14?

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 391.89 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/pavelermakov/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
```

Library version: 3.0.2

**Comment by jChris85** [comment]
I have the same issue. The user flow is actually correct. That is how the new date picker from iOS 14 works, but the styling is a bit broken / not optimized for the new flow.

**Comment by ajengrf** [comment]
facing the same issue, it makes users have to click two times to choose the date. any help on this?

**Comment by jChris85** [comment]
I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.

```
if (@available(iOS 14, *)) {
  UIDatePicker *picker = [UIDatePicker appearance];
  picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
}
```
After restarting your app the date picker should show the old wheel style.
This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

**Comment by pavermakov** [comment]
@jChris85 That works, thank you!

**Comment by jChris85** [comment]
@pavermakov I'm glad this is working for you. However, we should leave the issue open until this package is updated.

**Comment by jChris85** [comment]
Regarding the documentation setting the prop display to `spinner` worked for me as well without the need of the native "fix".

**Comment by joaom182** [comment]
@jChris85 you're a legend. Thaaanks

**Comment by yt-dev** [comment]
display={Platform.OS === 'ios' ? 'inline' : 'default'}

**Comment by daybreaker** [comment]
Setting display="spinner" still showing new default ios14 UI

I've deleted npm packages, cleared cache, reinstalled, cleared pod cache, and reinstalled pods. Same behavior.

**Comment by vinhnglx** [comment]
@daybreaker 
I have to use the [react-native-date-picker](https://github.com/henninghall/react-native-date-picker) at the moment.

**Comment by rodrigoarantes** [comment]
I noticed that in a brand new project the display options were working correctly, and so I tried deleting all caches with the following commands, and it worked.

```
watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache
```

**Comment by jChris85** [comment]
> Setting display="spinner" still showing new default ios14 UI
> 
> I've deleted npm packages, cleared cache, reinstalled, cleared pod cache, and reinstalled pods. Same behavior.

@daybreaker: Try to delete all available cache files and then restart your app.

Solution provided by @rodrigoarantes

> I noticed that in a brand new project the display options were working correctly, and so I tried deleting all caches with the following commands, and it worked.
> 
> ```
> watchman watch-del-all && 
> rm -rf $TMPDIR/react-native-packager-cache-* &&
> rm -rf $TMPDIR/metro-bundler-cache-* && 
> rm -rf node_modules/ 
> && npm cache clean --force &&
> npm install && 
> npm start -- --reset-cache
> ```

**Comment by daybreaker** [comment]
@jChris85 Thanks a bunch - that seems to have done the trick! I wasnt deleting enough caches! :-P

**Comment by phuocantd** [comment]
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }

Hi @jChris85,
I want to display center
Can you help me pls?

![image](https://user-images.githubusercontent.com/31690470/94409336-39bcc600-01a0-11eb-9908-9cf596703e8b.png)

**Comment by daybreaker** [comment]
@phuocantd this was happening to me too, when trying the AppDelegate.m hack

Try removing that, and doing the cache deletion steps @rodrigoarantes mentioned:

```
watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache
```

Deleting all the caches and restarting brought back the old, centered spinner.

**Comment by m4devgeek** [comment]
> facing the same issue, it makes users have to click two times to choose the date. any help on this?

Facing same

**Comment by phuocantd** [comment]
@daybreaker thanks but what is the TMPDIR???

**Comment by jChris85** [comment]
@m4devgeek Did you tried the solutions provided in this thread?

1. Set the date picker prop display to `spinner`
2. Delete all cache files
```
watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache
```
3. restart your app

**Comment by donaldparker** [comment]
This works locally but when it goes though my build server, bitrise, I get the following error:

```
ios/MY_APP/AppDelegate.m:54:39: use of undeclared identifier 'UIDatePickerStyleWheels'
picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
```


Any ideas?

**Comment by vonovak** [comment]
@donaldparker you need to use xcode 12, that should make the error go away

**Comment by donaldparker** [comment]
Yes that fixed the issue, thank you.

**Comment by anhtuank7c** [comment]
Swift version

```
if #available(iOS 14.0, *) {
    let picker = UIDatePicker()
    picker.preferredDatePickerStyle = .wheels
}
```

**Comment by kendallroth** [comment]
Out of curiosity, is there any way to toggle that datepicker popup directly, without having to go through the wheel or the new iOS 14 date inputs? ie. If I wanted to use a unified display to hold the text value, but `onPress` it would show the Android DatePicker **or** the new iOS picker modal?

**Comment by trackwell-mike** [comment]
@jChris85 Clearing the cache helped us as well on our local machine, but when we try and create a production build using Bitrise, it fails (similar to @donaldparker 's [comment](https://github.com/react-native-datetimepicker/datetimepicker/issues/285#issuecomment-701003150)). I've tried [clearing Bitrise's cache](https://devcenter.bitrise.io/builds/caching/about-caching-index/#downloading-and-deleting-caches), but that didn't solve our problem.

I'm not going to paste in all the errors we got related to this library, but I'll share the beginning portion to see if anyone else has this issue or an idea to solve. 

Thanks!

```
▸ Compiling RNDateTimePickerManager.m

❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:23:20: expected a type

RCT_ENUM_CONVERTER(UIDatePickerStyle, (@{
                                                                     ^



❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:24:19: use of undeclared identifier 'UIDatePickerStyleAutomatic'; did you mean 'UIActionSheetStyleAutomatic'?

    @"default": @(UIDatePickerStyleAutomatic),
                   ^



❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:25:19: use of undeclared identifier 'UIDatePickerStyleCompact'

    @"compact": @(UIDatePickerStyleCompact),
    ^



❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:26:19: use of undeclared identifier 'UIDatePickerStyleWheels'

    @"spinner": @(UIDatePickerStyleWheels),
                  ^



❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:30:5: use of undeclared identifier 'UIDatePickerStyleAutomatic'; did you mean 'UIActionSheetStyleAutomatic'?

}), UIDatePickerStyleAutomatic, integerValue)
                  ^



❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:23:1: implicit conversion of 'NSInteger' (aka 'int') to 'id' is disallowed with ARC

RCT_ENUM_CONVERTER(UIDatePickerStyle, (@{
```

**Comment by Dev4ster** [comment]
> Eu encontrei uma solução rápida para esse problema. Você pode substituir seu prefferedStyle do UIDatePicker em seu espaço de trabalho iOS nativo. Basta adicionar as seguintes linhas de código à função `didFinishLaunchingWithOptions`em seu `ios/APP_NAME/AppDelegate`arquivo.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> Depois de reiniciar seu aplicativo, o seletor de data deve mostrar o estilo de roda antigo.
> Esta correção pode ser removida depois que este pacote for atualizado com o novo fluxo de usuário e estilo para o selecionador de data do iOS 14.

woks to me thxs

**Comment by Dev4ster** [comment]
> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

as soon as I change the date it triggers this error

![image](https://user-images.githubusercontent.com/29731901/95462799-60bc8a00-094e-11eb-959a-9b587a120467.png)

**Comment by lorenzosignoretti** [comment]
> Out of curiosity, is there any way to toggle that datepicker popup directly, without having to go through the wheel or the new iOS 14 date inputs? ie. If I wanted to use a unified display to hold the text value, but `onPress` it would show the Android DatePicker **or** the new iOS picker modal?

Facing the same issue. Anyone found a viable solution? Thanks!

**Comment by Hless** [comment]
> @jChris85 Clearing the cache helped us as well on our local machine, but when we try and create a production build using Bitrise, it fails (similar to @donaldparker's [comment](https://github.com/react-native-datetimepicker/datetimepicker/issues/285#issuecomment-701003150)). I've tried [clearing Bitrise's cache](https://devcenter.bitrise.io/builds/caching/about-caching-index/#downloading-and-deleting-caches), but that didn't solve our problem.

@trackwell-mike You might want to try and switch to XCode 12+, iOS 14 API's will not be available otherwise.

**Comment by rosenexpend** [comment]
> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.



> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

@jChris85 Thank you for this fix. However, when I put your code in the `AppDelegate.m` in the `didFinishLaunchingWithOptions` function but I am getting the following errors on my build:
1) AppDelegate.m:31:12: Property 'preferredDatePickerStyle' not found on object of type 'UIDatePicker *'
2) Use of undeclared identifier 'UIDatePickerStyleWheels'

Do you know what is causing them and how I can proceed to resolve them? Thank you.

**Comment by burivuhster** [comment]
@rosenexpend Most probably it's an outdated Xcode version. You need at least Xcode 11.4 according to apple docs.

**Comment by aquinodaniel1994** [comment]
we gnari porco dio la dark mode!!?!?!?!

**Comment by unicornRainbows** [comment]
I also have the same issue using the latest Xcode. the time spinner is not centered. I have also deleted the cache as recommended.

**Comment by akiladevinda** [comment]
> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

I have tried this but still not getting the spinner like old version

**Comment by jagwingchoy** [comment]
> @m4devgeek This is the new iOS 14 date picker behaviour. However, did you try the solutions provided in this thread?
> 
> To reset the date picker to use the spinner wheel follow these steps:
> 
> 1. Set the date picker prop display to `spinner`
> 2. Delete all cache files
> 
> ```
> watchman watch-del-all && 
> rm -rf $TMPDIR/react-native-packager-cache-* &&
> rm -rf $TMPDIR/metro-bundler-cache-* && 
> rm -rf node_modules/ 
> && npm cache clean --force &&
> npm install && 
> npm start -- --reset-cache
> ```
> 
> 1. restart your app

Trying to remove cache with suggested commands, while running
`rm -rf $TMPDIR/react-native-packager-cache-*` and `rm -rf $TMPDIR/metro-bundler-cache-*`
comes out following errors:

    zsh: no matches found: /var/folders/1y/26nzt9ld4737blg1s89sxyk40000gn/T//metro-bundler-cache-*
    zsh: no matches found: /var/folders/1y/26nzt9ld4737blg1s89sxyk40000gn/T//react-native-packager-cache-*

I am already using Xcode 12, and have erased content in simulator, 
but still having the problem after running those commands. Any alternative ideas on how to solve it? Thanks.

**Comment by jagwingchoy** [comment]
> > @m4devgeek This is the new iOS 14 date picker behaviour. However, did you try the solutions provided in this thread?
> > To reset the date picker to use the spinner wheel follow these steps:
> > 
> > 1. Set the date picker prop display to `spinner`
> > 2. Delete all cache files
> > 
> > ```
> > watchman watch-del-all && 
> > rm -rf $TMPDIR/react-native-packager-cache-* &&
> > rm -rf $TMPDIR/metro-bundler-cache-* && 
> > rm -rf node_modules/ 
> > && npm cache clean --force &&
> > npm install && 
> > npm start -- --reset-cache
> > ```
> > 
> > 
> > 
> > 1. restart your app
> 
> Trying to remove cache with suggested commands, while running
> `rm -rf $TMPDIR/react-native-packager-cache-*` and `rm -rf $TMPDIR/metro-bundler-cache-*`
> comes out following errors:
> 
> ```
> zsh: no matches found: /var/folders/1y/26nzt9ld4737blg1s89sxyk40000gn/T//metro-bundler-cache-*
> zsh: no matches found: /var/folders/1y/26nzt9ld4737blg1s89sxyk40000gn/T//react-native-packager-cache-*
> ```
> 
> I am already using Xcode 12, and have erased content in simulator,
> but still having the problem after running those commands. Any alternative ideas on how to solve it? Thanks.

Sorry my bad, found out that I need to add `display="spinner"` to datepicker.ios.js.

**Comment by kasunascentic** [comment]
> UPDATE: Solved this issue by updating Xcode version in Bitrise. Thanks @Hless, for your [suggestion](https://github.com/react-native-datetimepicker/datetimepicker/issues/285#issuecomment-706090955)
> 
> @jChris85 Clearing the cache helped us as well on our local machine, but when we try and create a production build using Bitrise, it fails (similar to @donaldparker's [comment](https://github.com/react-native-datetimepicker/datetimepicker/issues/285#issuecomment-701003150)). I've tried [clearing Bitrise's cache](https://devcenter.bitrise.io/builds/caching/about-caching-index/#downloading-and-deleting-caches), but that didn't solve our problem.
> 
> I'm not going to paste in all the errors we got related to this library, but I'll share the beginning portion to see if anyone else has this issue or an idea to solve. 
> 
> Thanks!
> 
> ```
> ▸ Compiling RNDateTimePickerManager.m
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:23:20: expected a type
> 
> RCT_ENUM_CONVERTER(UIDatePickerStyle, (@{
>                                                                      ^
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:24:19: use of undeclared identifier 'UIDatePickerStyleAutomatic'; did you mean 'UIActionSheetStyleAutomatic'?
> 
>     @"default": @(UIDatePickerStyleAutomatic),
>                    ^
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:25:19: use of undeclared identifier 'UIDatePickerStyleCompact'
> 
>     @"compact": @(UIDatePickerStyleCompact),
>     ^
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:26:19: use of undeclared identifier 'UIDatePickerStyleWheels'
> 
>     @"spinner": @(UIDatePickerStyleWheels),
>                   ^
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:30:5: use of undeclared identifier 'UIDatePickerStyleAutomatic'; did you mean 'UIActionSheetStyleAutomatic'?
> 
> }), UIDatePickerStyleAutomatic, integerValue)
>                   ^
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:23:1: implicit conversion of 'NSInteger' (aka 'int') to 'id' is disallowed with ARC
> 
> RCT_ENUM_CONVERTER(UIDatePickerStyle, (@{
>                   ^
> 
> 
> ...
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:70:9: unknown type name 'UIDatePickerStyle'; did you mean 'UIDatePickerMode'?
> 
>         UIDatePickerStyle determinedDisplayValue = view.datePickerStyle;
>     ^
> 
> 
> ⚠️  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:73:94: incompatible integer to pointer conversion sending 'UIDatePickerMode' (aka 'enum UIDatePickerMode') to parameter of type 'id' [-Wint-conversion]
> 
>                  @"determinedDisplayValue": [RNDateTimePickerManager datepickerStyleToString:determinedDisplayValue],
>                                                                                              ^~~~~~~~~~~~~~~~~~~~~~
> 
> 
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:89:39: property 'datePickerStyle' not found on object of type 'RNDateTimePicker *'; did you mean 'datePickerMode'?
> 
>   if (@available(iOS 14.0, *) && view.datePickerStyle != UIDatePickerStyleWheels) {
>                                                            ^
> 
> 
> ...
> 
> 
> ▸ Compiling RNDateTimePicker.m
> ▸ Compiling RNDateTimePicker-dummy.m
> ▸ Compiling RNDateTimePickerManager.m
> 
> ❌  /Users/vagrant/git/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerManager.m:23:20: expected a type
> 
> RCT_ENUM_CONVERTER(UIDatePickerStyle, (@{
>     ^
> 
> ...
> ```

Any solution for this issue?

**Comment by pinpointpanda** [comment]
> Out of curiosity, is there any way to toggle that datepicker popup directly, without having to go through the wheel or the new iOS 14 date inputs? ie. If I wanted to use a unified display to hold the text value, but `onPress` it would show the Android DatePicker **or** the new iOS picker modal?

I'm also wondering about this! Will investigate and see if I can figure out a way of popping it directly.

**Comment by karlludwigweise** [comment]
I am using it the default way and it shows just a date and when you tap it the new date picker opens in modal styles.

The only thing I could not solve so far is aligning it to the right (it is `inline-block` style).

**Comment by dmitryshelomanov** [comment]
> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

it works on simulator but does not work on real device
Any ideas ?
On real device calendar dont apear

**Comment by sumitagarwal31** [comment]
@phuocantd did you got the solution of the center alignment of wheels

**Comment by phuocantd** [comment]
> @phuocantd did you got the solution of the center alignment of wheels

yes, i resolved it

**Comment by NozhenkoD** [comment]
What solution for expo "managed workflow"?

**Comment by oporter1** [comment]
> I found a quick fix for this issue. You can override your prefferedStyle of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

Sorry for the newb question but I am running React Native and not ejecting it to an ios file. Where would I create my AppDelegate file in this instance?

**Comment by imshreyansh** [comment]
Any Solution for Expo ?

**Comment by rafmst** [comment]
> Any Solution for Expo ?

The following code worked for me on Expo:

```
display={Platform.OS === 'ios' ? 'inline' : 'default'}
```

Using `"@react-native-community/datetimepicker": "^3.0.6"`

**Comment by jChris85** [comment]
> I found a quick fix for this issue. You can override your preferred Style of the UIDatePicker in your native iOS workspace. Just add the following lines of code in the function `didFinishLaunchingWithOptions` in your `ios/APP_NAME/AppDelegate` file.
> 
> ```
> if (@available(iOS 14, *)) {
>   UIDatePicker *picker = [UIDatePicker appearance];
>   picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> ```
> 
> After restarting your app the date picker should show the old wheel style.
> This fix can be removed after this package is updated with the new user flow and styling for the iOS 14 date picker.

:information_source: **Update**: This quick fix is no longer recommended. Instead you should use the option `display` as described in the documentation: https://github.com/react-native-datetimepicker/datetimepicker#display-optional

There are many good solutions already in this thread.

Here is the one which worked for my team.

1. If you want back the old spinner wheel for the datepicker on iOS 14 you need to set it explicitly.
```
display={Platform.OS === "ios" ? "inline" : "default"}
```
2. Clear all caches
```
watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache
```
3. Restart your application

This works for emulators as well for real devices.

We are running this with:
* Xcode 12.2
* react-native 0.63
* @react-native-community/datetimepicker 3.0.6

**Comment by akshaypunchh** [comment]
> resolved

what is solution for center alignment of wheels?

**Comment by komelabbbas** [comment]
Any solution for expo..?
I have try many thing but not work.
Plz help

**Comment by imshreyansh** [comment]
@komelabbbas Here is a workaround for you
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/473#issuecomment-737664197

**Comment by komelabbbas** [comment]
> @komelabbbas Here is a workaround for you
> [mmazzarolo/react-native-modal-datetime-picker#473 (comment)](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/473#issuecomment-737664197)

Now it working perfectly.
I have upgrade expo sdk to latest  and also update react-native-modal-datetime-picker.

**Comment by alekseiaksenov** [comment]
Hey everyone, facing the same on Expo 38 with @react-native-community/datetimepicker installed (managed workflow).
Clearing caches and everything above does not help.
I can't go up to the 39th SDK yet.
Is there any solution for Expo?

**Comment by robertoconceicao** [comment]
@jChris85 Hello, I did that:

if (@available(iOS 14, *)) {
  UIDatePicker *picker = [UIDatePicker appearance];
  picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
}

And this work until last week, but now not woking, does everyone have tips?

**Comment by alekseiaksenov** [comment]
Hey everyone, so today the emulator client asked for an update and after updating, at least it shows the same date picker for emulator and standalone app, but still the spinner style DP does not work

**Comment by sayo96** [comment]
I'm on expo sdk 38 and i'm running into this : 
I believe it's because of the os light and dark modes. Is there a way to change color of the text in date picker?
![File](https://user-images.githubusercontent.com/26695583/101976256-72315380-3c69-11eb-8558-b7f2ae7dce18.jpg)

**Comment by SriSamVictor** [comment]
I used this code in appdelegate.

if (@available(iOS 14, *)) {
  UIDatePicker *picker = [UIDatePicker appearance];
  picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
}

But now the output is
![Screenshot 2020-12-14 at 3 16 24 PM](https://user-images.githubusercontent.com/30155214/102066290-a3538480-3e1f-11eb-84ed-1dc1b93115a8.png)

**Comment by devanshsadhotra25** [comment]
> I used this code in appdelegate.
> 
> if (@available(iOS 14, *)) {
> UIDatePicker *picker = [UIDatePicker appearance];
> picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> }
> 
> But now the output is
> ![Screenshot 2020-12-14 at 3 16 24 PM](https://user-images.githubusercontent.com/30155214/102066290-a3538480-3e1f-11eb-84ed-1dc1b93115a8.png)
> 
> Please kindly help for this.. Thanks in advance

`  if (@available(iOS 13.0, *)) {
      rootView.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
  }`
  
  u might have to use this

**Comment by disnoa** [comment]
> > if (@available(iOS 14, *)) {
> > UIDatePicker *picker = [UIDatePicker appearance];
> > picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
> > }
> 
> Hi @jChris85,
> I want to display center
> Can you help me pls?
> 
> ![image](https://user-images.githubusercontent.com/31690470/94409336-39bcc600-01a0-11eb-9908-9cf596703e8b.png)

i had the same problem with DatePickerIOS inside a modal try settimeout to re render

const DateTimePickerCUSTOM = (props) => {
    const [show, setshow] = useState(false)
    useEffect(() => {
        setTimeout(() => {
            setshow(true);
        }, 1);
    }, [])

    if (show){
        return (
            <DatePickerIOS {...props} />
        )
    }
};

<img width="302" alt="Captura de Pantalla 2020-12-30 a la(s) 3 23 09 p  m" src="https://user-images.githubusercontent.com/1731383/103373160-f0d42080-4ab2-11eb-929b-ef0e963c3b8a.png">

**Comment by codr36** [comment]
> > Out of curiosity, is there any way to toggle that datepicker popup directly, without having to go through the wheel or the new iOS 14 date inputs? ie. If I wanted to use a unified display to hold the text value, but `onPress` it would show the Android DatePicker **or** the new iOS picker modal?
> 
> Facing the same issue. Anyone found a viable solution? Thanks!

also looking for a way to do this. Probably requires a new issue?

**Comment by dorbenzvi** [comment]
Does anyone have the solution for that with expo?
This is my code:

` <DatePicker
        style={{ width: '80%' }}
        date={selectedDate}
        mode="date"
        placeholder="select date"
        format="DD-MM-YYYY"
        minDate="11-2-2021"
        maxDate="1-1-2022"
        confirmBtnText="Confirm"
        cancelBtnText="Cancel"
        customStyles={{
          dateIcon: {
            position: 'absolute',
            left: 0,
            top: 4,
            marginLeft: 0,
          },
          dateInput: {
            marginLeft: 36,
          },
          // ... You can check the source to find the other keys.
        }}
        onDateChange={(date) => {
          setDate(date)
        }}
        display={Platform.OS === 'ios' ? 'inline' : 'default'}
      />`

**Comment by ksjmb** [comment]
Need to used **customStyles** to align at center position ;

<DatePicker
    customStyles={{
      datePicker: {
        justifyContent:'center'
      }
    }}
...
/>

Thank you

**Comment by anujraghuvanshi** [comment]
> Need to used **customStyles** to align at center position ;
> 
> <DatePicker
> customStyles={{
> datePicker: {
> justifyContent:'center'
> }
> }}
> ...
> />
> 
> Thank you

Many thanks! This worked osmmm.

**Comment by sirtok4** [comment]
I solved this issue by doing a custom datepicker for IOS. Maybe it helps someone:

{Platform.OS === 'ios' && (
          <Overlay isVisible={startDatePickerShow} onBackdropPress={() => setStartDatePickerShow(false)} overlayStyle={styles.overlayStyle}>
            <View style={styles.headerStyle}>
              <TouchableOpacity onPress={() => setStartDatePickerShow(false)}>
                <Typography style={{ paddingHorizontal: 15 }}>Cancel</Typography>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => setStartDatePickerShow(false)}>
                <Typography style={{ paddingHorizontal: 15, color: 'green' }}>Done</Typography>
              </TouchableOpacity>
            </View>
            <DateTimePicker
              value={(eStartDate) ? eStartDate : new Date()}
              mode='date'
              is24Hour={true}
              display="inline"
              onChange={eStartDateOnChange}
              style={{ backgroundColor: 'white' }}
            />
          </Overlay>
        )

**Comment by vonovak** [comment]
closing as outdated, thank you

**Comment by petervn** [comment]
> Regarding the documentation setting the prop display to `spinner` worked for me as well without the need of the native "fix".

you save my day
