### ISSUE TITLE
iOS 14 minuteInterval not working in time mode

### ISSUE THREAD

**Issue by DylanVerstraete** [react-native-datetimepicker/datetimepicker#288]
I have this code set:
```
<DateTimePicker
    minuteInterval={15}
    value={start}
    mode={'time'}
    onChange={onStartChange}
/>
```
But I am still able to select minutes outside the 15 minute window

<img width="213" alt="Screenshot 2020-09-25 at 19 16 43" src="https://user-images.githubusercontent.com/17138347/94296845-caf32900-ff63-11ea-8984-fbd6abb014d9.png">

**Comment by R1D3** [comment]
same issue

**Comment by akshitrcrm** [comment]
same issue

**Comment by tadleta** [comment]
same issue
