### ISSUE TITLE
iOS datetime mode set to 24 hours

### ISSUE THREAD

**Issue by Luisquii** [react-native-datetimepicker/datetimepicker#289]
# Question
Hi,
With the new iOS 14 we have a new date time picker interface and in the mode={"datetime"} the 24 hours picker is gone, just 12 hours now when scrolling. I know is possible to manually write the hour and minutes by pressing the label but some users may not notice that.

is it possible to configure it to 24 hours or add an AM/PM button?

My date time picker:

<DateTimePicker
                        style={{ width: "100%" }}
                        locale="es-ES"
                        minimumDate={new Date()}
                        maximumDate={max_hourDateValue}
                        value={this.state.hourDateValue}
                        mode={"datetime"}
                        onChange={this.setHourAndDate}
                        is24Hour={true}
                        display="default"
                      />

image:
<img width="271" alt="Screen Shot 2020-09-27 at 22 10 05" src="https://user-images.githubusercontent.com/41712573/94386897-4c86ba80-010e-11eb-83fa-06ea693b4444.png">

**Comment by baronha** [comment]
+1

**Comment by Luisquii** [comment]
I solved it by deleting the locale option:

just commented
// locale="es-ES"

**Comment by vonovak** [comment]
hello, this is something that is controlled by the locale, see https://github.com/react-native-datetimepicker/datetimepicker#localization-note

thank you :)
