### ISSUE TITLE
Darkmode needs fix

### ISSUE THREAD

**Issue by SergiOnGit** [react-native-datetimepicker/datetimepicker#296]
![image](https://user-images.githubusercontent.com/13105977/94937107-339c5180-04e0-11eb-8e67-ded378425657.png)

I use latest version of this plugin and it looks like this on ios.

**Comment by vonovak** [comment]
Hello, please read the dark mode note here https://github.com/react-native-datetimepicker/datetimepicker#style-optional-ios-only

thanks!
