### ISSUE TITLE
How to disable DateTimePicker component?

### ISSUE THREAD

**Issue by RoTTex** [react-native-datetimepicker/datetimepicker#303]
Hello!
We need to display DateTimePicker component with disabled flag on iOS. Before iOS14 we used a special header with current time and can disable this header to prevent DateTimePicker overlay open. After iOS 14 we don't see any reasons in this header but we can't disable system DateTimePicker component. 
As I know, iOS UIDatePicker view has got `isEnabled` field, that makes what we want: prevent touches and update UI to common disable view (gray text color). As a temp solution we are using another view about our date component, however it doesn't affect component styles. But it would be nice to have the same option in this lib.

**Comment by RoTTex** [comment]
As a temp solution we are using `pointerEvents="none"`, however it doesn't affect component styles.

**Comment by chinomnsoawazie** [comment]
> Hello!
> We need to display DateTimePicker component with disabled flag on iOS. Before iOS14 we used a special header with current time and can disable this header to prevent DateTimePicker overlay open. After iOS 14 we don't see any reasons in this header but we can't disable system DateTimePicker component.
> As I know, iOS UIDatePicker view has got `isEnabled` field, that makes what we want: prevent touches and update UI to common disable view (gray text color). As a temp solution we are using another view about our date component, however it doesn't affect component styles. But it would be nice to have the same option in this lib.

This is definitely necessary

**Comment by PabloTeari** [comment]
Great question. Today I am adapting using `pointerEvents = {"none"}` in a view external to DateTimePicker.

**Comment by dd-apt** [comment]
Thanks @PabloTeari wrapping in a View w/ that prop set seems to work! Setting pointerEvents to 'auto' when not disabled.

**Comment by vonovak** [comment]
closed by #412
