### ISSUE TITLE
TypeError: Cannot read property 'getDefaultDisplayValue' of undefined

### ISSUE THREAD

**Issue by plaporte** [react-native-datetimepicker/datetimepicker#306]
The DateTimePicker is working fine on iOS simulator, however I'm getting the error above on actual device: iPhone 11 iOS 14.

![D174D8BC-99E1-401B-A247-66A46599E8EF_1_105_c](https://user-images.githubusercontent.com/23533193/95934695-1b0d2080-0d97-11eb-984e-6ce36e3e7e71.jpeg)
![03707C6A-1459-4555-B824-AE10564E3FD1_1_105_c](https://user-images.githubusercontent.com/23533193/95934723-2d875a00-0d97-11eb-9c91-dbe2b6d28b37.jpeg)

Seems to be related to some native code setting a default height?

**Comment by vonovak** [comment]
hello, please try rebuilding the project. if that does not help, then open a new issue, keeping in mind the issue template, thank you!
