### ISSUE TITLE
Picker is not returning any date or time values...

### ISSUE THREAD

**Issue by mikeRChambers610** [react-native-datetimepicker/datetimepicker#307]
The picker is not returning any date or time. Instead, when returning date from onChange, it is returning a ton of useless data below.

SyntheticEvent {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: {…}, _dispatchListeners: ƒ, …}
bubbles: (...)
cancelable: (...)
currentTarget: (...)
defaultPrevented: (...)
dispatchConfig: null
eventPhase: (...)
isDefaultPrevented: (...)
isPropagationStopped: (...)
isTrusted: (...)
nativeEvent: (...)
target: (...)
timeStamp: (...)
type: (...)
_dispatchInstances: null
_dispatchListeners: null
_targetInst: null
preventDefault: (...)
stopPropagation: (...)
get bubbles: ƒ ()
set bubbles: ƒ (val)
get cancelable: ƒ ()
set cancelable: ƒ (val)
get currentTarget: ƒ ()
set currentTarget: ƒ (val)
get defaultPrevented: ƒ ()
set defaultPrevented: ƒ (val)
get eventPhase: ƒ ()
set eventPhase: ƒ (val)
get isDefaultPrevented: ƒ ()
set isDefaultPrevented: ƒ (val)
get isPropagationStopped: ƒ ()
set isPropagationStopped: ƒ (val)
get isTrusted: ƒ ()
set isTrusted: ƒ (val)
get nativeEvent: ƒ ()
set nativeEvent: ƒ (val)
get target: ƒ ()
set target: ƒ (val)
get timeStamp: ƒ ()
set timeStamp: ƒ (val)
get type: ƒ ()
set type: ƒ (val)
get preventDefault: ƒ ()
set preventDefault: ƒ (val)
get stopPropagation: ƒ ()
set stopPropagation: ƒ (val)
__proto__: Object

Thanks a lot react native team for once again making life difficult! Need to now redesign tons of screens to use a broken library. Awesome!!!!!!

**Comment by mikeRChambers610** [comment]
Needed to pass in both the "event" and the "date". 

setDate = (event, date) => {
            this.setState({ date: date });
            }

**Comment by yalcinozer** [comment]
`<DateTimePicker
                value={Date.now()}
                minuteInterval={30}
                onChange={(val) => console.log(val)}/>`

You can easily see that the function returns an object. So you can access it by val.nativeEvent.timestamp .

`{"nativeEvent": {"timestamp": 1609337689911}, "type": "set"}`

Use a Date() constructor to make it human readable later. Don't make life harder for you, always log it to see structure before try to use it :-)

**Comment by dhirajanand014** [comment]
Is this issue resolved and how? I'm also having this issue.

**Comment by dhirajanand014** [comment]
> Is this issue resolved and how? I'm also having this issue.

`<DateTimePicker minimumDate={props.minimumDate} display={`calendar`} mode={props.mode} value={props.requestForm.needed_request_date}
                    onChange={(event, date) => {
                        if (event.type == `set`) {
                            onChangeByValueType(datePickerProps, date, props)
                        }
                    }} is24Hour={false} />`

This is failing. what needs to be done?

**Comment by dhirajanand014** [comment]
> `<DateTimePicker value={Date.now()} minuteInterval={30} onChange={(val) => console.log(val)}/>`
> 
> You can easily see that the function returns an object. So you can access it by val.nativeEvent.timestamp .
> 
> `{"nativeEvent": {"timestamp": 1609337689911}, "type": "set"}`
> 
> Use a Date() constructor to make it human readable later. Don't make life harder for you, always log it to see structure before try to use it :-)


This does not make any sense. Can you provide the working code.

**Comment by dhirajanand014** [comment]
> The picker is not returning any date or time. Instead, when returning date from onChange, it is returning a ton of useless data below.
> 
> SyntheticEvent {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: {…}, _dispatchListeners: ƒ, …}
> bubbles: (...)
> cancelable: (...)
> currentTarget: (...)
> defaultPrevented: (...)
> dispatchConfig: null
> eventPhase: (...)
> isDefaultPrevented: (...)
> isPropagationStopped: (...)
> isTrusted: (...)
> nativeEvent: (...)
> target: (...)
> timeStamp: (...)
> type: (...)
> _dispatchInstances: null
> _dispatchListeners: null
> _targetInst: null
> preventDefault: (...)
> stopPropagation: (...)
> get bubbles: ƒ ()
> set bubbles: ƒ (val)
> get cancelable: ƒ ()
> set cancelable: ƒ (val)
> get currentTarget: ƒ ()
> set currentTarget: ƒ (val)
> get defaultPrevented: ƒ ()
> set defaultPrevented: ƒ (val)
> get eventPhase: ƒ ()
> set eventPhase: ƒ (val)
> get isDefaultPrevented: ƒ ()
> set isDefaultPrevented: ƒ (val)
> get isPropagationStopped: ƒ ()
> set isPropagationStopped: ƒ (val)
> get isTrusted: ƒ ()
> set isTrusted: ƒ (val)
> get nativeEvent: ƒ ()
> set nativeEvent: ƒ (val)
> get target: ƒ ()
> set target: ƒ (val)
> get timeStamp: ƒ ()
> set timeStamp: ƒ (val)
> get type: ƒ ()
> set type: ƒ (val)
> get preventDefault: ƒ ()
> set preventDefault: ƒ (val)
> get stopPropagation: ƒ ()
> set stopPropagation: ƒ (val)
> **proto**: Object
> 
> Thanks a lot react native team for once again making life difficult! Need to now redesign tons of screens to use a broken library. Awesome!!!!!!

DId you solve the issue and how?

**Comment by dhirajanand014** [comment]
> Is this issue resolved and how? I'm also having this issue.
> 
> `<DateTimePicker minimumDate={props.minimumDate} display={`calendar`} mode={props.mode} value={props.requestForm.needed_request_date} onChange={(event, date) => { if (event.type == `set`) { onChangeByValueType(datePickerProps, date, props) } }} is24Hour={false} />`
> 
> This is failing. what needs to be done?

Any updates?

**Comment by yalcinozer** [comment]
@dhirajanand014 

What I wrote is clear. Just read the nativeEvent key.

`<RNDateTimePicker
                    value={new Date()}
                    mode={"time"}
                    onChange={(res) => {
                            console.log(res.nativeEvent.timestamp);
                        }
                    }}/>`
