### ISSUE TITLE
Trying to animate the show/hide of the datetimepicker

### ISSUE THREAD

**Issue by mattwoberts** [react-native-datetimepicker/datetimepicker#309]
Hi all.

I'm trying to animate the datetimepicker, so that similar to the add event on google calendar or apple calendar, you can click to expand / collapse the datepicker.

However, it's not playing. the date picker is stubbornly remaining there on screen, even though the view it's within expands its height as I click to toggle. Does anyone know if this is possible?

Here's the code I'm using:

```javascript
  <Animated.View style={{ backgroundColor: 'yellow', paddingRight: 10, paddingLeft: 45, paddingTop: -10, height:heightAnimation }}>
    <DateTimePicker
      testID="dateTimePicker"
      value={date}
      mode='date'
      is24Hour={true}
      display="inline"
      onChange={onChange}
    />
  </Animated.View>
```

Here's it working when it's expanded:

![image](https://user-images.githubusercontent.com/109196/96281519-585cf280-0fd1-11eb-90ab-39b8b96afc04.png)

.. but when I contract:

![image](https://user-images.githubusercontent.com/109196/96281555-6579e180-0fd1-11eb-8113-c085e9f94420.png)

Is this a limitation of the native control, or is this possible?

Thanks

**Comment by darkheartfelt** [comment]
I have found this to be an extreme limitation of this component. Upgrading from IOSDatePicker to this component is seemingly impossible because you cannot close the modal without "dismiss" event which is unable to be sent to the component.

**Comment by vonovak** [comment]
I believe there should be a way to make this work, you just need to make the `DateTimePicker` View consume animated styles. A PR for this use case is welcome.

**Comment by YaoHuiJi** [comment]
hi,@mattwoberts , have you find a way to make it work?

hi,@vonovak ,could you give me some tips about how to animate DateTimePicker view?  I try to use createAnimatedComponent to make DateTimePicker a animatable component,but an error ocurred `createAnimatedComponent does not support stateless functional components; use a class component instead.`

**Comment by mattwoberts** [comment]
This looks interesting, thanks. For my project, we decided for the time being at least to switch to the `react-native-modal-datetime-picker` package. Although we're seeing other issues with that, so it's on my todo-list to come back to this and see if we can find something that works...

**Comment by vonovak** [comment]
hello, I'm closing this as I answered here: https://github.com/react-native-datetimepicker/datetimepicker/issues/664#issuecomment-1315551752

thank you 🙂
