### ISSUE TITLE
Ok and cancel buttons

### ISSUE THREAD

**Issue by VladCherniavsky** [react-native-datetimepicker/datetimepicker#315]
Is there any option  to click "Ok/Confirm/Done" button when user has selected the time? 

<img width="373" alt="Screenshot 2020-10-21 at 00 01 59" src="https://user-images.githubusercontent.com/8988069/96643844-d6522e00-1330-11eb-80e0-9a67caf26a1a.png">

**Comment by vonovak** [comment]
Hello, no, there are no such buttons, you have to add them yourself.

Thanks!
