### ISSUE TITLE
QUESTION Can I check if this input with time is in focus?

### ISSUE THREAD

**Issue by Roka20012** [react-native-datetimepicker/datetimepicker#319]
Can I check if this input with time is in focus?

I didn't found the `onFocus` method in this lib

![image](https://user-images.githubusercontent.com/32239452/97292386-dcc23780-1853-11eb-9796-2530e6e0e11f.png)

**Comment by vonovak** [comment]
hello, sorry but I'm not aware of any way to do this. Thanks!
