### ISSUE TITLE
Unable to find a specification for React-Core dependend upon by RNDateTimePicker

### ISSUE THREAD

**Issue by 1Jesper1** [react-native-datetimepicker/datetimepicker#320]
React native: 0.59.10
@react-native-community/datetimepicker: 3.0.4

When installing/linking the datetimepicker and executing command "pod install" I get the error:
"Unable to find a specification for React-Core dependend upon by RNDateTimePicker".

This is due to the change made in: https://github.com/react-native-datetimepicker/datetimepicker/commit/3243e61f81fea8f245523a4c92bb4c98aae17789

Using @react-native-community/datetimepicker: 3.0.2 it works.

**Comment by vonovak** [comment]
hello, for react native 0.59 you need to use v3.0.2

the latest versions only support RN 0.60 and newer.

thank you!

**Comment by 1Jesper1** [comment]
@vonovak Could you add this in the readme? Compatability table?
