### ISSUE TITLE
Expo Install - "Unable to resolve "./layoutUtilsIOS"

### ISSUE THREAD

**Issue by aricsangchat** [react-native-datetimepicker/datetimepicker#322]
I installed running "expo install @react-native-community/datetimepicker" and Im getting this error "Unable to resolve "./layoutUtilsIOS" from "node_modules\@react-native-community\datetimepicker\src\datetimepicker.ios.js"
Failed building JavaScript bundle."

Here are the versions im running,
"@react-native-community/datetimepicker": "2.2.2"
react-native: 0.61.4

Im also following the Basic usage with state example in the docs.

Anyone know how to fix this? Thanks!

**Comment by d36mehta** [comment]
I also had this issue a few days ago and was able to fix it. I uninstalled it, ran `npm i`, then closed and opened the project, re-installed it (I used something similar:`expo install @react-native-community/datetimepicker --npm`), and then ran `npm i`

**Comment by vonovak** [comment]
I'm closing because it seems the issue can be resolved as described by the comment. Thank you!
