### ISSUE TITLE
iOS 14 time picker presents both 24 hours and AM PM

### ISSUE THREAD

**Issue by memelie** [react-native-datetimepicker/datetimepicker#325]
### Summary

The iOS 14 time picker presents both the 24 hours wheel and the AM/PM selector, when using locale="en-US" while the phone locale is "en-GB".

![Image d’iOS (3)](https://user-images.githubusercontent.com/12428363/97864749-07ebd180-1d01-11eb-9f5f-587ac0bd13ee.png)

### Code sample

```
<DateTimePicker  
   style={style}  
   value={date}  
   mode="time"  
   // trick to get the AM / PM button, even if the locale is "en-GB"  
   locale="en-US"  
   display="inline"  
   onChange={(event, date) => action(date?.toTimeString())}  
 />
```

## Packages
- "react": "16.13.1",
- "react-native": "0.63.3",
- "@react-native-community/datetimepicker": "^3.0.4",
## Device
- iPhone 6
- iOS 14.1
- English UK

### Question
Does someone has encountered the same issue?
How can I get the time picker to be in 12 hours format with the AM/PM option?

Thank you so much for your help

**Comment by vonovak** [comment]
should be fixed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540
