### ISSUE TITLE
Can i change language for modal picker ?

### ISSUE THREAD

**Issue by Jalsss** [react-native-datetimepicker/datetimepicker#330]
This month showing is english but i want to change Vietnamese month , can't i do it?

![Screen Shot 2020-11-06 at 2 54 01 PM](https://user-images.githubusercontent.com/64591862/98340417-e90e7780-203f-11eb-8f51-aeec79f95f9c.png)

**Comment by PabloTeari** [comment]
You can try to pass "locale" with your location string. Work for me. (v3.0.8)

```
<DateTimePicker
   minimumDate = {props.minimumDate}
   value = {initialDate}
   mode = {"datetime"}
   onChange = {(evt, date) => onChange (date)}
   locale = {"pt-br"} />  // your country 'vi-VN'? 
```

**Comment by alesdvorakcz** [comment]
Could be also this bug? #300

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
