### ISSUE TITLE
ios build error on xcode 11.13.1

### ISSUE THREAD

**Issue by Byronium** [react-native-datetimepicker/datetimepicker#331]
# Bug report

## Summary

![Screen Shot 2020-11-10 at 9 28 43 AM](https://user-images.githubusercontent.com/4009333/98727053-2fb7e680-234c-11eb-9a7f-068c5ff78aca.png)
Same as https://github.com/react-native-datetimepicker/datetimepicker/issues/261, but I am on xcode 11.13.1.

## Steps to reproduce

1. `npm install @react-native-community/datetimepicker --save`
2. `npx pod-install`

Describe what you expected to happen:

1. build succeed

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 208.59 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

datetimepicker version: 3.0.1

**Comment by Byronium** [comment]
For what it's worth, updating to Xcode 12.1 fixed this issue. I would re-evaluate the current stated minimum of 11.16.

**Comment by vonovak** [comment]
hello and thanks for reporting, 
xcode version 11.13.1 does not exist. As you see in your output, you were using 11.3.1

Thank you!

**Comment by rahulnainwal107** [comment]
User version 2.6.2 if you are using xCode version 11.1 (11A1027).
