### ISSUE TITLE
Value.getTime is not a function

### ISSUE THREAD

**Issue by Sheleya** [react-native-datetimepicker/datetimepicker#335]
## Summary

Value.getTime is not a function.
Encountered this error value.getTime is not a function ONLY in iOS. 
TypeError: value.getTime is not a function at ensureNativeIsInSyncWithJS (datetimepicker.ios.js:67)

## Reproducible sample code

```
<DateTimePicker
    style={getDateTimePickerStyles()}
    value={startTime1}
    mode="time"
    display="default"
    onChange={(e, date) => {
      toggleDatepicker1(Platform.OS === 'ios');
      if (date) {
         setStartTime1(new Date(date));
       }
   }}
/>
```

## Steps to reproduce

1. Set initial value for datepicker using new Date(year, month, date, minute, ms);
2. Try to change value 
3. Got the error (iOS only)

Describe what you expected to happen:

1. Don't see the error with predefined value after change
If I set the value new Date(), no error appears 

## Environment info

RN CLI
"react-native": "0.63.3",

datetimepicker version: "^3.0.3"

iOS / Android version: iOS 14.1

**Comment by vonovak** [comment]
hello, and thanks for reporting.
I see you opened second issue for this - I'm really sorry, but this not a runnable reproduction.

In order to fix any issue, we need to be able to copy your code and run it.

What is `startTime1`? What is `getDateTimePickerStyles` and `setStartTime1`?

We need all that code to help. Please update the description, otherwise this is not actionable, thank you!

**Comment by Sheleya** [comment]
const year = new Date().getFullYear();
const month = new Date().getMonth();
const date = new Date().getDate();
const newDate = new Date(year, month, date, 8, 11, 0);

getDateTimePickerStyles this is just a styling, it doesn't matter you can remove it

setStartTime1 is useState hook and startTime1 is a value using for DatePicker

**Comment by vonovak** [comment]
hello, I'd like to ask you to please read https://stackoverflow.com/help/minimal-reproducible-example - they explain what a maintainer needs to have before moving forward - and that is a code example that reproduces the issue. You have, so far, not provided a full example. Please read it and update the original description, thank you very much.

**Comment by jalong112358** [comment]
I am also getting this error, my component looks like so:
`const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());


	
	return (
		<View className={styles.dateFilter}>
	
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		
		</View>
	);
};

export default DateFilter;`

**Comment by jalong112358** [comment]
Im also getting this error. My component looks like so:
`
const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());


	
	return (
		<View className={styles.dateFilter}>
	
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		
		</View>
	);
};

export default DateFilter;
`

**Comment by jalong112358** [comment]
Im also getting this error. My component looks like so:
`const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());
	return (
		<View className={styles.dateFilter}>
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		</View>
	);
};`

**Comment by jalong112358** [comment]
I'm experiencing the same error. My component looks like so:
`
const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());
	return (
		<View className={styles.dateFilter}>
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		</View>
	);
};
`

**Comment by jalong112358** [comment]
I'm experiencing the same error. My component looks like so:

const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());
	return (
		<View className={styles.dateFilter}>
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		</View>
	);
};

**Comment by jalong112358** [comment]
I'm experiencing the same error. My component looks like so:
```
const DateFilter = () => {
	const [startDate, setStartDate] = useState(new Date());
	return (

		<View className={styles.dateFilter}>
			<DateTimePicker
				value={startDate}
				mode={"date"}
				display={"default"}
				onChange={(date) => setStartDate(date)}
			/>
		</View>
	);
};
```

**Comment by jalong112358** [comment]
When you are setting your date within the onChange, try replacing ` setStartTime1(new Date(date));` with this  setStartTime1(date);

**Comment by jalong112358** [comment]
I was experiencing the same error and this is what worked for me.
When you are setting your date within the onChange, try replacing setStartTime1(new Date(date)); with this `setStartTime1(date);`

**Comment by jalong112358** [comment]
I was experiencing the same error and this is what worked for me.
When you are setting your date within the onChange, try replacing `setStartTime1(new Date(date))`; with this `setStartTime1(date);`
