### ISSUE TITLE
is there a way to set max time of the day and min time of the day?

### ISSUE THREAD

**Issue by b0nbon1** [react-native-datetimepicker/datetimepicker#338]

**Comment by jaynguyen89** [comment]
I want same thing. Just looked into their source code, no such thing is implemented.

**Comment by gelfer** [comment]
Hope this helps:

<DateTimePicker
mode="time"
is24Hour={true}
display="spinner"
minimumDate={new Date('2021-06-28T00:00:00.000Z').getTime() + 1800000}
maximumDate={new Date('2021-06-28T04:00:00.000Z').getTime() - 1800000}
...other props
/>

**Comment by Aryan6290** [comment]
> Hope this helps:
> 
> <DateTimePicker
> mode="time"
> is24Hour={true}
> display="spinner"
> minimumDate={new Date('2021-06-28T00:00:00.000Z').getTime() + 1800000}
> maximumDate={new Date('2021-06-28T04:00:00.000Z').getTime() - 1800000}
> ...other props
> />

How to do this in ts?

**Comment by vonovak** [comment]
Hello, I'm afraid this is something you'll have to implement yourself in your JS code.

thank you 🙂
