### ISSUE TITLE
iOS compact style needs a width, is stuck left aligned

### ISSUE THREAD

**Issue by chrisdrackett** [react-native-datetimepicker/datetimepicker#339]
I'm trying to use the new compact date picker style in iOS but I'n having a hard time styling it.

When I first put it in I got the following:

```
<DateTimePicker
    display="compact"
    mode="date"
    value={DateTime.local().toJSDate()}
/>
```

<img width="521" alt="CleanShot 2020-11-16 at 17 09 50@2x" src="https://user-images.githubusercontent.com/4378/99327354-98accc00-282e-11eb-96b7-ee6d7d2d5801.png">

The date picker is the gray square on the right. I tried to set `flex: 1` but that didn't get things to display. Next I just set a width:

```
<DateTimePicker
    style={{width: 140}}
    display="compact"
    mode="date"
    value={DateTime.local().toJSDate()}
/>
```

<img width="521" alt="CleanShot 2020-11-16 at 17 11 50@2x" src="https://user-images.githubusercontent.com/4378/99327454-d90c4a00-282e-11eb-8eec-bcd231b2e1da.png">

Now I can see the date picker, but it's too far to the left. I'd like to right align it. At this point I got stuck. Nothing I seemed to do right aligns the picker and because I don't know the width (which is variable based on the contents).

Anyone run into this yet? any ideas?

**Comment by saksham2410** [comment]
Give the datepicker a style with width 100% and wrap it in a view with <View style={{width: '100%', padding: 40}}>

**Comment by chrisdrackett** [comment]
as far as I can tell this is also an issue with the native component. I've seen it mentioned on swift forums as well so I'm guessing we'll just have to wait for apple to update the component.

**Comment by jaketoolson** [comment]
I've just run into this and was going crazy!

**Comment by fjarrett** [comment]
While we wait for a more permanent fix, my dirty workaround ended up looking something like this:

```jsx
<View style={{ alignItems: 'center', width: '100%' }}>
  <DateTimePicker
    display="compact"
    mode="datetime"
    style={{ width: 230 }}
  />
</View>
```

**Comment by ASchwad** [comment]
A year has passed, any updates on this issue?

**Comment by HighDeck** [comment]
I'm really praying for a fix! 
Defining width is not reliable when switching locales :(

**Comment by otaviogaiao** [comment]
Just got this bug, is the problem really on the native side or in the lib?

**Comment by Adrian93Box** [comment]
Any updates?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
as of v6.3.4 the width should now be computed by the native side and you should not need to specify it manually.
If you're still running into problems, please open a new issue.
Thank you 🙂
