### ISSUE TITLE
Can't Update Package

### ISSUE THREAD

**Issue by oporter1** [react-native-datetimepicker/datetimepicker#348]
# Bug report

## Summary
iOS 14 is having issues with datetimepicker so I attempted to update to the latest release 3.0.6. When I run npm install @react-native-community/datetimepicker or npm update @react-native-community/datetimepicker, it states that everything is up to date which is not correct. I am stuck on version 2.2.2. 

## Reproducible sample code

terminal:
    ------$ npm update @react-native-community/datetimepicker
    up to date, audited 2908 packages in 24s

package.json
    "@react-native-community/datetimepicker": "2.2.2",

## Steps to reproduce
open terminal, update package with npm 
remove package-lock.json
remove node modules
clear cache
npm install

or npm install @react-native-community/datetimepicker --force

or manually change the version number and do above steps again to clear cache and rebuild node modules

nothing seems to work to get the package updated. which I am not even sure is actually the root cause of why the spinner isn't working on iOs 14.

1. open terminal, update package with npm 
2. remove package-lock.json
3. remove node modules
4. clear cache
5. npm install

Describe what you expected to happen:

I expected my datetimepicker package to be updated to 3.0.6

## Environment info

`npx react-native info` output:

```bash
ystem:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 36.87 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

datetimepicker version: 2.2.2

iOS / Android version: iOs 14.2

**Comment by vonovak** [comment]
hello, please try `npm install @react-native-community/datetimepicker@latest` 

otherwise I don't know why you should be stuck with an old version. Sound like an issue with npm, not this library

thank you!
