### ISSUE TITLE
Xcode 11.3 doesn't support datetimepicker

### ISSUE THREAD

**Issue by Haris-Shahid** [react-native-datetimepicker/datetimepicker#351]
![Screenshot 2020-11-28 at 11 48 21 PM](https://user-images.githubusercontent.com/16974444/100536412-49bf4900-31d5-11eb-8151-db3d1a85e1f5.png)

Note: Please for the error look into the screenshot I shared

I need help in resolving this for me I am using old Mac which does not support Mac OS latest version and this the last version I updated which is Xcode 11.3 and It doesn't update more

I searched a lot in google and find this solution to update Xcode to Xcode 11.6 but that I am not able to do it can anyone help me to resolve this?

**Comment by vonovak** [comment]
hello and thanks for asking the question.
Unfortunately, there is no way for us to support older XCode versions. The only way you can resolve this is that you'll buy a newer machine which supports latest MacOS, and by extension, latest XCode.

Hope this makes sense, thank you!
