### ISSUE TITLE
Does this package supports entering date manually as shown in the image?

### ISSUE THREAD

**Issue by Yandamuri** [react-native-datetimepicker/datetimepicker#352]
# Question

![Capture](https://user-images.githubusercontent.com/31983789/100990412-da03e200-3577-11eb-8efc-3b18d08fc209.PNG)

Usually date pickers allow users to select any date from the calendar. Besides to that I want to allow user to enter date manually as shown in the image.

**Comment by vonovak** [comment]
hello, you'll have to create such textinput yourself. Thank you
