### ISSUE TITLE
RNDateTimePicker was not found

### ISSUE THREAD

**Issue by MarioSilvaPrada** [react-native-datetimepicker/datetimepicker#357]
# Question

Hey guys,

After import and pod install the packages, the following error shows up when I use <DateTimePicker />.

Any ideas why?

![image](https://user-images.githubusercontent.com/35892161/101337889-256a0900-3874-11eb-815b-b1c602aa648a.png)

Thank you

Cheers

**Comment by vonovak** [comment]
hello and thanks for reporting, please try one of these: 

https://stackoverflow.com/questions/61832232/invariant-violation-requirenativecomponent-rncwebview-was-not-found-in-the-u

it that does not work, please open a new issue and please follow the issue template, thanks!
