### ISSUE TITLE
Open datepicker instantly on IOS instead of showing up a button

### ISSUE THREAD

**Issue by ingerable** [react-native-datetimepicker/datetimepicker#361]
# Question

"@react-native-community/datetimepicker": "^2.6.2"

On IOS 14.2 when I show my ```<DateTimePicker``` component I have a button showing up instead of a popup like android. The picker only appears when I click on the button. ( see the screenshot below for the comparison )
Is there a workaround to show directly the datepicker instead of a button on IOS 14 ? 

![Capture d’écran 2020-12-10 à 14 09 09](https://user-images.githubusercontent.com/26652057/101776592-776b9280-3af1-11eb-9264-d635ee8a5dc1.png)

**Comment by ferasabufares** [comment]
same problem any solution please

**Comment by limk10** [comment]
some problem here, heeeelp :(

**Comment by vonovak** [comment]
> Is there a workaround to show directly the datepicker instead of a button on IOS 14 ?

please see https://github.com/react-native-datetimepicker/datetimepicker#display-optional

and use `display="spinner"`

@limk10 please open a new issue and follow the template, thanks!
