### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RNDateTimePicker"

### ISSUE THREAD

**Issue by BogdanRad** [react-native-datetimepicker/datetimepicker#362]
I have this error when i run `pod install`.

![image](https://user-images.githubusercontent.com/40359109/101790521-37190e00-3b0b-11eb-8f45-8b1869261a7f.png)

How can i fix this problem?

**Comment by AlejandroGutierrezB** [comment]
Have a better look at the end of the error `cocoapods dependency were found but they required a higher minimum deployment target`. 

Change it in your podfile. Also, make sure the global platform in your Podfile matches the highest minimum target required by any dependency.

I am using it in `platform :ios, '10.0'`. IOS10 will mean supporting over 90% of the devices so you should really have a good reason not to update.

Hope it helps!

**Comment by vonovak** [comment]
hello, please see https://stackoverflow.com/questions/36182969/cocoa-pods-error-with-pod-install

Thank you!
