### ISSUE TITLE
Open datepicker instantly on IOS instead of showing up a button

### ISSUE THREAD

**Issue by limk10** [react-native-datetimepicker/datetimepicker#364]
Problem here, heeeelp :(

In my "debug" ambient and testflight work, but in production in Apple Store not working the component as expected, shows only one button as mentioned above

![Group 1](https://user-images.githubusercontent.com/20530933/101834461-c70d8680-3b10-11eb-9b02-9099fded2cf7.png)

[UPDATE]: **!!RESOLVED!!** - As I was using code push to deploy, it didn’t upload / ios files just from the project root, it was necessary to deploy a new version to Apple Store and "VOILÁ", the Date Picker it's working, easy peasy lemon squeezy :grimacing:

**Comment by vonovak** [comment]
as I have said, please follow the issue template, otherwise this is not actionable, thanks!

**Comment by wolfag** [comment]
duplicate with: [https://github.com/react-native-datetimepicker/datetimepicker/issues/285](url)
