### ISSUE TITLE
Exception thrown on iOS 14 beta if textColor is set

### ISSUE THREAD

**Issue by nimabrownlee** [react-native-datetimepicker/datetimepicker#367]
# Bug report

## Summary

There's been a bug report about this but it's closed on the assumption that it's fixed. But it isn't in the latest version `3.0.8`.
https://github.com/react-native-datetimepicker/datetimepicker/issues/247

## Reproducible sample code

This is very easy to reproduce so I'll skip this step.

## Steps to reproduce

Add `textColor` prop to DateTimePicker.

## Environment info

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

```

datetimepicker version: `3.0.8`

iOS / Android version: `14 / -`

**Comment by vonovak** [comment]
hello and thanks for reporting, please add a reproducible sample, thank you!

**Comment by nimabrownlee** [comment]
@vonovak 

Seems the issue is with https://github.com/mmazzarolo/react-native-modal-datetime-picker as they've not updated to the latest version. Thanks!
