### ISSUE TITLE
reactNative.NativeModules.RNDatePickerAndroid.dismiss

### ISSUE THREAD

**Issue by kaleemnisar478** [react-native-datetimepicker/datetimepicker#369]
[Unhandled promise rejection: TypeError: _reactNative.NativeModules.RNDatePickerAndroid.dismiss is not a function. (In '_reactNative.NativeModules.RNDatePickerAndroid.dismiss()', '_reactNative.NativeModules.RNDatePickerAndroid.dismiss' is undefined)]

**Comment by vonovak** [comment]
hello, please rebuild your project

**Comment by OsamahMohammed** [comment]
Just FYI, if you're using expo, remive this package and install it using `expo install`, then clear cache.
