### ISSUE TITLE
Apps Crash When Click OK or Cancel (Android 10 Tested)

### ISSUE THREAD

**Issue by YuddiPrase** [react-native-datetimepicker/datetimepicker#370]
# Bug report

## Summary
Apps Crash When Click OK or Cancel

## Reproducible Sample Code
`{this.state.isShow ? <DateTimePicker
          testID={ this.props.testID || "dateTimePicker"}
          value={this.props.date}
          mode={'date'}
          is24Hour={true}
          display="default"
          onChange={this.props.onDateChange}
					style={{ elevation: 10 }}
        /> : null}
				<TouchableNativeFeedback 
					onPress={() => this.setState({ isShow: !this.state.isShow })}
				>
					<View style={{ flex: 1, height: 40 }}>
						<Text style={{ fontSize: 16 }}>{ 'Click date time' }</Text>
					</View>
				</TouchableNativeFeedback>`
				
				
## Steps to reproduce
<img width="125" alt="Screen Shot 2020-12-17 at 03 24 10" src="https://user-images.githubusercontent.com/30163412/102402537-82ee1a80-4017-11eb-81be-edc446debce0.png">
Click OK or Cancel

## Environment info
datetimepicker version: 3.0.8
<img width="326" alt="Screen Shot 2020-12-17 at 03 06 47" src="https://user-images.githubusercontent.com/30163412/102400709-e88cd780-4014-11eb-869c-3de2132c65bc.png">

Android Version: 10
React Native: 0.63.1
<img width="182" alt="Screen Shot 2020-12-17 at 03 07 42" src="https://user-images.githubusercontent.com/30163412/102400845-09edc380-4015-11eb-8d6f-2b7176a6d77f.png">

**Comment by Saeid-Barzegar** [comment]
@YuddiPrase , you closed this issue
I have the same problem. how you fixed it ?

https://github.com/react-native-datetimepicker/datetimepicker/issues/371
