### ISSUE TITLE
Problem with date picker on android

### ISSUE THREAD

**Issue by Saeid-Barzegar** [react-native-datetimepicker/datetimepicker#371]
# Question

how can I control the cancel button action in the android date picker?
i want to change the showAndroidPicker to false

![image](https://user-images.githubusercontent.com/10572916/102464053-d9467200-4086-11eb-996f-af104e9d7f57.png)

when I pressing on Cancel button on the date-picker it will close but on showing the picker again it shows this error

![image](https://user-images.githubusercontent.com/10572916/102464739-b36d9d00-4087-11eb-81d4-7e68c221cdc0.png)

this is my code

![image](https://user-images.githubusercontent.com/10572916/102464802-ca13f400-4087-11eb-826c-5d7871bb9822.png)

**Comment by Saeid-Barzegar** [comment]
Solved!
previously this library had two separate events for okay and cancel
but know both of them handled by the **onChange** event
this code fixed my issue 

![image](https://user-images.githubusercontent.com/10572916/102564311-1c9bf180-4116-11eb-863d-f9c9b00e20e9.png)

**Comment by junaid-jazsoft** [comment]
How can I unsubscribe for email notifications?

**Comment by vonovak** [comment]
closing as resolved, thank you
