### ISSUE TITLE
Memory leak: RNDatePicker DialogFragment Leaked.

### ISSUE THREAD

**Issue by AjayShivanagol** [react-native-datetimepicker/datetimepicker#373]
Known leak pattern: instance field android.os.Message#obj
Description: A thread waiting on a blocking queue will leak the last dequeued object as a stack local reference. So when a HandlerThread becomes idle, it keeps a local reference to the last message it received. That message then gets recycled and can be used again. As long as all messages are recycled after being used, this won't be a problem, because these references are cleared when being recycled. However, dialogs create template Message instances to be copied when a message needs to be sent. These Message templates holds references to the dialog listeners, which most likely leads to holding a reference onto the activity in some way. Dialogs never recycle their template Message, assuming these Message instances will get GCed when the dialog is GCed. The combination of these two things creates a high potential for memory leaks as soon as you use dialogs. These memory leaks might be temporary, but some handler threads sleep for a long time. To fix this, you could post empty messages to the idle handler threads from time to time. This won't be easy because you cannot access all handler threads, but a library that is widely used should consider doing this for its own handler threads. This leaks has been shown to happen in both Dalvik and ART.
1751 bytes retained
┬
├─ android.os.HandlerThread
│    Leaking: UNKNOWN
│    Thread name: 'queued-work-looper'
│    GC Root: Java local variable
│    ↓ thread HandlerThread.<Java Local>
│                           ~~~~~~~~~~~~
├─ android.os.Message
│    Leaking: UNKNOWN
│    ↓ Message.obj
│              ~~~
├─ com.reactcommunity.rndatetimepicker.RNDismissableDatePickerDialog
│    Leaking: YES (Dialog#mDecor is null)
│    ↓ RNDismissableDatePickerDialog.mCancelMessage
├─ android.os.Message
│    Leaking: YES (RNDismissableDatePickerDialog↑ is leaking)
│    ↓ Message.obj
├─ androidx.fragment.app.DialogFragment$2
│    Leaking: YES (Message↑ is leaking)
│    Anonymous class implementing android.content.DialogInterface$OnCancelListener
│    ↓ DialogFragment$2.this$0
╰→ com.reactcommunity.rndatetimepicker.RNDatePickerDialogFragment
​     Leaking: YES (DialogFragment$2↑ is leaking and Fragment#mFragmentManager is null and ObjectWatcher was watching this)
​     key = 689d5b4b-bf5e-4dc3-93b8-f378d3510b54
​     watchDurationMillis = 490296
​     retainedDurationMillis = 485200

METADATA

Build.VERSION.SDK_INT: 28
Build.MANUFACTURER: Google
LeakCanary version: 2.0-beta-5
App process name: com.xxxx.xxxx
Analysis duration: 11235 ms

![Screenshot_1608740533](https://user-images.githubusercontent.com/29257275/103017353-7e6eb800-4569-11eb-9955-1d267d963521.png)
![Screenshot_1608740540](https://user-images.githubusercontent.com/29257275/103017360-82023f00-4569-11eb-8cd3-06d6f49dd55f.png)

Can anyone help?

Thanks in Advance!!

**Comment by angusmunro** [comment]
What version of this package are you using?

**Comment by 1Ajay** [comment]
@angusmunro Thanks for replying..

 "react-native-modal-datetime-picker": "^9.0.0",
 "@react-native-community/datetimepicker": "3.0.1",

**Comment by angusmunro** [comment]
You should see if an upgrade to 3.0.8 fixes your issue, there was work done on fragments for the latest release: 

https://github.com/react-native-datetimepicker/datetimepicker/commit/267a20fbdb1e2220e80b0bea8c9068f6e07cf2df

**Comment by FernandoDiCostanzo** [comment]
Which version this leak belongs to
