### ISSUE TITLE
How can I get "25-12-2020" instead of "2020-12-25T22:02:40.037Z"?

### ISSUE THREAD

**Issue by tahademirer** [react-native-datetimepicker/datetimepicker#375]
# Question
Im using that component on my Android emulator. On "date" mode, it gives me the output with the format of "2020-12-25T22:02:40.037Z". I just want to get "DD-MM-YYYY". How can I handle this problem? 
Thanks.

**Comment by hardcodet** [comment]
This is a standards ISO 8601 date, which is pretty much the best option you can get. You can easily parse this into a Date object and format in any way you want. Google is your friend ;)

https://stackoverflow.com/questions/25159330/convert-an-iso-date-to-the-date-format-yyyy-mm-dd-in-javascript

**Comment by vonovak** [comment]
closing as answered, thank you :)
