### ISSUE TITLE
Error message with RN Date Picker Android using Expo 4.0.16

### ISSUE THREAD

**Issue by raphael-guedj** [react-native-datetimepicker/datetimepicker#376]
# Question
Hi,

I'm using React Native Modal Datetime Picker and I have an error message since 2 weeks but can't find where it's does from. It usually reboot the app . I saw there was some version conflict but i'm up to date with expo

here is the message i get in the terminal

[Unhandled promise rejection: TypeError: _reactNative.NativeModules.RNDatePickerAndroid.dismiss is not a function. (In '_reactNative.NativeModules.RNDatePickerAndroid.dismiss()', '_reactNative.NativeModules.RNDatePickerAndroid.dismiss' is undefined)]

Would you know why it's happening?

is it related to this snippet : 
`const onChange = (event, selectedDate) => {
    const currentDate = selectedDate || date;
    setShow(Platform.OS === "ios");`

Thanks,

**Comment by vonovak** [comment]
hello, thanks for reporting; you probably installed the lib using `yarn install`, please install using `expo install` as seen in https://docs.expo.io/versions/latest/sdk/date-time-picker/

otherwise please open a new issue, thanks
