### ISSUE TITLE
possible to make timepicker as duration?

### ISSUE THREAD

**Issue by gpbaculio** [react-native-datetimepicker/datetimepicker#378]
i am thinking of using timepicker as duration but can't think of a way if it's possible? and limit the duration the user can set?

**Comment by vonovak** [comment]
hello, the closest you can get using the `mode="countdown"` prop, but this is only available on iOS, android does not support this natively so we cannot have it either. See a screenshot in https://developer.apple.com/documentation/uikit/uidatepicker?language=objc

hope this helps :)
