### ISSUE TITLE
maxTime and minTime for countdown mode

### ISSUE THREAD

**Issue by pvanny1124** [react-native-datetimepicker/datetimepicker#381]
maxTime and minTime props for countdown mode in order to set a range of values (i.e0 to 3 hours)

sometimes there is no need to have all 24 hours in some cases.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I'm not aware of the native component offering such functionality, so this is not actionable from our side.

You'll have to create your own coundown picker with max and min time.

Thank you 🙂
