### ISSUE TITLE
RNDatePicker Not found in UIManager Xcode 12.3

### ISSUE THREAD

**Issue by ajen010** [react-native-datetimepicker/datetimepicker#382]
# Bug report

## Summary

Tried to run DatePicker on a react native app and the app won't build on the ios emulator

## Reproducible sample code

<img width="377" alt="Screen Shot 2021-01-01 at 10 16 11 PM" src="https://user-images.githubusercontent.com/320949/103437713-f67e6180-4c7e-11eb-930a-919e849484ac.png">
import React, { useState } from 'react';
import DatePicker from 'react-native-date-picker';

const TimePicker = () => {

  const [date, setDate] = useState(new Date());

  return (
    \<DatePicker
      date={date}
      onDateChange={setDate}
      `mode="time"`
    />
  );
};

export { TimePicker }; 

## Steps to reproduce

Use Xcode version 12.3
npm install react-native-date-picker --save
cd ios && pod install

Try to run the code using cocoapods on a MacBook pro
The TimePicker is called with <TimePicker /> in app.js

Describe what you expected to happen:

1. I expect to see a timepicker on the emulator

## Environment info

I am not using expo

`npx react-native info` output:
react-native-cli: 2.0.1
react-native: 0.63.4
```bash
# paste it here
```

datetimepicker version: 3.2.7

iOS / Android version: emulator only at this stage ios 14.3

**Comment by mhammerc** [comment]
Have you run `pod install`? I remember had the same error when forgetting to update pods.

**Comment by ajen010** [comment]
Yes I ran pod install from the ios directory.

**Comment by mhammerc** [comment]
Have you recompiled then restarted your app?

**Comment by ajen010** [comment]
I closed the app and restarted and the timepicker works. Thanks!
