### ISSUE TITLE
React-Native-Windows TimePicker not working ?

### ISSUE THREAD

**Issue by creambyemute** [react-native-datetimepicker/datetimepicker#383]
# Bug report

## Summary

Using DateTimePicker on React-Native-Windows with `mode` `time` doesn't render anything

## Reproducible sample code

* Init RN-Windows project
* Add DateTimepicker
* Set mode to `time`

## Steps to reproduce

* Init RN-Windows project
* Add DateTimepicker
* Set mode to `time`

Describe what you expected to happen:

Time Picker is shown

## Environment info

`npx react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 20.71 GB / 31.86 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.10586.0, 10.0.14393.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 13.0.2 - /c/Program Files/OpenJDK/jdk-13.0.2/bin/javac
    Python: 2.7.14 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: ^0.63.0-0 => 0.63.11
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.0.4 - Latest (tried them all)

@rectified95 Do you maybe have an idea why? Date mode works though. Maybe related to https://github.com/microsoft/react-native-windows/issues/5437 ?

**Comment by creambyemute** [comment]
I actually found the solution in the example folder.

You need to give a style with height for the TimePicker to show up. This should be mentioned on the Readme maybe?

**Comment by rectified95** [comment]
Hey @creambyemute thanks so much for doing the investigation! Components not rendering without the height specified is a known issue now that we have fixed for those in the RNW repo. It has to do with specifying a custom Yoga measure function. There is work required to expose this API to view managers over the ABI boundary. 

Coming back to your question - yes, https://github.com/microsoft/react-native-windows/issues/5437#issuecomment-670726301 is where this is captured. I think a good mitigation for now is to add a default height value to the style sheet for TimePicker. Would you be able to create a PR fixing this?

**Comment by creambyemute** [comment]
@rectified95 You mean in the Windows implementation directly? I'd rather mention it in the README? But anyway, yeah I can do that.

**Comment by hossamnasser938** [comment]
Time picker does not appear when being nested in a view with flexDirection: 'row', Any idea how to fix that? @rectified95
