### ISSUE TITLE
Date picker UI is different 

### ISSUE THREAD

**Issue by shahidcodes** [react-native-datetimepicker/datetimepicker#385]
# Question

The date picker UI is showing differently than in this screenshot [image](https://github.com/react-native-datetimepicker/datetimepicker/blob/master/docs/images/ios_date.png?raw=true). I remember when I implemented this few months back the UI looked and behaved same but today when I am checking UI looks like this 
[image](https://user-images.githubusercontent.com/17620737/105338044-17dcc880-5c01-11eb-83c7-e271611878de.jpg)

Is there any change in DatePicker UI in iOS ?

```javascript
 <DateTimePicker
          value={dateSlot.date}
          mode="date"
          display="default"
          onChange={onChange}
          onConfirm={() => {}}
          onCancel={() => {}}
        />
```

P.S. - I am using Expo SDK 38

**Comment by vonovak** [comment]
hello, this is the expected behavior on ios 14, you can control it with `display` prop, thank you!
