### ISSUE TITLE
minimumDate & maximumDate UI issue

### ISSUE THREAD

**Issue by kaushalmarakana** [react-native-datetimepicker/datetimepicker#387]
Hello

I need help regarding an issue with **minimumDate** and **maximumDate**. 

If I pass this 2 props, both platform has different behavior. Ex

- Android - It is showing only years that match this condition. Like if the min date year is **2000** and the max is **2020** then it only shows 2000 to 2020 years in the year selection picker. (**Expected Behaviour**) 
- Ios - it shows all years from 0000. But allows selecting only years that match these min and max conditions. (**Unexpected Behaviour**)

I want behavior like an android in ios too.

do anyone knows is a library issue or not? Or Is it open for contribution?

@vonovak

**Comment by vonovak** [comment]
Hello, this is the expected behavior of each of the platforms, so it's not a bug as far as I can tell. If you want to unify the behavior, I'm afraid you'll need to write a custom date picker for iOS.

Hope this helps ☺

**Comment by kaushalmarakana** [comment]
Thanks for the clarification @vonovak
