### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by ksielyov** [react-native-datetimepicker/datetimepicker#388]
Hello!

I write `locale='ru'`

It doen`t work

**Comment by vonovak** [comment]
hello, please try `ru-RU`

**Comment by ksielyov** [comment]
> ru-RU

Hello. It doesn`t work.

**Comment by ksielyov** [comment]
This is my code: 
`
<DateTimePicker
        testID="dateTimePicker"
        value={date}
        mode={"countdown"}
        is24Hour={true}
        display="default"
        locale={'ru-RU'}
        onChange={onChange}
        style={{ backgroundColor: "#fff" }}
      />
`

**Comment by Gitarcitano** [comment]
> This is my code:
> `<DateTimePicker testID="dateTimePicker" value={date} mode={"countdown"} is24Hour={true} display="default" locale={'ru-RU'} onChange={onChange} style={{ backgroundColor: "#fff" }} />`

Try this:

```js
<DateTimePicker 
  testID="dateTimePicker"
  value={date}
  mode={"countdown"}
  is24Hour={true}
  display="default"
  locale="ru-RU"
  onChange={onChange}
  style={{ backgroundColor: "#fff" }}
/>
```

**Comment by MatBdry** [comment]
Hi,

I got the same issue on my Emulator, where the default language was... English. I changed it to French and now it's working ;)

I hope it helps

**Comment by alenseferovic1** [comment]
Locale doesn't work on the android. Any suggestions here?

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
