### ISSUE TITLE
How to import RNDateTimePicker?

### ISSUE THREAD

**Issue by shamxeed** [react-native-datetimepicker/datetimepicker#389]
# I want to make a migrate and trying to follow as shown in the readME section, I already installed the package/whatever using expo, but can not seem to find how to import \<RNDateTimePicker /> \. Something like it is not included in the package.

**Comment by vonovak** [comment]
hello, sorry I didn't undrstand. You can import it like 

`import DateTimePicker from '@react-native-community/datetimepicker';`

or `import RNDateTimePicker from '@react-native-community/datetimepicker';`

the name under which you import does not really matter

hope this helps
