### ISSUE TITLE
Picker not returning any values in Android and IOS for version datetimepicker 3.0.9

### ISSUE THREAD

**Issue by dhirajanand014** [react-native-datetimepicker/datetimepicker#391]
The picker is not returning any date or time. Instead, when returning date from onChange, it is returning a ton of useless data below.

SyntheticEvent {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: {…}, _dispatchListeners: ƒ, …}
bubbles: (...)
cancelable: (...)
currentTarget: (...)
defaultPrevented: (...)
dispatchConfig: null
eventPhase: (...)
isDefaultPrevented: (...)
isPropagationStopped: (...)
isTrusted: (...)
nativeEvent: (...)
target: (...)
timeStamp: (...)
type: (...)
_dispatchInstances: null
_dispatchListeners: null
_targetInst: null
preventDefault: (...)
stopPropagation: (...)
get bubbles: ƒ ()
set bubbles: ƒ (val)
get cancelable: ƒ ()
set cancelable: ƒ (val)
get currentTarget: ƒ ()
set currentTarget: ƒ (val)
get defaultPrevented: ƒ ()
set defaultPrevented: ƒ (val)
get eventPhase: ƒ ()
set eventPhase: ƒ (val)
get isDefaultPrevented: ƒ ()
set isDefaultPrevented: ƒ (val)
get isPropagationStopped: ƒ ()
set isPropagationStopped: ƒ (val)
get isTrusted: ƒ ()
set isTrusted: ƒ (val)
get nativeEvent: ƒ ()
set nativeEvent: ƒ (val)
get target: ƒ ()
set target: ƒ (val)
get timeStamp: ƒ ()
set timeStamp: ƒ (val)
get type: ƒ ()
set type: ƒ (val)
get preventDefault: ƒ ()
set preventDefault: ƒ (val)
get stopPropagation: ƒ ()
set stopPropagation: ƒ (val)
proto: Object

Considering the below code, the date value does not return anything. The value of event.nativeEvent.timestamp is also not the right value to refer. Please help - 

`<DateTimePicker minimumDate={props.minimumDate} display={'calendar'} mode={props.mode} value={props.requestForm.needed_request_date} onChange={(event, date) => { if (event.type == set) { onChangeByValueType(someProp, date, props) } }} is24Hour={false} />`

**Comment by vonovak** [comment]
hello, thanks for reporting.

Please take a look at the example https://github.com/react-native-datetimepicker/datetimepicker/blob/master/example/App.js

this module has a bunch of e2e tests that prove that it is working (https://github.com/react-native-datetimepicker/datetimepicker/blob/master/example/e2e/detoxTest.spec.js), so you're probably doing something wrong and we'll need you to follow the issue template to accept a bug, thank you.
