### ISSUE TITLE
Cannot choose earlier or future date in iOS 14.3 devices

### ISSUE THREAD

**Issue by Maharshi01** [react-native-datetimepicker/datetimepicker#392]
iOS: 14.3
react-native-modal-datetime-picker: 9.1.0
react-native-community/datetimepicker: 3.0.9
react-native: 0.61.2
react: 16.9.0

Iam unable to select earlier or future date only in iOS 14.3 device, in other andorid or iOS devices i am able to select though...the code which implemeted is :
<DateTimePicker
cancelTextStyle={{ color: '#173154' }}
isVisible={this.state.showTime}
onConfirm={this.handleTimePicked}
title={strings.customerSupport.Set_Time}
is24Hour={false}
titleIOS={strings.customerSupport.setTime}
mode={"time"}
maximumDate={this.state.date === moment(new Date()).format('DD MMM YYYY') ? new Date() : null}
onCancel={this.hideTimePicker}
isDarkModeEnabled={false}
/>

**Comment by vonovak** [comment]
hello, this part of the condition will never be true `this.state.date === moment(new Date()).format('DD MMM YYYY')` which is likely an issue. Thank you!
