### ISSUE TITLE
Cannot install datetimepicker for ios

### ISSUE THREAD

**Issue by VilleMiekkoja** [react-native-datetimepicker/datetimepicker#394]
# Question

I try to install datetimepicker by following the docs but can't seem to succeed.

Upon pod install I get the following error message:

> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Unable to find a specification for `React-Core` depended upon by `RNDateTimePicker`

> You have either:
   >* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
   >* mistyped the name or version.
   >* not added the source repo that hosts the Podspec to your Podfile.

Tried running pod repo update but no effect.

My RN version is: 0.59.10

**Comment by vonovak** [comment]
hello, unfortunately the newest version does not support RN 0.59.

you can try undoing this commit https://github.com/react-native-datetimepicker/datetimepicker/commit/3243e61f81fea8f245523a4c92bb4c98aae17789#diff-96ed3c14300362ac3567810aee05de8db8b7dfba31489b5ca5fd8e4103fe8206 locally and it might work, but the best thing to do would be to upgrade to latest RN

Thanks!

**Comment by VilleMiekkoja** [comment]
Tried that and got this error:

> Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager.
> 
> This error is located at:
>     in RNDateTimePicker (at datetimepicker.ios.js:110)

**Comment by vonovak** [comment]
https://www.google.com/search?rlz=1C5CHFA_enCZ901CZ901&biw=1629&bih=895&sxsrf=ALeKk00hbhvB0SwduKXTlb6G98h31twd6g%3A1612816966733&ei=RqIhYL2cLNKwrgTHsJOoCw&q=requireNativeComponent%3A++was+not+found+in+the+UIManager.+site%3Astackoverflow.com&oq=requireNativeComponent%3A++was+not+found+in+the+UIManager.+site%3Astackoverflow.com&gs_lcp=CgZwc3ktYWIQAzoHCAAQRxCwA1D5CVj5CWCbDGgBcAJ4AIABQ4gBgwGSAQEymAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwi9146zk9vuAhVSmIsKHUfYBLUQ4dUDCA0&uact=5

**Comment by VilleMiekkoja** [comment]
Was able to get it working by linking this library manually: https://archive.reactnative.dev/docs/linking-libraries-ios
