### ISSUE TITLE
IOS UI Picker Select not working

### ISSUE THREAD

**Issue by methineeinkan** [react-native-datetimepicker/datetimepicker#395]
![Screen Shot 2564-02-08 at 19 30 08](https://user-images.githubusercontent.com/40588602/107219747-1a824f00-6a44-11eb-99f1-eb2f7f160847.png)

**Comment by vonovak** [comment]
actually, this might be related to dark mode, see this: https://github.com/react-native-datetimepicker/datetimepicker#style-optional-ios-only
