### ISSUE TITLE
V3.0.9 - How to change Android default Theme of date picker

### ISSUE THREAD

**Issue by TylerNRobertson** [react-native-datetimepicker/datetimepicker#400]
Hey everyone. Ive seen the answer in the issues before at #20 but none of the solutions in there work with the current version.

datetimepicker version: 3.0.9

**Comment by vonovak** [comment]
Hello, thanks for reporting. Let's please keep the discussion in one place: #20.

I believe we have a PR for this (#221) but it stalled and no one picked it up. You're welcome to have a look and finish it up. Thanks.
