### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNDateTimePicker

### ISSUE THREAD

**Issue by sovp-89** [react-native-datetimepicker/datetimepicker#401]
# Question
 Hi, please somebody help me!

I've got this error after I install this module for Expo, I just imported the component and use it as in the example but the app is no longer working, any idea what is happening or what to [do?](url
![WhatsApp Image 2021-02-23 at 16 39 07](https://user-images.githubusercontent.com/56313928/108917689-c22b7f80-75f5-11eb-9717-608e07fd63b0.jpeg)
)

Thanks in advance!

**Comment by kmkrtich** [comment]
Same for me on IOS, without expo
