### ISSUE TITLE
Set firstDayOfWeek to Monday on iOS

### ISSUE THREAD

**Issue by SanKlein** [react-native-datetimepicker/datetimepicker#410]
# Feature request

firstDayOfWeek is only supported on Windows, can someone please add support on iOS?

## Why it is needed

Support for a calendar setting for weeks starting on Monday instead of Sunday.

## Possible implementation

I am not sure what the implementation would be. Hopefully similar to Windows?

### Code sample

It should work similar to Windows.

**Comment by ASchwad** [comment]
@vonovak Could you point us in the direction where work is needed to solve this issue? I would like to contribute

**Comment by vonovak** [comment]
hello, as far as I'm aware, the pickers take this information from the application locale. I'm not aware of any other way to specify this (it's possible I'm wrong though).

Thank you :)

**Comment by ASchwad** [comment]
Oh you are right - thanks!
