### ISSUE TITLE
How to get a consistent return format from international users?

### ISSUE THREAD

**Issue by oporter1** [react-native-datetimepicker/datetimepicker#415]
My `@react-native-community/datetimepicker` is working great in the US but my international users are seeing a mixed up output. I assume this is because they input their DOB differently then we typically do here (ie: MM/DD/YYYY). 

Is there a way to make sure the returned value is in a consistent format no matter where the user is located? 

```
import DateTimePickerModal from "@react-native-community/datetimepicker";

    const handleConfirm = (event, date) => {
        hideDatePicker();
        handleInput("birthday", date.toLocaleDateString());
    };

    <DateTimePickerModal
                testID="dateTimePicker"
                value={new Date(birthday)}
                mode="date"
                display="spinner"
                onChange={handleConfirm}
                style={{
                  flex: 1,
                  backgroundColor: Colors.White,
                  marginLeft: -100,
                }}
    />
```

**Comment by vonovak** [comment]
Hello and thanks for reporting.

Yes, where I'm from (europe) we use DD/MM/YYYY normally

You should be able to supply user locale `toLocaleDateString ` to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#parameters - would that not work? You can find user locale via https://github.com/zoontek/react-native-localize#getlocales

Note that depending on what JS engine you're using (hermes, JSC - where behavior might differ between ios and android) you might need to install Intl polyfills or consult https://github.com/facebook/hermes/issues/23). Hope this helps :)

**Comment by oporter1** [comment]
I am using `toLocaleDateString` in my `handleConfirm()` method. do you mean using it in another way?

**Comment by vonovak** [comment]
@oporter1 please see the docs and examples: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#using_locales that should clarify it 🙂

**Comment by oporter1** [comment]
got it thank you!
