### ISSUE TITLE
Showing the DatePicker doesn't show the picker, just the selected date...

### ISSUE THREAD

**Issue by alxvallejo** [react-native-datetimepicker/datetimepicker#420]
Really confused by this.

![image](https://user-images.githubusercontent.com/947203/112210841-93eb9080-8bf1-11eb-869d-fe146cb0527c.png)

This is what i see when i show the datepicker. Then i have to click it again to pull up the 'date' mode. Then selecting a date doesn't close the picker.

```
                <View style={styles.content}>
                    <Text style={styles.contentHeadText}>Date</Text>
                    <TouchableOpacity style={[]} onPress={() => setShowDatePicker(true)} accessibilityRole='button'>
                        <Text>{moment(selectedDate).format('MMM DD')}</Text>
                    </TouchableOpacity>
                    {selectedDate && showDatePicker && (
                        <DateTimePicker
                            style={styles.dropdownContainer}
                            mode={'date'}
                            display='default'
                            minimumDate={now}
                            value={selectedDate}
                            onChange={handleDateChange}
                            textColor={'#000000'}
                        />
                    )}
                </View>

```

My change handler:

```
    const handleDateChange = (event, date) => {
        setSelectedDate(date)
        setShowDatePicker(Platform.OS === 'ios')
    }
```

All I want to do is select a date and have it close with my state updated...

**Comment by Yadro** [comment]
Just change `display` to `"inline"` it will show date picker.
To close picker you should set false `setShowDatePicker(false)`. In your case `Platform.OS === 'ios'` return `true`.

**Comment by genesy** [comment]
is it not possible to show the dialog when shown?

**Comment by HJaffery** [comment]
> Really confused by this.
> 
> ![image](https://user-images.githubusercontent.com/947203/112210841-93eb9080-8bf1-11eb-869d-fe146cb0527c.png)
> 
> This is what i see when i show the datepicker. Then i have to click it again to pull up the 'date' mode. Then selecting a date doesn't close the picker.
> 
> ```
>                 <View style={styles.content}>
>                     <Text style={styles.contentHeadText}>Date</Text>
>                     <TouchableOpacity style={[]} onPress={() => setShowDatePicker(true)} accessibilityRole='button'>
>                         <Text>{moment(selectedDate).format('MMM DD')}</Text>
>                     </TouchableOpacity>
>                     {selectedDate && showDatePicker && (
>                         <DateTimePicker
>                             style={styles.dropdownContainer}
>                             mode={'date'}
>                             display='default'
>                             minimumDate={now}
>                             value={selectedDate}
>                             onChange={handleDateChange}
>                             textColor={'#000000'}
>                         />
>                     )}
>                 </View>
> ```
> 
> My change handler:
> 
> ```
>     const handleDateChange = (event, date) => {
>         setSelectedDate(date)
>         setShowDatePicker(Platform.OS === 'ios')
>     }
> ```
> 
> All I want to do is select a date and have it close with my state updated...

Did you find any solution. I am also stuck on the same issue

**Comment by MaxwellHangry** [comment]
I was having this problem too, and solved it with this youtube video: https://www.youtube.com/watch?v=lpIEpggB6o4
The trick is to make whatever display you want and then pop off a modal for the DateTimePicker, thus avoiding that annoying little default display.

**Comment by MaxwellDG** [comment]
I was having this problem too, and solved it with this youtube video: https://www.youtube.com/watch?v=lpIEpggB6o4
The trick is to make whatever display you want and then pop off a modal for the DateTimePicker, thus avoiding that annoying little default display.

**Comment by ksamdb** [comment]
I changed a display mode to 'spinner' to solve this issue.

**Comment by iKoru** [comment]
any solutions for default(calendar) display?

**Comment by caolong0204** [comment]
> I changed a display mode to 'spinner' to solve this issue.

it's not enough to solve issue, i have set spinner at early

**Comment by vonovak** [comment]
hello,
change your onChange handler to 

```
    const handleDateChange = (event, date) => {
        setSelectedDate(date)
        setShowDatePicker(false)
    }
```

and the picker will hide.

Thank you 🙂
