### ISSUE TITLE
Spinner Doesn't Stay Open

### ISSUE THREAD

**Issue by oporter1** [react-native-datetimepicker/datetimepicker#421]
Is there an elegant way to keep the spinner open until the user has clicked MM DD and YYYY? Or keep it open for a set amount of seconds?

Right now current functionality is: when a user scrolls/spins to the month, the picker closes immediately because I am hiding the picker after they set the value which is closing the picker after each input. If I don't do this then the picker never closes and it is a bad user experience. Is there a timer or a good way to handle only closing the picker after the user has completed all field inputs?

```
const handleConfirm = (event, date) => {
       handleInput("birthday", date.toLocaleDateString("en-US"));
       hideDatePicker();
    };
 
     const hideDatePicker = () => {
        setShow(!show);
      };

        {show && (
              <DateTimePickerModal
                    testID="dateTimePicker"
                   value={new Date(birthday)}
                    mode="date"
                    display="spinner"
                    onChange={handleConfirm}
                    style={{
                      flex: 1,
                      backgroundColor: Colors.White,
                      marginLeft: -100,
                    }}
              />
        )}

```

**Comment by sumitsk1** [comment]
> Is there an elegant way to keep the spinner open until the user has clicked MM DD and YYYY? Or keep it open for a set amount of seconds?
> 
> Right now current functionality is: when a user scrolls/spins to the month, the picker closes immediately because I am hiding the picker after they set the value which is closing the picker after each input. If I don't do this then the picker never closes and it is a bad user experience. Is there a timer or a good way to handle only closing the picker after the user has completed all field inputs?
> 
> ```
> const handleConfirm = (event, date) => {
>        handleInput("birthday", date.toLocaleDateString("en-US"));
>        hideDatePicker();
>     };
>  
>      const hideDatePicker = () => {
>         setShow(!show);
>       };
> 
>         {show && (
>               <DateTimePickerModal
>                     testID="dateTimePicker"
>                    value={new Date(birthday)}
>                     mode="date"
>                     display="spinner"
>                     onChange={handleConfirm}
>                     style={{
>                       flex: 1,
>                       backgroundColor: Colors.White,
>                       marginLeft: -100,
>                     }}
>               />
>         )}
> ```

same issue!!
Did you find any solution ??

**Comment by robsonsr** [comment]
same issue!!
Did you find any solution ??

**Comment by robsonsr** [comment]
My solution:
Put inside Modal when IOS
![Simulator Screen Shot - iPhone 11 - 2021-05-06 at 14 22 01](https://user-images.githubusercontent.com/9003593/117340945-e4544000-ae77-11eb-95af-598ca4656689.png)

**Comment by ararog** [comment]
@robsonsr did almost same modal here. Looks way better!
