### ISSUE TITLE
iOS Date picker dose not open automatically

### ISSUE THREAD

**Issue by isipisi281** [react-native-datetimepicker/datetimepicker#425]
Hello together,

i have a problem on my iOS Devices.
On iOS when i show the picker, it dosent open automatically like in android.
So when i set show:true on android the picker appears and looks like this:

![android](https://user-images.githubusercontent.com/8292225/112492957-055a4900-8d82-11eb-9e97-8f85946740fd.png)

If i run the same code on iOS there is a new component spawning to the bottom of my page.
I have to click it so the date picker opens.

![ios1](https://user-images.githubusercontent.com/8292225/112493115-291d8f00-8d82-11eb-9835-50f511952c5c.png) 
![ios2](https://user-images.githubusercontent.com/8292225/112493138-2e7ad980-8d82-11eb-8381-bb63bf724198.png)

Am i doing something wrong?
I am running RN 0.64.0

Here is my Code.

```javascript
import React from 'react'
import DateTimePicker from '@react-native-community/datetimepicker'
import PropTypes from 'prop-types'

class ApeDatePicker extends React.PureComponent  {
  
  // constructor
  constructor(props) {
    super(props)
    this.state = {
      date: new Date(),
      mode: 'date', 
      show: false,
    }
  }

  onChange = (event, selectedDate) => {
    if (selectedDate) {
      this.setState({ date: selectedDate })
      this.props.dateSelected(selectedDate)
      this.close()
    }
    if (event.type == "dismissed") {
      this.close()
    }
  };

  open() {
    this.setState({ show: true })
  }

  close() {
    this.setState({ show: false })
  }

  render() {
    return (
      this.state.show ? (
        <DateTimePicker
          value={this.state.date}
          mode={this.state.mode}
          is24Hour={true}
          display={'default'}
          onChange={this.onChange}
        />
      ) : null
    );
  }
}

ApeDatePicker.propTypes = {
  dateSelected: PropTypes.func,
}

export default ApeDatePicker

```

**Comment by vonovak** [comment]
Hello, that is the expexted behavior. On ios, users have to tap on the control to activate it.

Thank you!

**Comment by namantayal** [comment]
Try using display="inline"
