### ISSUE TITLE
I have not found styles view selected datetimepicker property display = "spinner"

### ISSUE THREAD

**Issue by khuongsatou** [react-native-datetimepicker/datetimepicker#426]
# Question

I intend to custom your datetimepicker like picture 1 but can't find your styles selected property. Can you tell I custom styles?
![image](https://user-images.githubusercontent.com/44874881/112717659-bc8cc680-8f20-11eb-9128-a0fba81bbf5f.png)

![image](https://user-images.githubusercontent.com/44874881/112717796-69674380-8f21-11eb-9336-697c13190deb.png)

**Comment by jaimeagudo** [comment]
Are there any plans to allow for tweaking that? I played with `style` but I couldn't find the right property to tweak the selected row `backgroundColour`

**Comment by khuongsatou** [comment]
> Are there any plans to allow for tweaking that? I played with `style` but I couldn't find the right property to tweak the selected row `backgroundColour`

waiting admin reply you, I not found

**Comment by LuisD20** [comment]
i want to modify the styles

**Comment by vonovak** [comment]
hello, the style customizations are limited. All the options that the package offers are documented in readme.

thank you
