### ISSUE TITLE
Locale props not working with IOS countdown mode

### ISSUE THREAD

**Issue by ingerable** [react-native-datetimepicker/datetimepicker#429]
# Locale props not working with IOS countdown mode

## Summary
When I am using the mode Props with "countdown"  value the strings are not translated even though I filled
the locale props with "fr-FR" value. Locale props is working well for "date" mode but not for "countdown" mode.

## Reproducible sample code

```
<DateTimePicker
                mode={"countdown"}
                locale={"fr-FR"}
                style={{ height: "80%" }}
                value={new Date(0, 0, 0, 0, 1, 5)}
              />
```

## Steps to reproduce

1. Create a DateTimePicker 
2. Set props mode to "countdown"
3. Set props locale to "fr-FR"

Describe what you expected to happen:

1. "hours" and "min" strings should be translated to French

## Environment info

"datetimepicker": "3.4.3"
"react-native": "0.63.3"

IOS 14

**Comment by MatBdry** [comment]
Hi,

I got the same issue on my Emulator, where the default language was... English. I changed it to French and now it's working ;)

J'espère que ça t'a aidé !

**Comment by ingerable** [comment]
It may work if you want you want to use the native language of the device but what if you want to support multiple language ? With a dynamic locale ?
Merci quand même !

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
