### ISSUE TITLE
Improve year browsing in Android

### ISSUE THREAD

**Issue by davidgittegui** [react-native-datetimepicker/datetimepicker#430]
# Feature request

In Android select the year is not intuitive at all.

## Why it is needed

he most usable and intuitive would be that by clicking on the month you could navigate through the months and clicking on the year you could navigate by year. 

It is not intuitive that you have to click on the year to be able to change it, so they believe that they have to navigate month by month until they reach, for example, 1974 from the current year, 2021.

![image](https://user-images.githubusercontent.com/81964051/113568595-29831900-9611-11eb-9cff-5aa10e522004.png)

**Comment by vonovak** [comment]
Hello and thanks for reporting. The date picker is provided by the android OS and we cannot alter its appearance much. What we could do to improve your use case is open the date picker with year selection first. This is being tracked here: https://github.com/react-native-datetimepicker/datetimepicker/issues/67

Thanks!🙂

**Comment by davidgittegui** [comment]
> Hello and thanks for reporting. The date picker is provided by the android OS and we cannot alter its appearance much. What we could do to improve your use case is open the date picker with year selection first. This is being tracked here: #67
> 
> Thanks!🙂

Thank you very much for your quick response!

**Comment by vonovak** [comment]
hello @davidgittegui, you're more than welcome 🙂 I see you are new on github so let me use this message to politely ask you to not give +1 comments to GH issues, such as here https://github.com/react-native-datetimepicker/datetimepicker/issues/67 - in general, comments that do not add any useful information to a topic end up just cluttering other people's inboxes and are considered spam 🙂 If you use the emojis to react to messages that will be much nicer, thank you! 👍
