### ISSUE TITLE
[Android] Time picker doesn't close when unmounted (with fix)

### ISSUE THREAD

**Issue by juanamd** [react-native-datetimepicker/datetimepicker#432]
# Bug report

## Summary
Time picker native dialog does not close when it is unmounted on Android (did not test iOS).
Looked at the code and [this line](https://github.com/react-native-datetimepicker/datetimepicker/blob/cde07fb82bf66f968917fb0a527dc65d4b88ebdb/src/timepicker.android.js#L44) seems to be the issue. After changing it to:
`return NativeModules.RNTimePickerAndroid.dismiss();` (Notice the "RNTime" instead of "RNDate")
it then works as expected.

Seems to be a copy/paste issue with [this PR](https://github.com/react-native-datetimepicker/datetimepicker/pull/337).
Doing a PR for this seems a bit overkill so if any maintainer could fix this I would appreciate it.

## Steps to reproduce

1. Open the time picker
2. Unmount the caller component

Describe what you expected to happen:

1. Time picker should close when unmounted

## Environment info

`npx react-native info` output:

```bash
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 3.35 GB / 15.87 GB
  Binaries:
    Node: 15.4.0 - ~\AppData\Local\Temp\yarn--1618015864599-0.593455401429519\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1618015864599-0.593455401429519\yarn.CMD
    npm: 7.0.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.0.28803.352 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_181
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.4.3

Android version: 11

**Comment by vonovak** [comment]
hello and thanks for reporting :)

> Doing a PR for this seems a bit overkill so if any maintainer could fix this I would appreciate it.

well, I daresay opening a PR would cost you the same amount of time as filling out this issue template and I would then just press the "merge" button and we would be done with this 😄 but yeah, I'll fix this some point soon, if you don't beat me to it

**Comment by juanamd** [comment]
> well, I daresay opening a PR would cost you the same amount of time as filling out this issue template and I would then just press the "merge" button and we would be done with this 😄

You overestimate my ability to submit PRs 😂
Thanks for taking care of it!
