### ISSUE TITLE
[3.4.5] R.style.ClockTimePickerDialog

### ISSUE THREAD

**Issue by NicholasBertazzonAga** [react-native-datetimepicker/datetimepicker#437]
# Bug report

Hi, I saw that in the last commit you changed how you access ClockTimePickerDialog, it now gives me a build error:

```error: cannot find symbol
                  ? R.style.ClockTimePickerDialog
                           ^
  symbol:   variable ClockTimePickerDialog
  location: class style
```

I mean 5f0c8ee98b13775e7fbb38b902b84d32774b8790

react-native: 0.64.0

**Comment by aishwarya-k11** [comment]
? R.style.ClockTimePickerDialog
                           ^
  symbol:   variable ClockTimePickerDialog
  location: class style

Same issue
"react-native": "0.64.0"
