### ISSUE TITLE
language for turkish

### ISSUE THREAD

**Issue by oguzhan10** [react-native-datetimepicker/datetimepicker#439]
I am trying to change the language for turkish but I cant.

<DateTimePicker
            testID="dateTimePicker"
            value={date}
            mode={mode}
            locale='tr'
            is24Hour={true}
            display="default"
            onChange={onChange}
/>
I wrote to locale='tr', locale='tr-tr', locale={'tr'},locale='tr-TR' ,locale='tur' but any of them didn't work. How can I change the language please.

**Comment by farukozdemirz** [comment]
@oguzhan10  Simulatorden çalıştırmaya çalışıyorsanız cihazın default dilini baz alır. Default dil türkçe olarak seçili bir cihaz ile deneyin.

**Comment by farukozdemirz** [comment]
Test with a phone with a default language of Turkish.

**Comment by oguzhan10** [comment]
ok I will try mate thanks.

**Comment by systemride** [comment]
Can confirm this works. Can you close ticket?

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
