### ISSUE TITLE
Timepicker AM/PM backwards

### ISSUE THREAD

**Issue by consciousweb** [react-native-datetimepicker/datetimepicker#440]
# Bug report

## Summary

Am and pm options for time picker return opposite of what they should be.

## Reproducible sample code

<DateTimePicker
                            testID="timePicker"
                            value={this.state.currentDate}
                            mode={"time"}
                            is24Hour={false}
                            display="spinner"
                            onChange={this.onTimeChange}
                        />

## Steps to reproduce

select a time with am/pm

Describe what you expected to happen:

5am would be 5:00
instead, 5am is 17:00

## Environment info

expo 4.3.5

`npx react-native info` output:

    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 642.76 MB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

datetimepicker version: 3.4.6

iOS / Android version: latest/sim

**Comment by vonovak** [comment]
hello, you did not specify what platform this is on, but I just tried with android and I cannot reproduce on v5.

thank you
