### ISSUE TITLE
npm ERR! code ERESOLVE

### ISSUE THREAD

**Issue by Goowwy** [react-native-datetimepicker/datetimepicker#441]
How can i install lib

$ expo install @react-native-community/datetimepicker
Installing 1 SDK 41.0.0 compatible native module using npm.
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.3" from @react-native-community/datetimepicker@3.2.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"3.2.0" from the root project
npm ERR!   1 more (react-native)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.2.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"3.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\A\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\A\AppData\Local\npm-cache\_logs\2021-04-22T05_58_11_786Z-debug.log

npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at ChildProcess.cp.emit (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
    ...
    at Object.spawnAsync [as default] (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:166:31)
    at NpmPackageManager.addAsync (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:105:18)
    at installAsync (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\src\commands\install.ts:130:3)
    at Command.<anonymous> (C:\Users\A\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:350:7)

**Comment by daoma90** [comment]
I'm seeing the same error message. Tried to install this package today.

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nemas_native@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.3" from @react-native-community/datetimepicker@3.4.6
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.4.6
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\David\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Local\npm-cache\_logs\2021-04-22T09_29_41_471Z-debug.log`

Not using Expo

**Comment by pengships** [comment]
same error message

npm install @react-native-community/datetimepicker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.3" from @react-native-community/datetimepicker@3.4.6
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"*" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.4
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.4.6
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
--------------------------------------------------

npm install @react-native-community/datetimepicker@3.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"^16.0" from @react-native-community/masked-view@0.1.10
npm ERR!   node_modules/@react-native-community/masked-view
npm ERR!     peer @react-native-community/masked-view@">= 0.1.0" from @react-navigation/stack@5.14.4
npm ERR!     node_modules/@react-navigation/stack
npm ERR!       @react-navigation/stack@"^5.14.4" from the root project
npm ERR!     @react-native-community/masked-view@"^0.1.10" from the root project
npm ERR!   peer react@"16 || 17" from @react-native-picker/picker@1.15.0
npm ERR!   node_modules/@react-native-picker/picker
npm ERR!     @react-native-picker/picker@"^1.15.0" from the root project
npm ERR!   11 more (@react-navigation/core, @react-navigation/native, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.11.0" from react-native-windows@0.62.22
npm ERR! node_modules/@react-native-community/datetimepicker/node_modules/react-native-windows
npm ERR!   optional react-native-windows@"^0.62.0-0" from @react-native-community/datetimepicker@3.0.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by CR0J22** [comment]
_Português_

Estava com o mesmo problema e achei 2 jeitos de resolver.
Metodo 1: 
Usar a tag --force assim
_`npm install @react-native-community/datetimepicker --save --force`_
**Esse metodo ta incompatibilidade com dispositivos android**

Metodo 2:
Baixar uma versão antiga
` npm install @react-native-community/datetimepicker@3.2.0 `

_Inglês_

I had the same problem and I found 2 ways to solve it.
Method 1:
Use the --force tag like this
`npm install @ react-native-community / datetimepicker --save --force `
**This method is incompatible with android devices**

Method 2:
Download an old version 
`npm install @ react-native-community / datetimepicker @ 3.2.0`

**Comment by daoma90** [comment]
I found another way to make it work. I installed it with 
`npm install @react-native-community/datetimepicker --legacy-peer-deps`

**Comment by tim92109** [comment]
I had to use a combination of the suggestions for it to work and stop displaying the warning when using 'expo start'.  The warning said it was expecting version 3.0.0.  And it would not install unless I used the --force flag as in:
npm install @react-native-community/datetimepicker@3.0.0 --force

**Comment by brentvatne** [comment]
react-native-windows should not be a peer dep, it is an *optional peer dep* which is not actually a thing npm can express. i'd recommend removing all of the peer deps from the package.json, though. react and react-native are pointless to add as peer deps to a react-native library

**Comment by tim92109** [comment]
If 3.0.0 is working is there any benefit to upgrading to 3.5.1?

**Comment by rosnk** [comment]
while upgrading to expo sdk 41, i was using this module and i got this error: 

```
Some dependencies are incompatible with the installed expo package version:
 - @react-native-community/datetimepicker - expected version: 3.2.0 - actual version installed: 3.5.2
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
```

if i use 3.2.0 i get this error: 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.3" from @react-native-community/datetimepicker@3.2.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"~3.2.0" from the root project
npm ERR!   1 more (react-native)
```

**Comment by tim92109** [comment]
It's been a while so you may need to update the version, but here are a couple installs that didn't work (just for reference) and one that did.

DID NOT WORK
npm install @react-native-community/datetimepicker --legacy-peer-deps

DID NOT WORK
npm install @react-native-community/datetimepicker@3.0.0

WORKED
npm install @react-native-community/datetimepicker@3.0.0 --force

NOT SURE (but might be better for the version your expo instance is expecting)
So maybe try changing the version to 3.2.0 like
npm install @react-native-community/datetimepicker@3.2.0 --force

**Comment by brentvatne** [comment]
alternatively, install npm 6 instead of npm 7, or yarn v1
