### ISSUE TITLE
Be able to set interval between hours minutes

### ISSUE THREAD

**Issue by ValchanOficial** [react-native-datetimepicker/datetimepicker#450]
Be able to set interval between hours minutes

maximumTime (optional) like maximumDate
minimumTime (optional) like minimumDate 

<RNDateTimePicker minimumTime={} = maximumTime={} />
// minimumTime = 01:00 
// maximumTime = 05:00
// result = show only time between 01:00 and  05:00

**Comment by yogendra1jain** [comment]
+1 @ValchanOficial

**Comment by vonovak** [comment]
hello, the TimePicker does not support min and max time (see https://github.com/react-native-datetimepicker/datetimepicker#maximumdate-optional), as documented.

Thank you
