### ISSUE TITLE
Disabling some specific dates.

### ISSUE THREAD

**Issue by baros-code** [react-native-datetimepicker/datetimepicker#452]
I have a program which users can take reservations for some available dates and times. I looked at the documentation but didn't see how can I disable some days and time. For example i will get an array of busy dates from database and I want these dates to be invisible to the user so that he/she can not select those. Is there any way i can achieve this behaviour? Any help will be appreciated thank you.

**Comment by vonovak** [comment]
hello and thanks for reporting. This is, unfortunately, not possible as the native apis do not provide such option. 

thank you!
