### ISSUE TITLE
Minute Interval of 60 minutes

### ISSUE THREAD

**Issue by ericqqqqq** [react-native-datetimepicker/datetimepicker#462]
# Feature request

Able to only select hour or minute.

## Why it is needed

Based on the requirements of the app, the users should be only able to select hours instead of a specific time.

## Possible implementation

1. I thought it would be a solution if the minute interval can be set to 60 minute
2. Since having minute interval of 60 minutes will make minute selection extra, it would be better if we can lock the minute selection.

### Code sample

I don't have a code sample implemented at the moment.

**Comment by vonovak** [comment]
hello, this is not possible as per https://developer.apple.com/documentation/uikit/uidatepicker/1615998-minuteinterval?language=objc

thank you
