### ISSUE TITLE
Inline iOS display in react native Modal is freezing application

### ISSUE THREAD

**Issue by zaharzagrava** [react-native-datetimepicker/datetimepicker#463]
# Bug report

## Summary

I run this code and it works:

```
import React, { FC } from 'react';
import { Modal, Text, View, TouchableOpacity } from 'react-native';

import DateTimePicker from '@react-native-community/datetimepicker';

const App: FC = () => (
  <Modal
    animationType="fade"
    transparent
    visible
    onRequestClose={ () => {} }
  >
    <View
      style={{
        backgroundColor: 'rgba(0, 0, 0, .3)',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
      }}>
      <TouchableOpacity><Text>as</Text></TouchableOpacity>
      {/* <DateTimePicker
        mode={ 'date' }
        value={ new Date() }
        onChange={ () => {} }
        display="inline"
      /> */}
    </View>
  </Modal>
);

export default App;
```

I uncomment the DateTimePicker element and the application freezes:

```
import React, { FC } from 'react';
import { Modal, Text, View, TouchableOpacity } from 'react-native';

import DateTimePicker from '@react-native-community/datetimepicker';

const App: FC = () => (
  <Modal
    animationType="fade"
    transparent
    visible
    onRequestClose={ () => {} }
  >
    <View
      style={{
        backgroundColor: 'rgba(0, 0, 0, .3)',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
      }}>
      <TouchableOpacity><Text>as</Text></TouchableOpacity>
      <DateTimePicker
        mode={ 'date' }
        value={ new Date() }
        onChange={ () => {} }
        display="inline"
      />
    </View>
  </Modal>
);

export default App;

```

## Steps to reproduce

Paste the code pieces from above.

Describe what you expected to happen:

To not freeze :/

## Environment info

```
    "@react-native-community/datetimepicker": "3.2.0",
    "expo": "^41.0.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
```

iOS version: 14.4, 14.5.1

**Comment by D10S60948** [comment]
Having the same problem with the "default" display (ios 14.5)

**Comment by kevinhylant** [comment]
Having the same problem also on iOS 14.5

**Comment by mmazzarolo** [comment]
This seems to happen only i development mode for me.

**Comment by tylercote** [comment]
Running into this issue as well.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
This is dues to conflicting layout constraints; if you remove the `alignItems` from your styles, it will not freeze the app. Please try to achieve what you need without that style and it should work.

Thank you 🙂

**Comment by danielmark0116** [comment]
Hi, just writing a small FIY for anyone having a similar issue with modals freezing (it was a freeze in my case, not a crash) the app on iOS.

In my case it was happening only on `release` type of builds.

What was causing the issue was the animated bar component (simple line that was being animated over time). Basically the bar was representing a countdown and the modal could be opened during the animation.

The line had `width` property animated with reanimated (v2). After changing the animation to target `translateX` in place of `width`, the problem disappeared :)

**Comment by zzAlexzz** [comment]
in my case, I am using @react-navigation/drawer 6.62 and react-native-reanimated 2.12.4 with @react-native-community/datetimepicker 6.3.5, when I pick a date from next 3 month, swith to a screen, then using drawer navigation to switch back, UI was just freezing and I cannot see any error from xcode as well

**Comment by kohchihao** [comment]
I have recently faced this issue as well. I am displaying the iOS calendar within `@gorhom/bottom-sheet` with their `BottomSheetModal`. It crashes when the bottom sheet is displayed and I quickly select a date. No solution and no error logs from xcode as well.

**Comment by zzAlexzz** [comment]
Finally I used "react-native-date-picker": "4.2.13", and all animation works fine.

**Comment by mphill** [comment]
When using `react-native-datetimepicker `in `@gorhom/bottom-sheet` with their `BottomSheetModal`, you're app will lock up completely and will require a forced quit.

I moved my settings to a page to resolve, I found no workarounds.

**Comment by kohchihao** [comment]
I recently chanced upon this piece of code from another library. https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.ios.js#L187 

I have tried it and it seems that setting the height for the calendar component (`height: 370`) seems to resolve the freezing issue.

**Comment by ser-emejia** [comment]
> I recently chanced upon this piece of code from another library. https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.ios.js#L187
> 
> I have tried it and it seems that setting the height for the calendar component (`height: 370`) seems to resolve the freezing issue.

I'm using `@gorhom/bottom-sheet` with `BottomSheetModal` and this solution looks like works for me, thank you.

**Comment by EricBorland** [comment]
> > I recently chanced upon this piece of code from another library. https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.ios.js#L187
> > I have tried it and it seems that setting the height for the calendar component (`height: 370`) seems to resolve the freezing issue.
> 
> I'm using `@gorhom/bottom-sheet` with `BottomSheetModal` and this solution looks like works for me, thank you.

hey @ser-emejia can you share your solution?
I have tried the following but still freezes my app when inside the BottomSheetModal
```
 <DateTimePicker
    testID="dateTimePicker"
    value={fromUTC(value)}
    mode={'time'}
    is24Hour={true}
    onChange={(evt, startTime) => onChange(toUTC(startTime))}
    style={{
      height: 36
    }}
/>
```

Is there anything else am I missing?

Thanks

**Comment by hoscahmet** [comment]
> I recently chanced upon this piece of code from another library. https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.ios.js#L187
> 
> I have tried it and it seems that setting the height for the calendar component (`height: 370`) seems to resolve the freezing issue.

this solution looks like works for me, thank you.

**Comment by ser-emejia** [comment]
> > > I recently chanced upon this piece of code from another library. https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.ios.js#L187
> > > I have tried it and it seems that setting the height for the calendar component (`height: 370`) seems to resolve the freezing issue.
> > 
> > 
> > I'm using `@gorhom/bottom-sheet` with `BottomSheetModal` and this solution looks like works for me, thank you.
> 
> hey @ser-emejia can you share your solution? I have tried the following but still freezes my app when inside the BottomSheetModal
> 
> ```
>  <DateTimePicker
>     testID="dateTimePicker"
>     value={fromUTC(value)}
>     mode={'time'}
>     is24Hour={true}
>     onChange={(evt, startTime) => onChange(toUTC(startTime))}
>     style={{
>       height: 36
>     }}
> />
> ```
> 
> Is there anything else am I missing?
> 
> Thanks

Hey man, sorry for the late response, but I did something like this and works good:

```
    <BottomSheetModal
      index={0}
      ref={sheet_ref}
      snapPoints={snap_points}
      enablePanDownToClose={true}
      backdropComponent={renderBackdropComponent}>
      <Box pH="s">
        <DateTimePicker
          mode={mode}
          value={date}
          display="spinner"
          minimumDate={min_date}
          maximumDate={max_date}
          // height needs to be 370 for working inside bottom sheet modal
          style={{ height: 370 }}
          onChange={onChangeDateValue}
        />
        <Button rounded={true} onPress={confirmNewDate}>
          Confirm
        </Button>
      </Box>
    </BottomSheetModal>
```
