### ISSUE TITLE
iOS 14 Datepicker inside modal

### ISSUE THREAD

**Issue by scott-massey** [react-native-datetimepicker/datetimepicker#464]
# Feature request

I added an issue [here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/570#issue-898228796) in a library that uses this one, but thought I should share it here too.

I figured out a way to wrap the new iOS 14 date picker inside a modal without having the weird show up before. Is this something that people would want implemented in this library? If so I could work on a PR to either make a new mode that wraps the `inline` mode in a modal like shown. 

## Why it is needed

The current implementation of the iOS 14 date picker can be pretty confusing, especially if you are trying to tie this component to a custom text input.

## Possible implementation

I've gotten this all working in my own setup, and I think it would be pretty straightforward to implement it directly in the library. It'll need the `Modal`, `Dimensions`, and `Keyboard` objects from `react-native` core. No extra libraries needed.

### Code sample

If people are interested in this, I can share my setup in a little more detail, or just get started on a PR myself...

Here's what it looks like:
![new-datepicker](https://user-images.githubusercontent.com/54546509/119171932-de8b5c80-ba2a-11eb-87f1-d2050bf2eb04.gif)

**Comment by vonovak** [comment]
hello @scott-massey and thanks for the suggestion!

To be honest, I'd rather prefer that you publish your enhancement in a separate library or in the library that you mentioned, and I see the discussion is already ongoing there 🙂 👍 

Reason I'd prefer for this not to be part of this library, is that I'd much prefer this module to be the "barebones" date/time picker that offers date/time picking and nothing more; other more fancy date/time inputs can be built on top. I just prefer this module to be focused on one thing and do it right.
Additionally, maintenance of this module is already lagging and more features mean more people reporting issues and asking questions and there currently is no one actively handling those....

Hope this makes sense! Hope I answered the question 🙂

**Comment by scott-massey** [comment]
Got it, makes sense!
