### ISSUE TITLE
need to change the format ad DD-MM-YYYY, after changing the date, getting the error saying"TypeError: value.getTime is not a function" 

### ISSUE THREAD

**Issue by AzranAzwer** [react-native-datetimepicker/datetimepicker#465]
Need to change the format ad DD-MM-YYYY, after changing the date, getting the error saying"TypeError: value.getTime is not a function" 

after changing as per [issue ](https://github.com/react-native-datetimepicker/datetimepicker/issues/375) , getting error saying 
"TypeError: value.getTime is not a function" 
but on change function is 
`onChange={(e, date) => onChangeDate(date)}`

```
const onChangeDate = (value) => {
    setUserDetails({
      ...userDetails,
      dateOfBirth: value ? `${value}` : `${new Date()}`,
    });
  };
```

**Comment by vonovak** [comment]
Hello, value need to be an instance of Date object.

Your example is not full, but if you're passing dateOfBirth as the value prop, it will not work because it's a string.

Hope this helps
