### ISSUE TITLE
Localization for iOS / inline only works for months, not days

### ISSUE THREAD

**Issue by savv** [react-native-datetimepicker/datetimepicker#467]
# Bug report

## Summary

Date picker only localizes months, not days, as per below:
![image](https://user-images.githubusercontent.com/747519/119331091-3c1be500-bc87-11eb-8d99-9201d949db57.png)

## Reproducible sample code

```
<DateTimePicker
              display="inline" mode="date"
              themeVariant="light" locale="ru" />
```

Describe what you expected to happen:
Days should also be in Russian (or any other lang).

## Environment info
datetimepicker version: 3.5.0

iOS version: 14.2

**Comment by savv** [comment]
FYI - also tested on iOS 14.5, where this bug still persists

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
