### ISSUE TITLE
'mode' attribute can not be resolved with Typescript

### ISSUE THREAD

**Issue by YuKitAs** [react-native-datetimepicker/datetimepicker#473]
# Question
 According to the basic usage, `mode` attribute is initialized as string:
 ```typescript
 const [mode, setMode] = useState('date');
 ```
 However, when setting it for `DateTimePicker`, it can not be resolved properly:
 ```typescript
 <DateTimePicker
    testID="dateTimePicker"
    value={date}
    mode={mode}
    is24Hour={true}
    display="default"
    onChange={onChange}
/>
```
Error reported by VSCode: `Type 'string' is not assignable to type 'AndroidMode | undefined'`

Runtime error when clicking on the picker: 

`TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNTimePickerAndroid.open')`

Versions:
* react-native: 0.64.1
* datetimepicker: 3.5.2

---
Can you please tell me if I missed anything?

**Comment by ZAHERSKIY** [comment]
Hi, have u found a solution?

**Comment by YuKitAs** [comment]
> Hi, have u found a solution?

No, I used [react-native-date-picker](https://www.npmjs.com/package/react-native-date-picker) instead.

**Comment by vonovak** [comment]
hello, as for `Type 'string' is not assignable to type 'AndroidMode | undefined'`, you need to tell TS to type your state:

`const [mode, setMode] = useState<AndroidNativeProps.mode>('date');`

As for the runtime error, seems like the module is not correctly linked.

thank you
