### ISSUE TITLE
blank datepicker screen in android

### ISSUE THREAD

**Issue by SivaYenugu** [react-native-datetimepicker/datetimepicker#475]
# Question

When I tried to change year, my datepicker screen suddenly went blank in android and its not updating. It was working perfectly fine before and I didn't change node_modules or add/remove any exisiting packages.

I updated my react-native-datetimepicker package from 3.4.7 to 3.5.2, cleared cache and started my react-native project again but the issue is still present.

I am using 
"react": "16.13.1",
"react-native": "0.63.4",
node : v14.15.1,
 
![datepicker_issue](https://user-images.githubusercontent.com/79721623/120863814-ddb90580-c5a8-11eb-9492-b58ad4b2e435.png)
![android_config](https://user-images.githubusercontent.com/79721623/120864684-3937c300-c5aa-11eb-872b-849570b38ceb.png)

**Comment by raajnadar** [comment]
I guess this is due to dark mode
