### ISSUE TITLE
onChange not working on android

### ISSUE THREAD

**Issue by silencer07** [react-native-datetimepicker/datetimepicker#477]
## Summary

when picking a date on date mode, onChange does not get triggered when a date has been tapped. same issue when on time mode and hour/minute/AM/PM changed

## Reproducible sample code

I think the current sample code will work. just add console log on the onChange

## Steps to reproduce

1. open the picker
2. select any date
3. notice that the onchange is not being invoked, hence the date always reverts back to the value in the `value` prop

datetimepicker version: the latest version as of this writing

iOS / Android version: android 10 (Using the latest version of EMUI in mate 20 pro) as of this writing

**Comment by Sofrosine** [comment]
Me too, but it's working on production

**Comment by Sofrosine** [comment]
Me too, but it works on production

**Comment by rthazen** [comment]
Same issue

**Comment by quintenbox** [comment]
Got same issue, using version 4.0.0

**Comment by vonovak** [comment]
hello, the `onChange` callback on android is not called when date changes but when user confirms the selection.

hope this helps
