### ISSUE TITLE
Programmatically open/close date picker?

### ISSUE THREAD

**Issue by bertrand-caron** [react-native-datetimepicker/datetimepicker#483]
Hi,

Is there a way to programmatically open/close the date picker from `react-native-datetimepicker`?

My use case is creating a component based on `TouchableOpacity` that opens the DatePicker when pressed (with a much bigger surface area than the tiny date picker). 

`RNDateTimePicker` does not seem to accept a `ref`, nor to have an API to hide/show.

Thank you very much.

**Comment by bertrand-caron** [comment]
Anyone?

**Comment by LouisRaine** [comment]
{show && <RNDateTimePicker />}

**Comment by krystiansliwa** [comment]
I have same question. I tried using some var like that `{show && <RNDateTimePicker />} ` but it just shows that tiny native text.

**Comment by martincalvert** [comment]
Yea am I missing something or is there no way to have the date picker open on render either?

**Comment by AlexandreMouyen** [comment]
Need to use forWardRef & useImperativeHandle (https://reactjs.org/docs/hooks-reference.html#useimperativehandle).

**Comment by RhyG** [comment]
Hi, was also wanting to find out if this was possible. In my project we were hoping to have an icon in the right hand side of an input, and the user can either type a date or press that icon to open the date picker. We also wanted to use the date picker and not spinner. Essentially the implementation looks like:

```js
import DateTimePicker from '@react-native-community/datetimepicker';

const InputWithDatePicker = () => {
    const [date, setDate] = useState(new Date());
    const [showPicker, setShowPicker] = useState(false);

    return (
        <>
            <TextInput rightIcon={<Icon onPress={() => setShowPicker(true)}/>
            { showPicker ? (
                 <DateTimePicker
                    testID="date-picker"
                    value={new Date(date)}
                    mode="date"
                    is24Hour={true}
                    onChange={(_: any, date?: Date) => setDate(date)}
                    maximumDate={new Date()}
                  />
            ) : null }
        </>
    );
};
```
Doing it like this only renders the small date display that then needs to be pressed to open the picker, but we would like to remove that step.

Open to any suggestions, and thanks a lot for your work and time. 🙂

**Comment by omarqe** [comment]
I needed this too. But my current workaround is to wrap `<DateTimePicker/>` inside an invisible `<View/>`. The touch experience is not quite good, but it works though.

Example:

```js
import React from "react"
import { View, Text } from "react-native"
import DateTimePicker from "@react-native-community/datetimepicker";

export default function CustomDateInput({ value, ...restProps }) {
    return (
        <View style={{ position: "relative" }}>
            <Text>{value}</Text>
            <View style={{ opacity: 0, position: "absolute" }}>
                <DateTimePicker value={value} {...restProps} />
            </View>
        </View>
    );
}

```

**Comment by bertrand-caron** [comment]
Any update on this? the `{show && <RNDateTimePicker />}` only works on Android, on iOS it shows a tiny label version.

**Comment by vonovak** [comment]
hello, on ios, you can render the picker directly in your view hierarchy. If you need to open it "even more" - to show the calendar dialog for example, I'm not aware of any way to do that, although I would not be surprised if it were possible from native code.

On android, there are imperative methods to do this as seen in `src/datetimepicker.android.js`

thank you!

**Comment by PaulMonnery** [comment]
So, just to be sure, on IOS, there is currently no way to trigger the opening of the calendar widget directly via my custom button like in this example?
![example](https://user-images.githubusercontent.com/44644435/144973986-b8e74d94-344f-49f6-b7d4-62a0e0c900ab.gif)

**Comment by charlestbell** [comment]
I figured it out. You have to add display='spinner' to the DateTimePicker component. This will revert it to pre-ios14 style, which doesn't have that extra step of the mini button that you have to click again to open it.

```
return(
<--the main conent of my component goes here-->

{show && (
        <DateTimePicker
          testID="dateTimePicker"
          value={date}
          mode={'time'}
          is24Hour={false}
          onChange={onChange}
          display="spinner"
          minuteInterval={15}
        />
      )})
```

**Comment by kkkasio** [comment]
I have the same problem, I need to click on the little "snippet" to open the native calendar.
I believe that for now I will leave the spinner mode.

**Comment by jordanful** [comment]
FWIW `display="spinner"` did help; but `display="inline"` worked even better for me.

**Comment by DarrenRED** [comment]
Combining `display="inline"`, with [https://www.npmjs.com/package/react-native-popover-view](url) this library (or simply making your own popover / tooltip component, this lib was super simple to use though, if you're on a tight deadline)

**Comment by jeffjenk** [comment]
I found setting the component to `display="inline` and wrapping it inside a `Modal` worked rather well. Here is an example that could use a bit of styling.

```
const [show, setShow] = useState(false);
const [date, setDate] = useState(undefined);

const onChange = (
  _event: DateTimePickerEvent,
  selectedDate: Date | undefined
) => {
  const currentDate = selectedDate?.toUTCString();
  if (currentDate === undefined) return;
  setDate(currentDate);
};

return (
  <View>
    <Pressable
      // style to look like a text input
      onPress={() => setShow(true)}
    >
      <Text>{date ? new Date(date).toDateString() : "Select Date"}</Text>
    </Pressable>

    <Modal
      visible={show}
      animationType="slide"
      onRequestClose={() => setShow(false)}
      transparent={true}
    >
      <View>
        <DateTimePicker
          testID="dateTimePicker"
          value={date ? new Date(date) : new Date()}
          mode={"date"}
          onChange={onChange}
          display="inline"
        />
        <Pressable onPress={() => setShow(false)}>
          <Text>Done</Text>
        </Pressable>
      </View>
    </Modal>
  </View>
);

**Comment by itsaliraxa** [comment]
> I found setting the component to `display="inline"` and wrapping it inside a `Modal` worked rather well. Here is an example that could use a bit of styling.
> 
> ```
> const [show, setShow] = useState(false);
> const [date, setDate] = useState(undefined);
> 
> const onChange = (
>   _event: DateTimePickerEvent,
>   selectedDate: Date | undefined
> ) => {
>   const currentDate = selectedDate?.toUTCString();
>   if (currentDate === undefined) return;
>   setDate(currentDate);
> };
> 
> return (
>   <View>
>     <Pressable
>       // style to look like a text input
>       onPress={() => setShow(true)}
>     >
>       <Text>{date ? new Date(date).toDateString() : "Select Date"}</Text>
>     </Pressable>
> 
>     <Modal
>       visible={show}
>       animationType="slide"
>       onRequestClose={() => setShow(false)}
>       transparent={true}
>     >
>       <View>
>         <DateTimePicker
>           testID="dateTimePicker"
>           value={date ? new Date(date) : new Date()}
>           mode={"date"}
>           onChange={onChange}
>           display="inline"
>         />
>         <Pressable onPress={() => setShow(false)}>
>           <Text>Done</Text>
>         </Pressable>
>       </View>
>     </Modal>
>   </View>
> );
> ```

Yes, it's worked for me
![Simulator Screen Shot - iPhone 14 Pro - 2023-07-21 at 22 31 32](https://github.com/react-native-datetimepicker/datetimepicker/assets/120467402/fb5f7d1e-6253-429c-b782-fea62e307608)

**Comment by nicolascavallin** [comment]
@itsaliraxa can you share your example?

**Comment by itsaliraxa** [comment]
> @itsaliraxa can you share your example?

**### Date Picker component**

import React from 'react';
import { Modal, View, Platform } from 'react-native'

import { DateTime } from 'luxon'
import DateTimePicker from '@react-native-community/datetimepicker';

const DatePicker = ({ date, maxDate, onChange }) => {
    
    const handleDate = (event, date) => {
        const parsedDate = DateTime.fromISO(date.toISOString());
        let data = {
            date: parsedDate.toISODate(),
            dateToShow: parsedDate.toLocaleString()
        }
        onChange(data)
    }


    if (Platform.OS === 'android') {
        return (<DateTimePicker
            mode='date'
            textColor="#a7c610"
            accentColor="#a7c610"
            value={new Date(date)}
            onChange={handleDate}
            maximumDate={maxDate ? maxDate : null}
            style={{ flex: 1, justifyContent: 'flex-start' }}
        />)
    } else {
        return (
            <Modal
                visible={true}
                animationType="slide"
                // onRequestClose={() => setShow(false)}
                transparent={true}
            >
                <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                    <View style={{ height: '40%', width: '90%', backgroundColor: 'white', borderRadius: 8 }}>
                        <DateTimePicker
                            mode='date'
                            textColor="#a7c610"
                            accentColor="#a7c610"
                            value={new Date(date)}
                            onChange={handleDate}
                            maximumDate={maxDate ? maxDate : null}
                            // locale="es-ES"
                            display="inline"
                            style={{ flex: 1, justifyContent: 'flex-start' }}
                        />
                    </View>

                    {/* <Pressable onPress={() => setShow(false)}>
                        <Text>Done</Text>
                    </Pressable> */}
                </View>
            </Modal>
        )
    }
}

export default DatePicker;

**### Display and open calender**

const handleDateChange = (data) => {
        const { date, dateToShow } = data
        setShowPicker(false)
        setDate({
            value: date,
            display: dateToShow
        });
    }

<InputLabel label={t('profile.dob')} />
                    <Text>{date.display}</Text>
                    {showPicker && <DateTimePicker date={ date.value} onChange={handleDateChange} />}
                    <Pressable onPress={() => setShowPicker(true)}>
                        <Text color='primary.50'>Edit</Text>
                    </Pressable>

**Comment by statico** [comment]
@itsaliraxa Brilliant. Thank you so much for this.

We had to use a variation of your solution and only show the `DateTimePicker` when the visibility boolean is true:

```typescript
  const [isPickerOpen, setPickerOpen] = useBoolean(false)

  const handleChange = (event: DateTimePickerEvent, date: Date) => {
    setPickerOpen.off()
    onChange(date)
  }
  
  return <View>...
  ...
          {Platform.OS === "android" ? (
            isPickerOpen && (
              <DateTimePicker
                mode="date"
                accentColor={theme.colors.primary}
                value={new Date(value)}
                onChange={handleChange}
                minimumDate={minDate}
              />
            )
          ) : (
            <PhModal isOpen={isPickerOpen} onClose={setPickerOpen.off}>
              <DateTimePicker
                mode="date"
                accentColor={theme.colors.primary}
                value={new Date(value)}
                onChange={handleChange}
                minimumDate={minDate}
                display="inline"
              />
            </PhModal>
          )}
```

**Comment by arive-de** [comment]
Hi guys ! It's been really helpful reading all of your comments. The display-inline is life saving, and works great with mode="date", but when using it with mode="time" it is not working at all.

Do you guys have any idea how to do it ?

Thank you very much

**Comment by Nasseratic** [comment]
@arive-de Can you try passing height to style?
```
<DateTimePicker
                mode="time"
                ...
				style={{height: 300}}
                display="inline"
              />
              ```

**Comment by arive-de** [comment]
So I found the trick, I'm just displaying "spinner" in time mode !

**Comment by badalsaibo** [comment]
Use the `react-native-modal-datetime-picker` package which is wrapper around this package and comes with the prop `isVisible` 

https://www.npmjs.com/package/react-native-modal-datetime-picker

**Comment by WillSmithTE** [comment]
The `inline` solution nearly works, but seems to remove the days of the week, whereas `compact` still has them. The code looks the same, @itsaliraxa did you do anything in particular to show them?


<img width="375" alt="IMG_A76A7C035C9D-1" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/26863411/9ffe3edd-61ed-4ca9-9331-6196dbe72903">
<img width="436" alt="Screenshot 2023-12-11 at 16 25 12" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/26863411/5b53920b-2e10-499a-9bc3-aeaacff7a582">

**Comment by Martinnord** [comment]
Why can't it just close the date picker after you've selected a date when `mode="date"`? Shouldn't that be default behaviour??

**Comment by basememara** [comment]
These are creative but hideous attempts so I want to add my hideous attempt to mix too 😛. It's too bad nothing comes out of the box for this. I didn't want to forego the latest native behaviour so my approach was to overlay a text (or icon) with `pointEvent="none"` so the tap passes through and opens the calendar popup.

```tsx
<View style={styles.dateContainer}>
  <View
    pointerEvents="none"
    style={[
      styles.dateOverlay,
      { backgroundColor: theme.secondaryGroupedBackground, display: value === null ? 'flex' : 'none' }
    ]}
  >
    <Text>Select</Text>
  </View>
  <DateTimePicker {...props} value={value ?? new Date()} />
</View>

const styles = StyleSheet.create({
  dateContainer: {
    justifyContent: 'center'
  },
  dateOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: '100%',
    height: '100%',
    zIndex: 1
  }
});
```

https://github.com/react-native-datetimepicker/datetimepicker/assets/892152/54a92cd0-8c86-404a-b05e-ca24bec66476

FWIW, this is a challenge down in the SwiftUI native side so there's no hook to do this so just more hacks on that side as well: [link 1](https://stackoverflow.com/questions/75073023/how-to-trigger-swiftui-datepicker-programmatically), [link 2](https://stackoverflow.com/questions/77373659/swiftui-datepicker-issue-ios-17-1). Someone even had a creative idea to use the accessibility APIs to open it but didn't look like it had consistent or reliable behaviour. I didn't look on the Android side yet or how my code behaves there.

**Comment by omarbenzi** [comment]
```
/**
 * TimePickerModal is a React Native component that integrates a DateTimePicker
 * within a React Native Paper Modal component. It provides a clean interface for
 * selecting dates in a modal popup that can be programmatically opened and closed.
 *
 * @component
 * @param {object} props - Component props
 * @param {boolean} props.showStartDatePicker - Controls visibility of the modal
 * @param {Date | undefined} props.value - Current selected date value
 * @param {Function} props.onDateChanges - Callback function triggered when date is changed
 * @param {string} props.title - Title text displayed above the date picker
 * @param {Function} props.onDismiss - Callback function triggered when modal is dismissed
 *
 * @returns {React.ReactElement} A modal containing a date picker component
 *
 * @example
 * <TimePickerModal
 *   showStartDatePicker={showPicker}
 *   value={selectedDate}
 *   onDateChanges={(event, date) => handleDateChange(date)}
 *   title="Select a date"
 *   onDismiss={() => setShowPicker(false)}
 * />
 */

import { View, Text } from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { Modal } from "react-native-paper";

type TimePickerModalProps = {
    showStartDatePicker: boolean;
    value: Date;
    title: string;
    onDateChanges: (event, selectedDate) => void;
    onDismiss?: () => void;
};

const TimePickerModal = (props: TimePickerModalProps) => {
    const { showStartDatePicker, value, onDateChanges, title, onDismiss } =
        props;
    return (
        <Modal
            style={{
                backgroundColor: "transparent",
            }}
            contentContainerStyle={{}}
            dismissable={true}
            dismissableBackButton={true}
            visible={showStartDatePicker}
            onDismiss={onDismiss}
        >
            <View
                style={{
                    backgroundColor: "#FFF",
                    padding: 20,
                    borderRadius: 8,
                }}
            >
                <Text>{title}</Text>
                <DateTimePicker
                    themeVariant="dark"
                    value={value || new Date()}
                    mode="date"
                    display="inline"
                    onChange={onDateChanges}
                    minimumDate={new Date()}
                />
            </View>
        </Modal>
    );
};

export default TimePickerModal;

```
