### ISSUE TITLE
Dark mode is still not working...

### ISSUE THREAD

**Issue by nimabrownlee** [react-native-datetimepicker/datetimepicker#485]
# Bug report

## Summary

The picker is invisible in dark mode.

## Reproducible sample code

I'll skip this step as there has been countless reports for this specific issue. 

## Steps to reproduce

1. Add `textColor="red"` and it doesn't work
2. Add `themeVariant="light"` and it doesn't work
3. Disable dark mode in `info.plist` and it doesn't work
4. Disable dark mode in app.json in Expo and it doesn't work
5. Add custom background color in styles and it doesn't work

Describe what you expected to happen:

I just want the picker to be visible in dark mode. Can someone for the love of God tell me what I can do to fix this? It's so tiring that something so simple renders this library completely useless.

## Environment info

Expo: 41.0.1

`npx react-native info` output:

```bash
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 368.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - ~/.nvm/versions/node/v15.5.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v15.5.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.5.2

iOS: 14.6

Other important info: I use [react-navigation](https://reactnavigation.org/) and maybe the picker bugs out in different views?

**Comment by MikeSagnelli** [comment]
@vonovak I am having the same issue, there is no way in which I can force the component to show black text in the date picker when the user has the dark mode setting on his iPhone.

**Comment by MikeSagnelli** [comment]
Maybe you can point me in the right direction to send an update to your code and fix this issue?

**Comment by StartupSam** [comment]
Experiencing the same. For now, I'm probably going to listen to dark/light mode on iOS and change the background color of my modal accordingly.

Not ideal though

**Comment by assimovt** [comment]
On Android, the dark mode is not detected at all. I am using Expo SDK 42 and the latest version of the package.

**Comment by vonovak** [comment]
hello folks, please check out the example app. It looks pretty good to me :)

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-13 at 17 58 38](https://user-images.githubusercontent.com/1566403/141652312-4098f9fd-b4d6-47b7-a69b-735326288a57.png)

![Simulator Screen Shot - iPhone 11 - 2021-11-13 at 17 59 04](https://user-images.githubusercontent.com/1566403/141652326-641093f9-90f0-4e88-9a9b-77c892aaeb4b.png)


thank you! :)
