### ISSUE TITLE
[iOS][14] Change selected row color on spinner

### ISSUE THREAD

**Issue by Andrea-Arguello** [react-native-datetimepicker/datetimepicker#486]
# Question

As of right now, my picker on iOS in spinner mode defaults to a grey color for the selected row:
![image](https://user-images.githubusercontent.com/31134106/124335694-61d6bc80-db58-11eb-9a2a-1c71876c57fb.png)

Any help on how to change this to any other color is appreciated.

**Comment by Alexanderwags** [comment]
hello @Andrea-Arguello , I asked the same question if you could get solution?

**Comment by Andrea-Arguello** [comment]
> hello @Andrea-Arguello , I asked the same question if you could get solution?

I haven't had any luck, I've checked the Apple Developer Forums but they offer no insight on where the code should be placed, such as [this one](https://developer.apple.com/forums/thread/659184). Any insight helps.
