### ISSUE TITLE
Spinner handle exceeding date range

### ISSUE THREAD

**Issue by LouisRaine** [react-native-datetimepicker/datetimepicker#487]
# Question

Any way of accessing an error when spinner date range is exceeded.

Currently when you add a min or max date with the spinner mode if a user selects a date outside of this range the spinner slides back to a valid range - while this is nice, it would be cool to be able to know when this occurs so that I can show a warning for what the valid date range is.

**Comment by vonovak** [comment]
hello, personally I'm not aware of such option but you can try asking on stackoverflow too.

thanks!
