### ISSUE TITLE
you can change the native color that comes by default of android

### ISSUE THREAD

**Issue by Alexanderwags** [react-native-datetimepicker/datetimepicker#488]
I want to change the background color, I don't want it green

**Comment by traviswsims** [comment]
Wish the OP phrased his comment better, but I am also interested in styling the Android time picker.  Any suggestions?  Thank you!

**Comment by Alexanderwags** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/26121628/125007923-622af800-e02f-11eb-9fd7-412b05d363e6.png)
hello @traviswsims ,If you argue wrong, what I want is to change the native color of android by default I get green, I would like it to be orange.

**Comment by Andrea-Arguello** [comment]
#20 and #340 seem to be similar issues, have you tried any of the solutions mentioned in the comments?

**Comment by sphrases** [comment]
🙋I really need this feature too! The solutions from #20 and #340 seem to only work statically with bare workflow (Not with standard Expo) The solutions further suggest that the problem lies with android itself.

**Comment by vonovak** [comment]
duplicate of #20
