### ISSUE TITLE
minuteInterval not working as expected on iOS

### ISSUE THREAD

**Issue by yamila-fraiman** [react-native-datetimepicker/datetimepicker#489]
When setting minuteInterval and open time selector on iOS, it displays only available minutes but when I select time without scrolling hours or minutes, it use current time and doesn't take into account interval.

version: 3.5.2

<img src="https://user-images.githubusercontent.com/71793326/125179182-528fe880-e1c2-11eb-974e-c5e4e3c4422a.png" width=25% height=25%>

<img src="https://user-images.githubusercontent.com/71793326/125179184-5459ac00-e1c2-11eb-8a11-138b9cc48b93.png" width=25% height=25%>

**Comment by ppv94** [comment]
**I am also facing the same issue in IOS when the minute interval is used**
if I click confirm without selecting the Time in picker I am not getting the time shown in the picker as the above issue
if I change the time in the picker I am getting the selected time.

**Comment by vonovak** [comment]
hello and thanks for reporting.

in your examples, when you press "confirm" without scrolling the picker, the picker does not even get a chance to apply the "interval clamping" - it is not called or used at all. You will have to do this manually.

Thank you! :)
