### ISSUE TITLE
Date-picker for web

### ISSUE THREAD

**Issue by DilipCoder** [react-native-datetimepicker/datetimepicker#491]
# Feature request
date picker for the web.

## Why it is needed
in our organization, we are working on cross-platform solutions which include the web too.
i searched for the solution but there is no integrated solution. the changes and their maintenance will be easy. but it will add a great value for the developers using this component as cross-platform.

## Possible implementation
there are multiple solutions that exist.
1. writing component file as platform-specific like `datepicker.web.tsx` and `datepicker.tsx`
2. switching the implementation as a platform specific like
```
export default function DateTimePicker({ value, onChange }: Props) {
  
  return createElement('input', {
    type: 'date',
    value: value,
    onInput: onChange,
  })
}
<!--
```
It really helps if you could describe from a technical POV how this new feature would work, which code it rely on, etc.
-->

### Code sample
now we can import the component which will support the web as well.

### reference
https://stackoverflow.com/questions/53746118/react-native-web-datepicker-component

**Comment by cesargdm** [comment]
For web we're using the Firefox, Safari and Chrome's UI https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date by rendering a text input and adding the input props that enable the text input to be a date input

<img width="174" alt="Screen Shot 2021-09-01 at 11 54 08 a m" src="https://user-images.githubusercontent.com/10179494/131712138-fc07ee88-8ebd-40a8-a66d-9fb0656bae36.png">


```
  useEffect(() => {
    if (inputRef?.current) {
      inputRef?.current?.setNativeProps({
        type: 'date',
        min: format(minimumDate, DATE_FORMAT.en),
        max: format(maximumDate, DATE_FORMAT.en),
        pattern: 'd{4}-d{2}-d{2}',
      })
    }
  }, [inputRef?.current])

  if (Platform.OS === 'web') {
    return <TextInput ref={inputRef} type="date" {...moreProps} />
  }
```

**Comment by hasn-ab** [comment]
@cesargdm can you please share the gist? Where are you adding this code?

**Comment by cgallivanpam** [comment]
> @cesargdm can you please share the gist? Where are you adding this code?

Yes @cesargdm, this would be very helpful!

**Comment by cesargdm** [comment]
Sure @hasn-ab @cgallivanpam , let me know if this helps https://gist.github.com/cesargdm/ceb486d73e43b8ecd5ca5fc45c2bd834

**Comment by vonovak** [comment]
hello and thanks for reporting, we do not plan to add web support, as there are tons of other pickers you can use on the web.

thank you :)
