### ISSUE TITLE
Do not support Buddhist calendar on Android devices

### ISSUE THREAD

**Issue by MINISOCKS** [react-native-datetimepicker/datetimepicker#492]
Hi, it seems that this library doesn't support Buddhist calendar on Android phones. Any solution for that?

**Comment by vonovak** [comment]
hello,
I'm closing this as per readme:

> Please note that this library currently exposes functionality from UIDatePicker on iOS and DatePickerDialog + TimePickerDialog on Android, and CalendarDatePicker +TimePicker on Windows.
These native classes offer only limited configuration, while there are dozens of possible options you as a developer may need. It follows that if your requirement is not supported by the backing native views, this library will not be able to implement your requirement. When you open an issue with a feature request, please document if (or how) the feature can be implemented using the aforementioned native views. If those views do not support what you need, such feature requests will be closed as not actionable.


thank you :)
