### ISSUE TITLE
issue with setting time

### ISSUE THREAD

**Issue by elmcapp** [react-native-datetimepicker/datetimepicker#493]
I am having an issue with loading in the start date from a prop. I get the following error

A date or time should be specified as value
The prop value is 1626408000000 after formatted with moment

`<DateTimePicker
            ref={(c) => (this._txtRemindTime = c)}
            testID="dateTimePicker"
            //value={this.state.dateSelect}'
            value={moment(this.props.date).valueOf()} // coming from prop and moment converts it as 1626408000000
            mode={"time"}
            is24Hour={false}
            display="spinner"
            onChange={this.onTimeChange} 
          />`

**Comment by clowenhg** [comment]
I'd expect time simply wants to be within 00:00 to 23:39, no date component, nor seconds from epoch.
So, `hour*60+minutes`
