### ISSUE TITLE
Prevent Choosing past hours from current hour for android?

### ISSUE THREAD

**Issue by abdo17rabah** [react-native-datetimepicker/datetimepicker#495]
I want to prevent choosing past hours from current hour in DateTimePickerModal. in IOS it works fine but on Android i can choose the past hours. How can i prevent that in minimumDate?
Here is my code : 
`<DateTimePickerModal
       style={{
          width: 'auto',
           marginBottom: 16,
            backgroundColor: '#F0F3F4',
         }}
         isVisible={showDatePicker}
         mode="datetime"
         minimumDate={getTodayStringSuperior()}
/>`

**Comment by vonovak** [comment]
Hello and thanks for asking,
`minimumDate` on Android only works for the date mode, as documented: https://github.com/react-native-datetimepicker/datetimepicker#minimumdate-optional

you will need to check the time that the user has picked, or create your own time picking mechanism.

Thank you 🙂
