### ISSUE TITLE
can not set date formate; I just want to choose the year and month;  'yyyy-MM'

### ISSUE THREAD

**Issue by liuqing520it** [react-native-datetimepicker/datetimepicker#496]
# Feature request

can set datePicker dateFormate

### Code sample

<DateTimePicker dateFormat={'yyyy-MM'|'yyyy-MM-dd'|'yyyy-MM-dd HH:MM'}/>

**Comment by vonovak** [comment]
hello, this package does not offer selecting only year and months, thank you.
