### ISSUE TITLE
Time picker select issue in apple devices 

### ISSUE THREAD

**Issue by manojkj12** [react-native-datetimepicker/datetimepicker#497]
# Bug report

## Summary
I am using your plugin react-native-community/datetimepicker, In apple iPhone or iPAD we are displaying the timepicker icon in 
a popup and whenever I try to set time once i scroll the hours value it is getting closed automatically before i select the value for minutes and in addition to that the popup is also getting closed. This is not the case for android and the same codebase works well in android devices. Can we avoid or overcome this issue in apple devices so that i can choose the hours and minutes in one go before it gets closed automatically and is there any way for us to make the popup stay still and not get closed until i select and fill both hours and minutes from timepicker. So that i can avoid multiple clicks.

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
# paste it here
```

datetimepicker version: 

iOS / Android version: x.x

**Comment by dyegooviedo** [comment]
Hey @manojkj12 ,
Probably you are using the same logic to display the time picker in Android and so iOS.
When you call your "setShowTimePicker" from state, you can use the Platform component to fix it, would be something like this:

  ` setShowDateTimePicker(Platform.OS === 'ios'); `

By this way you don't call this update in each changes on time picker using iOS.
Remind to import Platform from 'react-native' module.
