### ISSUE TITLE
Module does not anymore build into Windows

### ISSUE THREAD

**Issue by tero-paananen** [react-native-datetimepicker/datetimepicker#499]
# Bug report

Following commit causes that module does not build anymore into Windows.

https://github.com/react-native-datetimepicker/datetimepicker/commit/603ac79a474906774fb37e35e503e10ba84a9133#diff-d901f0e0858bdc387efcba25276aad189cc3ee6762fc74a069a6fa4393d271e7

## Environment info
System:
    OS: Windows 10 10.0.19043
  npmPackages:
    react-native: 0.62.2 => 0.62.2
    react-native-windows: 0.62.22 => 0.62.22

**Comment by tero-paananen** [comment]
patched

**Comment by vonovak** [comment]
closed by #583 

thank you
