### ISSUE TITLE
Error when pod install

### ISSUE THREAD

**Issue by vinhtran6921** [react-native-datetimepicker/datetimepicker#500]
# Bug report

## Summary

I got this error when pod install
![image](https://user-images.githubusercontent.com/53859772/128473239-c13a9bbd-70b9-4be1-8f98-56ed997dbf04.png)

Here is my podfile
![image](https://user-images.githubusercontent.com/53859772/128472946-cae93214-fdb3-4784-8231-11b9b59033f8.png)

## Steps to reproduce

1. npm install @react-native-community/datetimepicker
2. react-native link @react-native-community/datetimepicker
3. pod install

## Environment info

react native: 0.59.1
"@react-native-community/datetimepicker": "^3.5.2",

**Comment by ShuKTan** [comment]
Same here...

**Comment by vidurajith-darshana** [comment]
node modules-> @react-native-community -> datetimepicker-> RNDateTimePicker.podspec

find the line with this code
`s.platform = '10.0'` or any version

and change it to your current deployment target version like this,

`s.platform = '9.0'`

**Comment by vonovak** [comment]
hello and thanks for reporting; react native now requires iOS 11, so I suggest you upgrade to latest RN to use the module.

thank you :)
