### ISSUE TITLE
ok and cancel buttons are not on ios before and after date selection.

### ISSUE THREAD

**Issue by umairalirehan** [react-native-datetimepicker/datetimepicker#501]
# Bug report

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
# paste it here
```

datetimepicker version: x.x.x

iOS / Android version: x.x

**Comment by Basir-PD** [comment]
I had to create those buttons myself in iOS:

`<View style={styles.btnContainer}>
  <TouchableOpacity
      style={styles.btn}
      onPress={() => {
        setShowDOB(!showDOB);
        dob.current = "Birth Date";
      }}
  >
      <Text>Cancel</Text>
  </TouchableOpacity>
  
  <TouchableOpacity style={styles.btn} onPress={() => setShowDOB(!showDOB)}>
      <Text>OK</Text>
  </TouchableOpacity>
</View>`
