### ISSUE TITLE
RN | datetimepicker - P ossible Unhandled Promise Rejection (id:9): TypeError: null is not an object

### ISSUE THREAD

**Issue by Aaketk17** [react-native-datetimepicker/datetimepicker#502]
![image](https://user-images.githubusercontent.com/61150758/130088936-39cbb832-3956-44ce-a4e3-d83a65aecfc4.png)

I used the same code from the documentation and it gives me this error. how to resolve this

**Comment by jettandres** [comment]
I was able to get mine working by cleaning the gradle cache
```
cd android && ./gradlew cleanBuildCache && cd ..
```

If that didn't work, you can follow the more in-depth instructions [here](https://github.com/react-native-datetimepicker/datetimepicker/issues/38#issuecomment-578915295)

**Comment by ikeller96** [comment]
I'm having this same issue. I am using Expo so we have a custom client setup. It is working fine on iOS after creating a new custom client and downloading it to a device, but after doing the same thing with Android, I get the above error as well. I don't want to eject from Expo so I don't have direct access to the Android folder. Is there another solution out there to fix this?
