### ISSUE TITLE
How can i open directly calendar popup in IOS? 

### ISSUE THREAD

**Issue by Alpacora** [react-native-datetimepicker/datetimepicker#504]
# Question

Hello guys! please help-me. I want to know if its possible open Calendar PopUp in IOS with custom button, if yes, please tell-me. Thanks in advanced.

**Comment by cesargdm** [comment]
Apparently this is a duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/483

**Comment by vonovak** [comment]
hello, thanks for asking. I'm not aware of such way.
