### ISSUE TITLE
dependency incompatible in expo sdk 41

### ISSUE THREAD

**Issue by rosnk** [react-native-datetimepicker/datetimepicker#507]
upgraded to sdk 41, i am getting this error

1) trying to do "expo install @react-native-community/datetimepicker", i am getting installation error: 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.3" from @react-native-community/datetimepicker@3.2.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"3.2.0" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native-windows@0.65.1
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.2.0
npm ERR!   node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"3.2.0" from the root project
```

2) installing npm route: 
`npm install @react-native-community/datetimepicker --save`

  then trying to run "npm run start", i am getting following error: 
```
  Some dependencies are incompatible with the installed expo package version:
 - @react-native-community/datetimepicker - expected version: 3.2.0 - actual version installed: 3.5.2
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
```

tried checking package-lock.json to see if there are any peer dependency that depend on datetimepicker version 3.2.0 but found non...... why is expo even installing versino 3.2.0 also why installing datetimepicker 3.5.2 from npm showing my project has dependency for 3.2.0

**Comment by Vandetho** [comment]
Hi,
This error can be solved by using expo install instead like

`expo install @react-native-community/datetimepicker`

but if you want to use npm, you need to add `--legacy-peer-deps`

`npm install @react-native-community/datetimepicker --legacy-peer-deps --save`

**Comment by vonovak** [comment]
hello,
expo 44 (beta is available) will include v4 of this package, the error should be gone by then. Thank you
