### ISSUE TITLE
Styling IOS Picker Result Text

### ISSUE THREAD

**Issue by aec2f** [react-native-datetimepicker/datetimepicker#508]
# Question

I would like to style the display of the date that was picked on iOS.  Including the text color and background color.  Specifically to white background black text.  Is this possible?  I tried the style attribute, which lets me set padding.  And I can set a background color but there appears to be a transparent overlay which prevents me from setting it to white.

![image](https://user-images.githubusercontent.com/61921037/132421002-597a8707-e043-4231-8293-8e4685fb9375.png)

`<DateTimePicker textColor='green' style={styles.iosDatePickerStyle} mode={props.dateOnly ? 'date' : 'datetime'} onChange={date => selectChangeHandler(date, 'datePicker')} onCancel={() => setDatePickerVisibility(false)} value={new Date(inputState.value)} minimumDate={props.minDate} />
`
`
    iosDatePickerStyle: {
        flex: 1,
        backgroundColor: '#ffffff',
        color: 'red',
        marginLeft: 10
    },
`
Thanks,
Andrew

**Comment by supryan** [comment]
I second this behavior. I am having an issue on iOS 15 where the picker can't be stretched to fill the container. So you can only tap in the area where the date is. In this case I would like to style it in a way where it can fill the whole space, therefore increasing the tap area.

![IMG_8DC95B5B80D2-1](https://user-images.githubusercontent.com/6980704/134429548-0182cc25-eb0e-47d5-b421-2bb1fbe5d4b6.jpeg)

**Comment by Lapaenergy** [comment]
I have the same issue =(

https://github.com/react-native-datetimepicker/datetimepicker/issues/514

**Comment by vonovak** [comment]
hello, as for the styling question, I have given my answer here https://github.com/react-native-datetimepicker/datetimepicker/issues/537 so I'll close this as duplicate and the discussion can continue there 

thank you
