### ISSUE TITLE
[Android] timeZoneOffsetInMinutes issue with minimumDate/maximumDate

### ISSUE THREAD

**Issue by PaitoAnderson** [react-native-datetimepicker/datetimepicker#518]
# Bug report

## Summary

When setting a minimum and maximum UTC date and setting `timeZoneOffsetInMinutes={0}` the Android picker is off by one day, I'm guessing it's using the device timezone somewhere.

## Reproducible sample code

Using the example project, change these lines:
```js
const [minDate, setMaxDate] = useState(new Date(Date.UTC(2021, 9, 2)));
const [maxDate, setMinDate] = useState(new Date(Date.UTC(2021, 9, 4)));
```

And also specify this for the `<DateTimePicker />`:
```jsx
minimumDate={minDate}
maximumDate={maxDate}
```

(iOS Left: No issues, Android Right: Issue)
<img width="837" alt="Screen Shot 2021-10-06 at 9 23 14 AM" src="https://user-images.githubusercontent.com/4108718/136212428-4d81be06-2c4c-4f93-add7-f671f8cd5e6b.png">

## Steps to reproduce

1. Click Show Picker

Describe what you expected to happen:

1. Should only let the user pick 2,3,4 instead, it let me pick 1,2,3 on Android.

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.25 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/Development/datetimepicker/node_modules/.bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 2 Arctic Fox 2020.3.1 Patch 2
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.2 => 0.62.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.5.2

iOS / Android version: iOS 15.0 / Android 10

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 5.0.2 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
