### ISSUE TITLE
iOS 14.x - Invisible text

### ISSUE THREAD

**Issue by whispli** [react-native-datetimepicker/datetimepicker#526]
# Bug report

When updating expo from v40 to v41, I also updated this package. Since then, the text is invisible (white color).

## Summary

![datepicker1](https://user-images.githubusercontent.com/45744621/141481000-268a9b7e-e7ff-4e9c-b33b-909b66f8d69a.jpeg)

Changing the theme, or using `textColor` does nothing. Using a different `mode` or `display` does not change anything.

Using this snipped found in another issue
```
style={{
  shadowColor: '#000000',
  shadowRadius: 0,
  shadowOpacity: 1,
  shadowOffset: { height: 0, width: 0 },
}}
 ```
gives this result, which isn't ideal.

![datepicker](https://user-images.githubusercontent.com/45744621/141480988-72915f5b-75ec-436c-95af-8471e848ed97.jpeg)

## Environment info

Expo version 41

datetimepicker version: 3.5.2

iOS / Android version: 14.6

**Comment by vonovak** [comment]
hello, please see the example project that works with dark / light mode
