### ISSUE TITLE
Datetimepicker cannot be compiled on windows.

### ISSUE THREAD

**Issue by cmachaca** [react-native-datetimepicker/datetimepicker#529]
# Bug report

Hello.
The native module can no longer be used on windows. The project breaks the solution. The readme steps were followed and still the app could not be launched.

**Comment by creambyemute** [comment]
@cmachaca Can you try again with Version 4.0.1 which fixed the ARM64 Build Configuration?

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.0.2 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
