### ISSUE TITLE
Date picker shows date oldren than minimum date

### ISSUE THREAD

**Issue by abidhkm** [react-native-datetimepicker/datetimepicker#536]
## Summary

I have provided maximum date as 1 Jan 2022 and minimum date as 25 Nov 2021 and value as 1 Jan 2022. When I try to change the date from the picker I am able to pick the date 1st Jan of 2021 which is not satisfying the minimum date and on clicking on OK, the on change callback returns 1 Jan 2021 . 
<img width="315" alt="Screen Shot 2021-11-25 at 11 01 07 AM" src="https://user-images.githubusercontent.com/22368311/143397147-6bc5d88c-6d39-45e0-9f57-cc62d52e6f95.png">

## Reproducible sample code

const [date, setDate] = useState(new Date("1/1/2022"))

 <DateTimePicker
        maximumDate={new Date("1/1/2022")}
        minimumDate={new Date("11/25/2021")}
        timeZoneOffsetInMinutes={0}
        value={date}
        display={Platform.OS === 'ios' ? 'spinner' : 'default'}
        onChange={(e) => setDate(e)}
  />

## Steps to reproduce

1. Default date is 1 Jan 2022
2. Click on year 2022 from the picker and change it to 2021
3. Now it will show 1 Jan 2021 as the date in top portion of the date picker but it shows correct date in the bottom part

Describe what you expected to happen:

1. It should show correct date in the top and bottom part of the picker.

## Environment info

datetimepicker version: 4.0.0

Android version: 10

**Comment by vonovak** [comment]
this should be resolved with https://github.com/react-native-datetimepicker/datetimepicker/pull/519
