### ISSUE TITLE
Is there a way to change the blue color in the ios date picker?

### ISSUE THREAD

**Issue by fffaria** [react-native-datetimepicker/datetimepicker#537]
In order to maintain the color palette of the screen, I would need to change the color blue that the DateTimePicker uses for the "date" mode, as shown in the picture below.
 
![Screen Shot 2021-12-08 at 16 20 46](https://user-images.githubusercontent.com/9650859/145271151-7ccae8a1-b8d3-4bc2-8a15-276a3b959983.png)

But I can't find a way to change that blue color to red. I have tried using style and textColor, but neither of them works. 
Can someone help me with this issue? Thanks!

**Comment by vonovak** [comment]
Hello, the picker probably uses some of the colors provided by iOS, as seen here: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors

if you change those (I never did it), you'll influence the appearance. This package does not provide a way to do so.

Thank you :)
