### ISSUE TITLE
Inability to display 24hr time in Time Picker on iOS due to locale prop removed in v. 5.0.0

### ISSUE THREAD

**Issue by vlad-ps** [react-native-datetimepicker/datetimepicker#542]
# Feature request

Please add the ability to display 24hr time on iOS. Previously it was possible to do so by doing 

```
locale={isMilitary ? 'en-GB' : undefined}
``` 

But after the `locale` prop was removed in https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (@vonovak), it is no longer possible to display military time in Time Picker on iOS, as `is24Hour` prop only works on Android. 

## Why it is needed

I have clients that use military time in their schedule and I need to be able to display military time in Time Picker for them.

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 5.1.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
