### ISSUE TITLE
Build Android Variant on Windows PC fails on mergeDexRelease

### ISSUE THREAD

**Issue by ModdyLP** [react-native-datetimepicker/datetimepicker#548]
# Bug report

## Summary
Hey I have sometimes on Building the React Native App as Android on Windows a Build Error. I dont know where i can locate it and fix it. The following error crashes the Build 
```* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform classes.jar (project :react-native-community_datetimepicker) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.BuildTypeAttr=release, com.android.build.api.attributes.VariantAttr=release, dexing-enable-desugaring=true, dexing-incremental-transform=true, dexing-is-debuggable=false, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > java.nio.file.NoSuchFileException: E:\Projekte\prepper-rn\node_modules\@react-native-community\datetimepicker\android\build\.transforms\8a14085d6ea01dcb67dea535e717e8b6\results.bin

```
The file which might be missing here exists and is accessable. Also a clean and regenerate of this file does not fix the error.

## Reproducible sample code
Dont have, to complex implementation and no time to build a seperate app for this.

## Steps to reproduce

1. Include as described
2. Build on Windows 11 with target platform Android
3. Voila

Describe what you expected to happen:

1. I dont want to see a error like this.

## Environment info

`npx react-native info` output:

```bash
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.80 GB / 7.92 GB
  Binaries:
    Node: 14.17.6 - E:\Programme\node-v14.15.0-win-x64\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - E:\Programme\node-v14.15.0-win-x64\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 25, 28, 29, 30
      Build Tools: 25.0.2, 28.0.3, 30.0.2, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_202 - C:\Program Files\Java\jdk1.8.0_202\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.66.4 => 0.66.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

datetimepicker version: 5.1.9

iOS / Android version: 11

**Comment by Aexonic-Abhishek** [comment]
I'm also facing the same issue on MacBook.

Execution failed for task ':app:mergeDexRelease'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform classes.jar (project :react-native-community_datetimepicker) to match attributes {artifactType=android-dex, com.android.build.api.attributes.BuildTypeAttr=release, com.android.build.api.attributes.VariantAttr=release, dexing-enable-desugaring=true, dexing-incremental-transform=false, dexing-is-debuggable=false, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform:

Any update?

**Comment by Aexonic-Abhishek** [comment]
@ModdyLP did you resolve the issue? Actually, I need to release the app on high priority but not able to create a release APK.

**Comment by Aexonic-Abhishek** [comment]
I solved the issue by removing the jcenter() dependencies and use mavenCentral(). In the end I had to upgrade my react native from 0.64.2 to 0.66.7.
