### ISSUE TITLE
how can i change the cancel and confirm text on android

### ISSUE THREAD

**Issue by shachardevops** [react-native-datetimepicker/datetimepicker#55]
how can i change the cancel and confirm text on android

**Comment by vonovak** [comment]
this should be possible: https://stackoverflow.com/a/16583969/2070942 ; a PR for this would be merged

**Comment by ducpt2** [comment]
+1 need this.

**Comment by HannahCarney** [comment]
same need

**Comment by vonovak** [comment]
hello, this is now possible: https://github.com/react-native-datetimepicker/datetimepicker#positiveButtonLabel-optional-android-only
