### ISSUE TITLE
The minute selector automatically updates the hour selector (only Android)

### ISSUE THREAD

**Issue by Juliocbr** [react-native-datetimepicker/datetimepicker#554]
For Android in time mode when if I have selected an hour like 8 and I move the minute selector until it reaches 0, the hour selector is updated at 9 and if I keep moving the time continues to update, how could I make this behavior not happen no matter if the minute selector reaches 0 in order to always keep the selected hour?.

**Comment by vonovak** [comment]
hello and thanks for asking

To the best of my knowledge, this behavior is outside of our control.

Thank you :)
