### ISSUE TITLE
Expo managed workflow, android text buttons not visible

### ISSUE THREAD

**Issue by couoheduardo** [react-native-datetimepicker/datetimepicker#557]
# Bug report

When the modal opens, in display={'spinner'} the text cancel and accept is not visible!

currently im using expo 43, this happens in android.

**Comment by kelvinndmo** [comment]
Use EAS Build and expo dev client for development

**Comment by pwfcurry** [comment]
Related: https://github.com/react-native-datetimepicker/datetimepicker/issues/543#issuecomment-1006427288

**Comment by webdevmario** [comment]
I left a comment in issue #543 about my scenario but this definitely started to happen once we upgraded to Expo SDK 45.

**Comment by vonovak** [comment]
closing as duplicate of #543
