### ISSUE TITLE
How do I select the default date on opening the iOS datepicker(Spinner) ?

### ISSUE THREAD

**Issue by ronlobo01** [react-native-datetimepicker/datetimepicker#559]
I am not able to click or select the default date shown on the spinner, It only accepts value if i spin it. Hence I am not able to move towards the time picker as well.

I there are resolve for this ?

**Comment by vonovak** [comment]
hello, thanks for asking
the spinner date picker on iOS has no way select the date other than by spinning. So if you want the user to be able to select the initial date, give them the ability to hide / close the spinner and just take the `value` that you passed as prop to the picker.
