### ISSUE TITLE
Is this library accessible to people with disabilities

### ISSUE THREAD

**Issue by YOEL311** [react-native-datetimepicker/datetimepicker#563]
Is this library accessible to people with disabilities
Is it possible to add to it fields intended for a screen reader?

**Comment by vonovak** [comment]
hello, thanks for asking.

I do not know how friendly this library is for people with special needs. The date pickers themselves are provided by the operating system and I believe they should be optimized for this.
The code that is added in this library is just a thin wrapper on top, and it's possible some improvements can be done there. Feel free to open a PR with any improvement necessary! :)

thanks
