### ISSUE TITLE
appear button in ios

### ISSUE THREAD

**Issue by M-Monn** [react-native-datetimepicker/datetimepicker#565]
All is working fine in Android but in ios have an extra button showing current date and I need to press on that instead of pressing Show Picker.  
In my code I am using TouchableOpacity instead of Button. 
Any advise?

Below are my code.
`export const AppDateTimePicker = () => {
  const [date, setDate] = useState(new Date());
  const [mode, setMode] = useState('date');
  const [show, setShow] = useState(false);
  const [chosenDate, setChosenDate] = useState('dd/mm/yyyy');

  const onChange = (event, selectedDate) => {
    const currentDate = selectedDate || date;
    setShow(Platform.OS === 'ios');
    setDate(currentDate);

    let tempDate = new Date(currentDate);
    let showDate = [tempDate.getDate(), (tempDate.getMonth() + 1), tempDate.getFullYear()].join('/');
    setChosenDate(showDate);
  };

  const showMode = (currentMode) => {
    setShow(true);
    setMode(currentMode);
  };

  const showDatepicker = () => {
    showMode('date');
  };

  return (
    <View style={styles.container}>
      <View style={styles.dateContent}>
        <TouchableOpacity onPress={(showDatepicker)} >
          <Text style={styles.textStyle}>{chosenDate}</Text>
          <MaterialCommunityIcons name="calendar" size={24} style={styles.icon}/>
        </TouchableOpacity>
        {/* <Button onPress={showDatepicker} title="Show date picker!" /> */}
      </View>

      {show && (
        <DateTimePicker
          testID="dateTimePicker"
          value={date}
          mode={mode}
          display="default"
          onChange={onChange}
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderBottomWidth: 1,
    borderBottomColor: colors.grey,
    width: '100%',
    paddingTop: 8,
    paddingBottom: 8,
    marginBottom: 30,
    marginTop: -10
  },
  icon: {
    position: 'absolute',
    right: 0,
    // top: 12
  },
  dateContent: {
    width: '100%',
    padding: 8,
    color: colors.primary
  },
  textStyle: {
    color: colors.primary
  }
});
`

**Comment by faisalur-rehman** [comment]
Same Issue

**Comment by luanphungba** [comment]
same here

**Comment by dsolanor** [comment]
Same here!

**Comment by M-Monn** [comment]
Solved. Need to wrapped inside Modal for ios. You can checked below code. I found this link below
https://www.youtube.com/watch?v=lpIEpggB6o4
Thanks to A3 Programming.

`import React, {useState} from 'react';
import {View, Platform, Text, StyleSheet, Modal, TouchableOpacity} from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { MaterialCommunityIcons } from '@expo/vector-icons';

function AppDateTimePicker (props) {
  const [date, setDate] = useState(new Date());
  const [mode, setMode] = useState('date');
  const [show, setShow] = useState(false);
  const [chosenDate, setChosenDate] = useState('dd/mm/yyyy');

  const onChange = (event, selectedDate) => {
    const currentDate = selectedDate || date;
    setShow(Platform.OS === 'ios');
    setDate(currentDate);
    let tempDate = new Date(currentDate);
    let showDate = [tempDate.getDate(), (tempDate.getMonth() + 1), tempDate.getFullYear()].join('/');
    setChosenDate(showDate);
  };

  const showMode = (currentMode) => {
    setShow(true);
    setMode(currentMode);
  };

  const showDatepicker = () => {
    showMode('date');
  };

  const hideDatepicker = () => {
    setShow(false);
  };

  const onCancelPress = () => {
    setDate(date);
    setShow(false);
  }

  const onDonePress = () => {
    props.onDateChange(date);
    setShow(false);
  }

  const renderDatePicker = () => {
    return(
      <DateTimePicker
        testID="dateTimePicker"
        value={new Date(date)}
        mode={mode}
        display={Platform.OS === 'ios' ? 'spinner' : 'default'}
        onChange={onChange}/>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.dateContent}>
        <TouchableOpacity onPress={showDatepicker} >
          <Text style={styles.textStyle}>{chosenDate}</Text>
          <MaterialCommunityIcons name="calendar" size={24} style={styles.icon}/>
        </TouchableOpacity>
      </View>
      {Platform.OS != 'ios' && show && renderDatePicker()}
      {Platform.OS === 'ios' && show && (
        <Modal
          transparent={true}
          animationType='slide'
          visible={show}
          supporDirections={['portrait']}
          onRequestClose={hideDatepicker}>
          <View style={styles.modalContentView}>
            <TouchableOpacity
              style={{ flex: 1, backgroundColor:  '#fff', }}
              onPress={onCancelPress}>
              <Text style={styles.modalBtnText}>Cancel</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={{backgroundColor:  '#fff'}}
              onPress={onDonePress}>
              <Text style={styles.modalBtnText}>Done</Text>
            </TouchableOpacity>
          </View>
          <View style={{backgroundColor: '#fff'}}>
            {renderDatePicker()}
          </View>
        </Modal>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    borderBottomWidth: 1,
    borderBottomColor: '#c0c0c0',
    width: '100%',
    paddingTop: 8,
    paddingBottom: 0,
    marginTop: -10
  },
  icon: {
    position: 'absolute',
    right: 0,
    bottom: 0
  },
  dateContent: {
    width: '100%',
    padding: 8,
    color:  '#c0c0c0'
  },
  textStyle: {
    color: '#c0c0c0',
  },
  modalContentView:{
    flex: 1, 
      alignItems: 'flex-end',
      flexDirection: 'row', 
      justifyContent: 'center',
  },
  modalBtnText: {
    color: colors.primary,
    fontWeight: 'bold',
    padding: 20
  }
});

export default AppDateTimePicker;

`

**Comment by SymntxHomendra51** [comment]
Save your time and use this package instead https://github.com/mmazzarolo/react-native-modal-datetime-picker
