### ISSUE TITLE
Can't keep my choosing data. 

### ISSUE THREAD

**Issue by akiid777** [react-native-datetimepicker/datetimepicker#567]
## Summary

Can't keep my choosing data. simply it keep rolling back to today data.

## simple screen shot:

![Alt Text](https://github.com/akiid777/login/blob/main/public/datepicker.gif)

## Reproducible sample code

```
import React, {useState} from 'react';
import {View, Text, Platform, TouchableOpacity} from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import Styles from './Styles';

export default function DatePicker(props) {
  const [showFrom, setShowFrom] = useState(false);
  const [showTo, setShowTo] = useState(false);

  const onChangeFrom = (event, selectedDateFrom) => {
    const currentDateFrom = selectedDateFrom || props.dateFrom;
    props.setDateFrom(currentDateFrom);
    setShowFrom(false);
  };

  const onChangeTo = (event, selectedDateTo)=>{
    const currentDateTo = selectedDateTo || props.dateTo;
    props.setDateTo(currentDateTo);
    setShowTo(false);
  }

  const showDatepickerFrom = () => {
    setShowFrom(true);
  };

  const showDatepickerTo = () => {
    setShowTo(true);
  };

  return (
    <View>
      <View style={Styles.dateButtonViewSection}>
      <TouchableOpacity style={Styles.dateButton} onPress={showDatepickerFrom}>
      <Text style={Styles.buttonText}> تاريخ القطف من</Text>
      <Text style={Styles.buttonText}>{props.dateFrom.toISOString().slice(0, 10)}</Text>
      </TouchableOpacity>

    <TouchableOpacity style={Styles.dateButton} onPress={showDatepickerTo}>
      <Text style={Styles.buttonText}>تاريخ القطف إلي</Text>
      <Text style={Styles.buttonText}>{props.dateTo.toISOString().slice(0, 10)}</Text>
    </TouchableOpacity>

      </View>
      {showFrom && (
        <DateTimePicker
          testID="dateTimePicker"
          value={props.dateFrom}
          mode={'date'}
          display="default"
          onChange={onChangeFrom}
        />
      )}

      {showTo && (
        <DateTimePicker
          testID="dateTimePicker"
          value={props.dateTo}
          mode={'date'}
          display="default"
          onChange={onChangeTo}
        />
      )}
    </View>
  );
};
```

this code appear in terminal also: 
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"49967":{"module":"RNDatePickerAndroid","method":"open"},"50508":{"module":"RNDatePickerAndroid","method":"open"},"51049":{"module":"RNDatePickerAndroid","method":"open"},"51590":{"module":"RNDatePickerAndroid","method":"open"},"52131":{"module":"RNDatePickerAndroid","method":"open"},"52672":{"module":"RNDatePickerAndroid","method":"open"},"53213":{"module":"RNDatePickerAndroid","method":"open"},"53754":{"module":"RNDatePickerAndroid","method":"open"},"54295":{"module":"RNDatePickerAndroid","method":"open"},"54836":{"module":"RNDatePickerAndroid","method":"open"},"55651":{"module":"RNDatePickerAndroid","method":"open"},"76279":{"module":"RNDatePickerAndroid","method":"open"},"76806":{"module":"RNDatePickerAndroid","method":"open"},"77358":{"module":"RNDatePickerAndroid","method":"open"},"77910":{"module":"RNDatePickerAndroid","method":"open"},"78462":{"module":"RNDatePickerAndroid","method":"open"},"79014":{"module":"RNDatePickerAndroid","method":"open"},"79566":{"module":"RNDatePickerAndroid","method":"open"},"80118":{"module":"RNDatePickerAndroid","method":"open"},"80670":{"module":"RNDatePickerAndroid","method":"open"},"81222":{"module":"RNDatePickerAndroid","method":"open"},"81774":{"module":"RNDatePickerAndroid","method":"open"},"82326":{"module":"RNDatePickerAndroid","method":"open"},"82878":{"module":"RNDatePickerAndroid","method":"open"},"83430":{"module":"RNDatePickerAndroid","method":"open"},"83982":{"module":"RNDatePickerAndroid","method":"open"},"84534":{"module":"RNDatePickerAndroid","method":"open"},"85086":{"module":"RNDatePickerAndroid","method":"open"},"85638":{"module":"RNDatePickerAndroid","method":"open"},"86190":{"module":"RNDatePickerAndroid","method":"open"},"86742":{"module":"RNDatePickerAndroid","method":"open"},"87294":{"module":"RNDatePickerAndroid","method":"open"},"87846":{"module":"RNDatePickerAndroid","method":"open"},"88398":{"module":"RNDatePickerAndroid","method":"open"},"88950":{"module":"RNDatePickerAndroid","method":"open"},"89502":{"module":"RNDatePickerAndroid","method":"open"},"90054":{"module":"RNDatePickerAndroid","method":"open"},"90606":{"module":"RNDatePickerAndroid","method":"open"},"91158":{"module":"RNDatePickerAndroid","method":"open"},"91710":{"module":"RNDatePickerAndroid","method":"open"},"92262":{"module":"RNDatePickerAndroid","method":"open"},"92814":{"module":"RNDatePickerAndroid","method":"open"},"93366":{"module":"RNDatePickerAndroid","method":"open"},"93918":{"module":"RNDatePickerAndroid","method":"open"},"94470":{"module":"RNDatePickerAndroid","method":"open"},"95022":{"module":"RNDatePickerAndroid","method":"open"},"95574":{"module":"RNDatePickerAndroid","method":"open"},"96126":{"module":"RNDatePickerAndroid","method":"open"},"96678":{"module":"RNDatePickerAndroid","method":"open"},"97230":{"module":"RNDatePickerAndroid","method":"open"},"...(truncated keys)...":451}
at node_modules/react-native/Libraries/Utilities/warnOnce.js:27:2 in warnOnce
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:8 in Promise$argument_0
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:105:13 in promiseMethodWrapper
at node_modules/@react-native-community/datetimepicker/src/datepicker.android.js:38:2 in DatePickerAndroid.open
at http://192.168.1.155:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:204402:41 in open
at node_modules/@react-native-community/datetimepicker/src/datetimepicker.android.js:43:32 in getPicker
at node_modules/@react-native-community/datetimepicker/src/datetimepicker.android.js:93:11 in <anonymous>

used version: current version.

**Comment by Delvio** [comment]
having the same issue on some screens and on some others does not happen. I am using the same component in both.

**Comment by Delvio** [comment]
@akiid777 any update?
