### ISSUE TITLE
My DateTimePicker can't show on android

### ISSUE THREAD

**Issue by LofWalter** [react-native-datetimepicker/datetimepicker#568]
# Question

I placed the DateTimePicker component normally on android in the way which I have used on ios, but i can't see the component show.

this is my code:

 
      <TouchableWithoutFeedback onPress={onClose}>
        <View style={styles.body}>
          <View style={styles.dateWrapper}>
            <DateTimePicker 
              testID="dateTimePicker"
              mode="date"
              display="inline"
              value={date}
              onChange={onChange}
            />
          </View>
        </View>
      </TouchableWithoutFeedback>

can anybody help me?

**Comment by yesIamFaded** [comment]
Well I am not sure but you cant set display to inline on Android so maybe thats why it does not work. Change that part depending on your Platform.
