### ISSUE TITLE
iOS `locale` Prop ignores day of the week (Sun, Mon, Tues... Sat) [fix provided]

### ISSUE THREAD

**Issue by bigorangemachine** [react-native-datetimepicker/datetimepicker#569]
# Bug report

Related to `usage is discouraged due to [not working robustly in all picker modes](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/docs/images/ios_date_new.png) (note the mixed month and day names).`  [which is this screenshot](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/docs/images/ios_date_new.png).

## Summary

Was trying to use the `locale` prop as [per the documentation](https://github.com/react-native-datetimepicker/datetimepicker#localization-note) using tagged version of latest (v5.1.0).  [Updated README.md](https://github.com/react-native-datetimepicker/datetimepicker/tree/v5.1.0#localization-note) is incorrect.  The note that you need to setup the Project Languages is also unnecessary.

To resolve that screenshot issue you need to change the scheme (**App Language** & **App Region**). 
![image](https://user-images.githubusercontent.com/4397762/156402566-11cc96aa-1d15-49b1-b8ec-c2f164113e39.png)

To help uncover the need to change the scheme I validated by altering [these lines to](https://github.com/react-native-datetimepicker/datetimepicker/blob/master/ios/RNDateTimePickerManager.m#L54-L57):
```
- (UIView *)view
{
  UIDatePicker* view = [RNDateTimePicker new];
  return view;
}
```
I put a break point to see `view.locale.currentLocale` which revealed `en_FR` and once that hint was provided to me & an old comment somewhere else gave me a clue to [change the scheme](https://user-images.githubusercontent.com/4397762/156402566-11cc96aa-1d15-49b1-b8ec-c2f164113e39.png)!

## Reproducible sample code

As per sample code in documentation but I tested with French.

```
<RNDateTimePicker locale="fr_FR" />
```

## Steps to reproduce

1. Create an App from react-native template `npx create-react-native-app`
2. Create a date picker in the root of the with a locale that mis-matches your system/default (from App.jsx/App.tsx) `const App = () => <RNDateTimePicker locale="fr_FR" />;`
3. Launch from iOS Simulator
4. Note the pickers Month & Days of the Week [similar to this](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/docs/images/ios_date_new.png)
5. Stop Server & Simulator.  Run 'Clean Build Folder'
6. Edit Scheme (from xcode menu: Product > Scheme > Edit Scheme) Ensure you are on 'Run' and look at Options
7. Change **App Language** & **App Region** to French & France
8. Re-Run App from simulator
9. Note the Month & Days of Week match languages (rather than being english days of week & french month name)

Describe what you expected to happen:

1. Months to Localize from locale prop
2. Days of Week to Localize from locale prop

## Environment info

iOS 15 (not relevant just any iOS)

`npx react-native info` output:

```bash
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.34 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: 2022.02.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/<username>/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 32.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

datetimepicker version: 5.1.0

iOS / Android version: iOS-15.0 (iOS only prop)

# Solution

I was able to [alter line 100 of the manager](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/ios/RNDateTimePickerManager.m#L100).

From 
```
RCT_EXPORT_VIEW_PROPERTY(locale, NSLocale)
```

To:
```
RCT_CUSTOM_VIEW_PROPERTY(locale, NSLocale, RNDateTimePicker) {
    [view setValue:[RCTConvert NSLocale:json] forKey:@"locale"];
}
```

Note about adding [locales via project not necessary](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/README.md?plain=1#L180-L188) (unless you want custom days of the week?)

`README.md` Update
```
## Localization note

On Android, the picker will be controlled by the system locale. If you wish to change it, [see instructions here](https://stackoverflow.com/a/2900144/2070942).

For Expo, follow the [localization docs](https://docs.expo.dev/distribution/app-stores/#localizing-your-ios-app).
```
(Edit) Also change the `Info.plist` to remove the development region. Remove `CFBundleDevelopmentRegion` from ios/<appname>/Info.plist

**Comment by vonovak** [comment]
hello and thank you for opening the issue. However, I am afraid I don't fully understand what you're trying to say.

So you're saying that when you do

`const App = () => <RNDateTimePicker locale="fr_FR" />`

then you see the names of weeks and days messed up [like here](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/docs/images/ios_date_new.png)

yes, that is a known bug, as described in the readme.

> To resolve that screenshot issue you need to change the scheme (App Language & App Region).

Okay, so you switched the two to French / France and now you see Month & Days of Week match languages both in French (your step 9.). That is expected. However, note that the `locale` prop can be dynamic:

if you support several languages, you'd want to render them like so:

`<RNDateTimePicker locale="fr_FR" />`
`<RNDateTimePicker locale="de_DE" />`
`<RNDateTimePicker locale="cs_CZ" />`
... etc

however, using the Scheme, as in your screenshot, you can only set the language and region to be a specific combination. This is useful for testing, as described here https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html#//apple_ref/doc/uid/10000171i-CH7-SW2.

I think there is some confusion about how you understood the readme. I'll try to clarify the readme and get back to you. Then you can say if it resolves your issue.

also,

```
RCT_EXPORT_VIEW_PROPERTY(locale, NSLocale)
```

and

```
RCT_CUSTOM_VIEW_PROPERTY(locale, NSLocale, RNDateTimePicker) {
    [view setValue:[RCTConvert NSLocale:json] forKey:@"locale"];
}
```

are, afaict, the same thing

**Comment by vonovak** [comment]
please let me know if the localization part of the readme is now clearer: https://github.com/react-native-datetimepicker/datetimepicker/pull/571/files

**Comment by bigorangemachine** [comment]
> please let me know if the localization part of the readme is now clearer: https://github.com/react-native-datetimepicker/datetimepicker/pull/571/files
> thank you :)

My PR update (and the note above)  is referring to iOS lower down.  Both of those methods will have the correct localization effect on the date-picker without any locale prop being passed in.  The top part is correct is you can change it in the scheme.  The follow on part is specific for iOS.

> Testing Supported Languages and Regions on Devices
> For the most accurate test of an iOS app, run your app in Simulator or on a device and change the user’s language and region settings, as described in [Setting the Language on iOS Devices](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SpecifyingPreferences/SpecifyingPreferences.html#//apple_ref/doc/uid/10000171i-CH12-SW4) and [Setting the Region on iOS Devices](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SpecifyingPreferences/SpecifyingPreferences.html#//apple_ref/doc/uid/10000171i-CH12-SW5).



> hello and thank you for opening the issue. However, I am afraid I don't fully understand what you're trying to say.
> 
> So you're saying that when you do
> 
> `const App = () => <RNDateTimePicker locale="fr_FR" />`
> 
> then you see the names of weeks and days messed up [like here](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/docs/images/ios_date_new.png)
> 
> yes, that is a known bug, as described in the readme.

Yes... My PR and the above comments fixes the issue.

> Okay, so you switched the two to French / France and now you see Month & Days of Week match languages both in French (your step 9.). That is expected. However, note that the `locale` prop can be dynamic:

No what I was saying was I changed the scheme to french & france and both months and day of week is localized

> if you support several languages, you might want to render them like so:
> 
> `<RNDateTimePicker locale="fr_FR" />` `<RNDateTimePicker locale="de_DE" />` `<RNDateTimePicker locale="cs_CZ" />` ... etc
> 
> 
> ```
> RCT_EXPORT_VIEW_PROPERTY(locale, NSLocale)
> ```
> 
> and
> 
> ```
> RCT_CUSTOM_VIEW_PROPERTY(locale, NSLocale, RNDateTimePicker) {
>     [view setValue:[RCTConvert NSLocale:json] forKey:@"locale"];
> }
> ```
> 
> are, afaict, the same thing

Please check out the code and you'll see it is different.  They are not.  Looking at the source code from react-native these do different things.  However this is my first run into the xcode coding world but just running the functions through my head they are different.  `RCT_EXPORT_VIEW_PROPERTY(locale, NSLocale)` creates a new NSLocale object with `locale-prop` ... I'm not sure why... I assume the value is available somewhere else.

`[view setValue:[RCTConvert NSLocale:json] forKey:@"locale"];`  sets the attribute of the `view.locale` equal to (whatever json is) cast as NSLocale.  Json looks to be some magic :P.  Either way you can put break points in and see what json does... I didn't dig into it.  Either way using this makes it so the operating system is ignored and is more reliable.  This actually fixes what that screenshot is showing.

As long as the scheme is off it'll always mix localize.

Please make the change I mentioned to line 100

> I was able to [alter line 100 of the manager](https://github.com/react-native-datetimepicker/datetimepicker/blob/v5.1.0/ios/RNDateTimePickerManager.m#L100).` 

If you debug that you'll see how the localization gets mixed with what you pass and what the scheme is configured.

**Comment by bigorangemachine** [comment]
# Update

I had removed CFBundleDevelopmentRegion from `ios/<appname>/Info.plist` which we discovered is related to the bug.

![image](https://user-images.githubusercontent.com/4397762/157255721-3fedfa6e-b69c-4576-8a7a-ea1d739e5196.png)

**Comment by bigorangemachine** [comment]
okay I'm seeing the extent of the issue now.

Part of it is the device needs to align to the passed setting but you can only change the month :\

**Comment by vonovak** [comment]
> Should probably remove this prop as this is completely dependant on the client OS

please see https://github.com/react-native-datetimepicker/datetimepicker/pull/544 for more context

the prop will be available because there are uses cases for it, but its usage will remain discouraged...

thank you! :)
