### ISSUE TITLE
Error while installing or updating

### ISSUE THREAD

**Issue by zoolle** [react-native-datetimepicker/datetimepicker#578]
# Bug report
```
/Volumes/Work/Desktop/workspace/development-rider/node_modules/@react-native-community/datetimepicker: Command failed.
Exit code: 127
Command: patch-package
Arguments: 
Directory: /Volumes/Work/Desktop/workspace/development-rider/node_modules/@react-native-community/datetimepicker
Output:
/bin/sh: patch-package: command not found
```
-->

## Summary

1. change the version from my `package.json` from 5.1.0 to 6.0.0 and use `yarn install` I get the error above.  
2. remove the packages using `yarn remove @react-native-community/datetimepicker` and then `yarn add @react-native-community/datetimepicker` I also get the error above.
With 5.1.0 I have no issues

**Comment by vonovak** [comment]
hello, this is fixed in 6.0.1

thank you 🙂
