### ISSUE TITLE
Custom behaviour when clicking on cancel button on android

### ISSUE THREAD

**Issue by pierrezimmermannbam** [react-native-datetimepicker/datetimepicker#586]
# Feature request

I'd like to be able to pass a callback in the open method params that would be executed when the cancel button is pressed

## Why it is needed

My use case is the following : i have an input with the selected date and it has a different style when the date picker dialog is open. I handle this with a state that I set to true before calling the open method and to false in the onChange param of the openMethod

```javascript
setIsFocused(true);

DateTimePickerAndroid.open({
      value: currentValue || new Date(Date.now()),
      onChange: (e) => {
        const { timestamp } = e.nativeEvent;
        if (timestamp) {
          const date = new Date(timestamp);
          setCurrentValue(date);
          onChange(date);
          setIsFocused(false);
        }
      },
    });
```

As far is I could tell there is no way to set my state to false when the user presses the cancel button, is there ?
If not I think it would be great if possible to be able to customize behaviour on cancel button press in a similar way as for the ok button

## Possible implementation

I haven't looked at the library code and have no idea if this is even possible. If it is and you think it's a good idea i'd be glad to help

**Comment by vonovak** [comment]
hello, you can tell what happened by looking at `event.type`, the possible values are here https://github.com/react-native-datetimepicker/datetimepicker/blob/e9ae918535befbad0f5652a979a3dbdb64356fa7/src/constants.js#L15

I'm planning to make some docs improvements in this respect some time next month.

Hope this helps :)

**Comment by pierrezimmermannbam** [comment]
@vonovak  thanks for your quick reply, it works indeed ! For whatever reason I had thought that the onChange function was not called on dismiss but it does

**Comment by fukemy** [comment]
DateTimePickerAndroid.open did nothing to me, I didnt see the picker show
