### ISSUE TITLE
Can we set dynamically translation of the picker on iOS ?

### ISSUE THREAD

**Issue by GabinH** [react-native-datetimepicker/datetimepicker#596]
Hi,

This is about **locale on iOS** and the way to work with it : I read the #540 #569 and so on, but I always don't understand **if we can dynamically set locale for iOS**.

At this moment, I understand that the picker set the locale according to the OS locale (and we can play with it in the xCode scheme).

I also understand that the locale props (iOS only) has a problem with translation of week days.

And I read the Apple doc ([this one](https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions)), but for me, it only let us say to xCode that the app can use defined locale.

So my question is : Is there a way to set dynamically the locale for the picker, without talking about OS locale ?

Thank you for your time

**Comment by vonovak** [comment]
Hello and thanks for asking,

> And I read the Apple doc ([this one](https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions)), but for me, it only let us say to xCode that the app can use defined locale.

it not only allows to tell xcode what locales you support but you can then also change the locale through the Settings (settings -> apps -> your app).

>  Is there a way to set dynamically the locale for the picker, without talking about OS locale ?

yes, the way to do it is through the `locale` prop.

Thank you 🙂
