### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by camdagr8** [react-native-datetimepicker/datetimepicker#598]
# Question

Is there a simple example anywhere? 
The App.js example just has way too much going on to get an idea of how to implement this in your own code.

**Comment by vonovak** [comment]
Hello and thanks for asking,
there currently isn't a simple example available. But if you remove the windows-specific code from the example app, you should get code that is fairly digestible :)


Thank you 🙂

**Comment by vonovak** [comment]
actually, there is an example here: https://github.com/react-native-datetimepicker/datetimepicker#usage :)
