### ISSUE TITLE
OnChange date then close modal 

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-datetimepicker/datetimepicker#602]
I want that when I select data in ios then close the modal automatically.
It's in date mode.

**Comment by bobbygrossmann** [comment]
Im also searching for the toggle effect.

**Comment by brianakidd** [comment]
Same for me - I'm trying to use the compact display for iOS and calendar display for Android.  Even if cannot programmatically close, I at least need a "Done" or "Confirm" button on the calendar rather than the user having to click away.

**Comment by YuriVini** [comment]
Any PR about this? Same for me here. I'd like to help if needed.

**Comment by YuriVini** [comment]
Hey Guys! I got a solution! @Salmankhan033 @bobbygrossmann 

The `onChange` has to be like this... `onChange={(event: Event, date: Date) => setIosDate(date)}`
You have to set the date in a state before set in the setDate of DateTimePicker. And the prop `value`, has to have the value of `iosdate`
Then, if you have a button in your app like me, I have a funtion to set the `iosdate` state in `setDate` of DateTimePicker, the `handleSubmit`
Hope this can help other people.

```
  const [iosdate, setIosDate] = useState<Date>(datePicker || new Date());
  const bottomSheet = useRef<typeof BottomSheet>(null);

  const handleSubmit = () => {
    setDate(iosdate);
    bottomSheet.current.close();
  };

  const handleInputPress = () => bottomSheet.current.show();

  return (
    <>
        <BottomSheet draggable={false} ref={bottomSheet} height={scale(300)}>
          <View style={styles.containerBottomSheet}>
            <DateTimePicker
              value={iosdate || new Date()}
              mode="date"
              display="spinner"
              onChange={(event: any, date: any) => setIosDate(date)}
              maximumDate={maxDate}
              minimumDate={minDate}
              locale="pt"
              themeVariant="light"
              textColor="black"
            />
            <Button style={{ width: 200, alignSelf: 'center' }} onPress={handleSubmit}>
              {buttonText}
            </Button>
          </View>
        </BottomSheet>
    </>
  );
};

```

**Comment by newyorksoul** [comment]
> 

what's `datePicker `?

**Comment by YuriVini** [comment]
> > 
> 
> what's `datePicker `?

I don't use the DateTimePicker directly, this is a component, and the `datePicker` is a prop that I pass initialDate and lastDate when call this component. If u r using directly, I suppose that this problem of modal doesn't happen.

**Comment by vonovak** [comment]
Hello and thanks for asking,

> Even if cannot programmatically close, I at least need a "Done" or "Confirm" button on the calendar rather than the user having to click away.

You can add custom buttons below the calendar view if you use `display="inline"`.
If you want to "reset" the appearance of the compact calendar view right after the user selects a date, you can use the `key` prop:

```
<DateTimePicker                
                value={date}
                mode={'date}
                display={'compact'}
                disabled={disabled}
                key={date.toISOString()}
              />
```

Thank you 🙂

**Comment by Martinnord** [comment]
Why can't it just close after you've selected the date? Why would anyone want it to keep being open?
