### ISSUE TITLE
error: SyntaxError DateTimePickerAndroid.js 

### ISSUE THREAD

**Issue by putuoka** [react-native-datetimepicker/datetimepicker#603]
error: SyntaxError: D:\user\app\node_modules\@react-native-community\datetimepicker\src\DateTimePickerAndroid.js: Unexpected token, expected "]" (97:42)

   95 | }
   96 |
>  97 | function dismiss(mode: AndroidNativeProps['mode']) {
      |                                           ^
   98 |   // $FlowFixMe - `AbstractComponent` [1] is not an instance type.
   99 |   pickers[mode].dismiss();
  100 | }

version:
"@react-native-community/datetimepicker": "^6.1.2",
"react-native-modal-datetime-picker": "^13.1.2",
"react-native": "0.63.4",

Android version: emulator nexus 10 tablet

**Comment by ahardy42** [comment]
I'm seeing this on iOS for some reason

**Comment by ahardy42** [comment]
might need to update flow in your project??

**Comment by dspinellis** [comment]
A possible workaround is to install an earlier version, e.g. with `yarn add @react-native-community/datetimepicker@npm:3.5.2`.

**Comment by sedatbasar** [comment]
Having same issue with RN 0.63.4 TS 3.7.5 project.
Not using flow in project so cant upgrade it or sth. Also tried to use older version of package but for those i am getting "Unhandled promise rejection [TypeError: Cannot read property 'open' of null" error.

**Comment by buschco** [comment]
You can use [patch-package](https://github.com/ds300/patch-package) to manual replace the PropertyTypes:  

`AndroidNativeProps['mode']` -> `$PropertyType<AndroidNativeProps, 'mode'>`

**Comment by waqaramjad** [comment]
same issue here

**Comment by GarciaaMarilia** [comment]
> A possible workaround is to install an earlier version, e.g. with `yarn add @react-native-community/datetimepicker@npm:3.5.2`.

this works for me

**Comment by vonovak** [comment]
hello, I'm closing this as resolved - you can use one of the aforementioned workarounds or upgrade react native to >= 0.66

thank you!
