### ISSUE TITLE
Wrong Time

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-datetimepicker/datetimepicker#604]
In selected Time i apply Moment `moment(selectedDate).format('HH:mm')`  so it give wrong time.
let's suppose I select 9 am then it returns 10 pm,
select 8 pm then it returns 9 am.
also **am** and **pm** is difference

**Comment by stct97** [comment]
same, any solution?

**Comment by Salmankhan033** [comment]
> same, any solution?

I set it according to time zone
 like as `const _currentDate = moment.tz(selectedDate, timeZone).format('HH:mm')`
