### ISSUE TITLE
Timer mode

### ISSUE THREAD

**Issue by arisyo13** [react-native-datetimepicker/datetimepicker#611]
## Feature request
New mode: `timer`

## Why it is needed

Since most of the wheel and picking functionality is there it would be nice to add a timer feature so the user will be able to pick a timer value from `{ hours: number, minutes: number, seconds: string }`
 
![timer](https://user-images.githubusercontent.com/51513565/169522129-5127578d-84dc-4993-8ef3-00d42d2ea988.jpeg)

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Please see https://github.com/react-native-datetimepicker/datetimepicker#mode-optional

"countdown" mode.

As you can see here https://developer.apple.com/documentation/uikit/uidatepickermode/uidatepickermodecountdowntimer?language=objc

the countdown mode only has hours and minutes, so we cannot support seconds.


Thank you 🙂
