### ISSUE TITLE
Error: Could not resolve "./picker" 

### ISSUE THREAD

**Issue by bandhavya** [react-native-datetimepicker/datetimepicker#612]
# Bug report

## Summary

In src/DateTimePickerAndroid.js file,
import pickers from './picker';

but picker file is not available. Instead picker.android.js, picker.ios.js, picker.windows.js files are present.
<img width="889" alt="Screenshot 2022-05-23 at 3 25 58 PM" src="https://user-images.githubusercontent.com/12510202/169794470-de9b134d-2a4d-48e4-8407-489cf67daba6.png">

Hence the error is shown as above when trying to use it and build.

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
# paste it here
```

datetimepicker version: 6.1.3

Trying to build using esbuild.

But same works fine on using 5.1.0 version

**Comment by eelior** [comment]
Same here, did anybody found a solution for this on web?
I am trying to use this as part of the dependencies of `https://github.com/wix/react-native-ui-lib`

**Comment by vonovak** [comment]
closed via https://github.com/react-native-datetimepicker/datetimepicker/pull/625
