### ISSUE TITLE
Select time after select date

### ISSUE THREAD

**Issue by juntiapps** [react-native-datetimepicker/datetimepicker#616]
# Question
I want to ask. Is there any way to select a time, right after select a date.

for example i click select date button->modal open->selecting date->selecting time->modal->close

**Comment by vonovak** [comment]
Hello and thanks for asking,
on Android, you have to confirm the selection byt pressing the "OK"(or other) button. That will hide the dialog and trigger the `onChange` event. From there, you can open another the time picking dialog.

on iOS, when user selects the date, you could hide the calendar view and show time picker instead but I fear it'd probably feel awkward. I recommend you use the `datetime` mode.
Thank you 🙂
