### ISSUE TITLE
Is TypeError: value.getTime is not a function. (In 'value.getTime()', 'value.getTime' is undefined) this fixed in the new Version?

### ISSUE THREAD

**Issue by yesIamFaded** [react-native-datetimepicker/datetimepicker#618]
I just wanted to ask if that behavior is fixed or if you still need to change the Code of the Module manually.

Please refer to this: https://github.com/react-native-datetimepicker/datetimepicker/issues/566

Faded

**Comment by vonovak** [comment]
Hello 👋 ,
this issues should be resolved with https://github.com/react-native-datetimepicker/datetimepicker/issues/566#issuecomment-1066017898

With that, I'm closing the issue,
Thank you! 🙂

**Comment by codermaen** [comment]
`  const safeMinDate = minDate ? new Date(minDate) : new Date(1900, 0, 1);
  const safeMaxDate = maxDate ? new Date(maxDate) : new Date(2100, 11, 31);`
passing this as minDate and maxDate worked for me
