### ISSUE TITLE
[iOS] When I set a maximumDate and I pick the first available date without changing, it returns new Date() instead of the correct date

### ISSUE THREAD

**Issue by fede4954** [react-native-datetimepicker/datetimepicker#620]
## Summary

In my project I set a maximumDate of 18 years ago for the users that will sign up as it's an adult application, however, when I open the picker and confirm with the first available date (which is 18 years ago) what I get is the current date, basically what new Date() would return instead of a date 18 years ago. But this happens with any date, I tried it with static dates like new Date(1999, 0, 1) and it had the same issue.

Additionally I'd like to mention that I couldn't find onConfirm on the documentation here on GitHub, even though it's a required prop.

## Reproducible sample code

This is a simplified version of the code of my application:

```
const newDate = new Date()
const minYear = newDate.getFullYear() - 18
newDate.setFullYear(minYear)

<DateTimePickerModal
              cancelTextIOS='Cancel'
              confirmTextIOS='Confirm'
              isVisible={isDatePickerVisible}
              mode='date'
              onConfirm={(selectedDate) => {
                console.log(selectedDate)
                setDatePickerVisibility(false)
              }}
              onCancel={() => setDatePickerVisibility(false)}
              minimumDate={new Date(1920, 0, 1)}
              maximumDate={newDate}
/>
```

## Steps to reproduce

1. Open the picker with a maximum date on iOS
2. Press confirm without changing the date, using the first available date 
3. The current date (new Date()) will be returned and logged instead of the right date which would be the first date available

Basically, opening the picker and pressing confirm with the first available date should return that date, and not the current date.

![Screen Shot 2022-06-10 at 2 06 15 PM](https://user-images.githubusercontent.com/80700338/173060967-b60776bc-4698-42df-bb14-08b51332f2fd.png)

![Screen Shot 2022-06-10 at 2 10 29 PM](https://user-images.githubusercontent.com/80700338/173061554-a3c71c83-3858-4e1b-973d-c93d3924f53c.png)

## Environment info

expo: 44.0.0

`npx react-native info` output:

```bash
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 22.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.1 - ~/.nvm/versions/node/v16.14.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 4.0.0

iOS / Android version: 15.5 (running on a simulator)

**Comment by vjoby-wavefin** [comment]
I have the same problem as well, were you able to find a workaround
even the latest version doesn't seem to fix it

**Comment by vonovak** [comment]
Hello and thanks for reporting,
this library does not provide any `DateTimePickerModal`, and no `onConfirm`, `onCancel` and many of the other props in your repro. Please open a new issue which reproduces the problem using this library.
Thank you 🙂
