### ISSUE TITLE
[iOS] timepicker keyboard input bug

### ISSUE THREAD

**Issue by CptMaumau** [react-native-datetimepicker/datetimepicker#631]
# Bug report

Inputting time manually with the keyboard doesn't seem to work properly when inputting hh:mm. Works fine when inputting hour or minute separatly.

https://user-images.githubusercontent.com/5366008/179143566-a706c5f8-a232-4970-a415-0d86245a7d2e.MP4

## Reproducible sample code

```Javascript
<RNDateTimePicker display="inline" mode="datetime" />
```

## Steps to reproduce

1. open datetime picker
2. press time picker
3. press minute picker
4. press 9 on the keyboard 4 times 

Describe what you expected to happen:

1. time picker shows 09:09

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 30.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.5.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
    Watchman: 2022.06.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 6.2.0

iOS version: 15.5

**Comment by vonovak** [comment]
Hello and thanks for reporting,
what you're describing is the expected behavior:
if you want to enter the time "9:09", you need to type "0909" on the keyboard, not "9999".

e.g. if you type "1234" you'll get "12:34".


Thank you 🙂
