### ISSUE TITLE
[react-native-windows] REGDB_E_CLASSNOTREG error in RoGetActivationFactory

### ISSUE THREAD

**Issue by taenri** [react-native-datetimepicker/datetimepicker#635]
On Windows 11, react-native-windows version 0.68.2 we get a runtime error when trying to use the DateTimePicker after following the manual setup instructions outlined in the repo.

The error occurs when we try to create a new instance of winrt::DateTimePicker::ReactPackageProvider in our App class. The error code is REGDB_E_CLASSNOTREG error, which happens after calling RoGetActivationFactory for the winrt class name DateTimePicker.ReactPackageProvider.

This happens because the winrt class namespace does not match the DLL name. Either the winrt namespace needs to be renamed to DateTimePickerWindows, or the DateTimePickerWindows project/dll needs to be renamed to just DateTimePicker. I have tested this with local modifications to the vcxproj, and after these changes the date time picker works as expected.

**Comment by vonovak** [comment]
@chiaramooney @rectified95 any ideas about this? Thank you 🙂

**Comment by taenri** [comment]
@chiaramooney / @rectified95 - Any updates on this issue?

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.7.2 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
