### ISSUE TITLE
Props to hide and View the Date Components.

### ISSUE THREAD

**Issue by shudanshus198** [react-native-datetimepicker/datetimepicker#638]
# Feature request

## Why it is needed

This props is needed to decide weather to display  the date Modal or not according to the props value. If its implemented then we don't have to Coat the Component inside the condition.

## Possible implementation

I just want to send the props to display and hide the modal on the basis of the props value.

### Code sample

![image](https://user-images.githubusercontent.com/59770028/181166632-49a64c5a-afad-48f7-89a9-b75a3f365523.png)

**Comment by vonovak** [comment]
Hello and thanks for asking,
the idiomatic way to show / hide components in React is to render or not render them, as you have shown in your screenshot.

Therefore, we won't be adding a `hide` or similar prop.
Thank you 🙂

**Comment by shudanshus198** [comment]
Yes i know the method which you are using is right but I am facing issue
with it as if you add multiple components of it on a single page and then
use it the modal open again and again.

Which creates the problem ..

If you have time I can show it to you .

Iam a newbie in React Native.

**Comment by nochkin** [comment]
@vonovak 
That may work on Android, but I have a different behavior on iOS. Maybe I'm missing something really obvious.
When I have <DateTimePicker ...> rendered, I see a button with a date. When I tap the button, I get the calendar popup.

If you are saying I need to stop rendering in order to dismiss the popup, then how do I get that button back? Even if I render my own button instead, then having <DateTimePicker ...> component rendered will not get the calendar popup visible. I will need to tap twice -- first time to get <DateTimePicker ...> rendered by showing a button, and the second tap to actually get the calendar visible.

**Comment by vladstanescu** [comment]
A workaround I can suggest is having a state variable `temporarilyHidden: false` that onChange you set to true then setTimeout for changing it back to false: `setTimeout(() => { this.setState({ temporarilyHidden: false }); }, 100);` ; also, conditionally display the `!temporarilyHidden && <DateTimePicker...`

**Comment by vladstanescu** [comment]
Gotcha, I thought the problem was the same as mine that you were not able to dismiss it without clicking outside of it.

In that case, wrapping your component in a Modal opened programmatically and having the picker inline there would be the solution probably.

**Comment by vonovak** [comment]
@nochkin 

> If you are saying I need to stop rendering in order to dismiss the modal, then how do I get that button back?

I'm not sure I fully understand what you're after, but you can try re-rendering the `<DateTimePicker` with a changed `key` prop, which will re-create the view, effectively dismissing it if it's "presented"

**Comment by nochkin** [comment]
@vonovak It's a nice trick, but I was after something else. I need to make the modal opened programmatically instead of clicking a button. Sorry for confusion, it's been a year.
As an example, I'd like to have my own button which opens the date/time modal.

**Comment by vonovak** [comment]
ah I see, missed that in the last comment, and from the previous comments I did not understand. Anyways, it's not possible with the current api, but I tend to think it can be done... That being said I'm no longer very active here, so a PR would be appreciated.

**Comment by nochkin** [comment]
No problems, I understand. I was very close to PR a year ago, so I may consider it now when I'm back on that project which uses it. Thanks for your response.
