### ISSUE TITLE
Release 6.3.0 from npm doesn't have jest folder

### ISSUE THREAD

**Issue by bojackhorseman0309** [react-native-datetimepicker/datetimepicker#640]
# Bug report

## Summary

I tried to install the latest version since it has some testing improvements that I would like to use, but I'm kinda confused after installing the latest version https://github.com/react-native-datetimepicker/datetimepicker/releases/tag/v6.3.0 and it doesn't have the Jest folder in it but the source code from the release does have it in there.

I tried reinstalling the library on a new project to see if Expo or something was blocking or not updating correctly but inside node_modules it still doesn't have the jest folder.

## Steps to reproduce

1. `npm i @react-native-community/datetimepicker`

Describe what you expected to happen:

1. Should have the jest folder like mentioned in the docs 
```
"setupFiles": ["./node_modules/@react-native-community/datetimepicker/jest/setup.js"]
```

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.3.1 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:

**Comment by vonovak** [comment]
hello @bojackhorseman0309 thanks for flagging this, it should be fixed in the latest version.

thanks! :)

**Comment by bojackhorseman0309** [comment]
Thanks @vonovak I would have helped you with a PR but I haven't published an npm package and didn't knew that it was just a little change lol.

**Comment by vonovak** [comment]
No worries, you did your part by reporting the problem 😉.
