### ISSUE TITLE
Date Picker not visible on Android

### ISSUE THREAD

**Issue by MrShubhamSingh** [react-native-datetimepicker/datetimepicker#642]
Version Info :
 "react": "17.0.2",
 "react-native": "0.68.1",
"@react-native-community/datetimepicker": "^6.3.1",

Code Snippet :
     1 .  <DateTimePicker
                  value={new Date()}
                  display='default'
                  mode='date'
                  onChange={()=>{}}
                  style={{ width:200, height:200, backgroundColor:'white'}}
                />
     2. <RNDateTimePicker
                  value={new Date()}
                  display='default'
                  mode='date'
                  onChange={()=>{}}
                  style={{ width:200, height:200, backgroundColor:'white'}}
                />         
                
   Tried the above code snippet but unable to see picker on Android.
   
   P.S : Tried changing display and mode to different values, still no luck!

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I cannot reproduce this. Please add a runnable repro,
Thank you 🙂

**Comment by owaisansarii** [comment]
Rebuild your project after installing it'll work

**Comment by hypesol** [comment]
Thanks @owaisansarii
