### ISSUE TITLE
How can I select Range/multiple dates

### ISSUE THREAD

**Issue by engr425imran** [react-native-datetimepicker/datetimepicker#643]
# Question
<img width="314" alt="Screenshot 2022-08-08 at 3 31 49 PM" src="https://user-images.githubusercontent.com/70444687/183399145-d1576cf3-3d94-4b60-bbdd-91f3387dfec1.png">

Thankful for any help you can offerr

**Comment by vonovak** [comment]
Hello and thanks for asking,
this is not supported by the underlying native pickers and therefore cannot be supported.
Thank you 🙂
