### ISSUE TITLE
Disabled date specific

### ISSUE THREAD

**Issue by muhammadashariabdillah24** [react-native-datetimepicker/datetimepicker#644]
# Feature request

So I had an idea to ask this library could have a feature to disable certain dates in calendar

## Why it is needed

So that people can remove certain days from the calendar

## Possible implementation

this feature will work if someone wants to remove a certain day from the calendar, so there are two ways i.e.

1. enter a list of any dates you want to deactivate

example:

<DateTimePicker
disableDate={['2022-05-05', '2022-06-06']}
 />

2. turn off certain days that you want to disable

example:

<DateTimePicker
disableDate={['Sun', 'Mon', 'Tue']}
 />

**Comment by vonovak** [comment]
Hello and thanks for asking,
unfortunately the native apis do not offer such functionality, so it cannot be implemented here.
Thank you 🙂
