### ISSUE TITLE
positiveButtonLabel and negativeButtonLabel not work on Android imperative api

### ISSUE THREAD

**Issue by longb1997** [react-native-datetimepicker/datetimepicker#646]
# Bug report
Hi! When I try to using positiveButtonLabel and negativeButtonLabel props on Android imperative api, but them not working.

```js
                DateTimePickerAndroid.open({
			mode: 'date',
			value: value ? moment(value, 'YYYYMMDDHHmm').toDate() : new Date(),
			display: 'calendar',
			positiveButtonLabel: 'Positive',
			negativeButtonLabel: 'Negative',
			minuteInterval: props.minuteInterval,
			onChange: (event, newDate) => {
				onChange(newDate);
			},
		});
```

datetimepicker version: ^6.3.1

Android version: 12

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.3.2 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
