### ISSUE TITLE
Hello and thanks for reporting,

### ISSUE THREAD

**Issue by hpbush** [react-native-datetimepicker/datetimepicker#662]
Hello and thanks for reporting,
as of v6.3.4 the width should now be computed by the native side and you should not need to specify it manually.
If you're still running into problems, please open a new issue.
Thank you 🙂

_Originally posted by @vonovak in https://github.com/react-native-datetimepicker/datetimepicker/issues/339#issuecomment-1257206539_
    
I just upgraded to 6.3.4 from 6.2.0 hoping that this issue would be resolved, but it's worse than before.  Now not only do I have to supply an arbitrary width, I also have to specify a height in order to make the label appear.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
please follow the issue template,
Thank you 🙂
