### ISSUE TITLE
hello, I'm closing this as resolved - you can use one of the aforementioned workarounds or upgrade react native to >= 0.66

### ISSUE THREAD

**Issue by TimmBaier** [react-native-datetimepicker/datetimepicker#663]
hello, I'm closing this as resolved - you can use one of the aforementioned workarounds or upgrade react native to >= 0.66

thank you!

_Originally posted by @vonovak in https://github.com/react-native-datetimepicker/datetimepicker/issues/603#issuecomment-1177742833_

I still have this problem with react native 0.69.4. Upgrading didn't work.

**Comment by vonovak** [comment]
hello, you need to use correct react native as well as Flow version: flow >=0.155 is needed: https://flow.org/en/docs/types/indexed-access/

thank you 🙂

**Comment by TimmBaier** [comment]
Is there a way to use this without flow?

**Comment by vonovak** [comment]
try using https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types
