### ISSUE TITLE
Callback to know if user closes the datepicker without picking the date

### ISSUE THREAD

**Issue by musmanfaisal** [react-native-datetimepicker/datetimepicker#667]
# Question

I am not sure if this is a valid question but I can not seem to find the proper use of this feature. I need some callback or some way to know when the date picker is closed.
In the past, I get that there used to be something like onCancel but I seem to think it is not working anymore. I need some way of knowing if a user closed the date picker without choosing a date. Any help will be appreciated

![ezgif-5-ad51882af9](https://user-images.githubusercontent.com/61688410/192970056-11b56138-4e64-4714-9e53-22e8f51ccc53.gif)

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.5.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
