### ISSUE TITLE
Can't build on Android with newArchEnabled=true

### ISSUE THREAD

**Issue by EduFrazao** [react-native-datetimepicker/datetimepicker#668]
# Bug report

Hi. After change newArchEnabled=true on a React Native 0.70.1 project, I got this error trying to build my App:

`
  -- Configuring incomplete, errors occurred!
  See also "/home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/android/app/.cxx/Debug/453t2g58/arm64-v8a/CMakeFiles/CMakeOutput.log".
  
  CMake Error at /home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/android/app/build/generated/rncli/src/main/jni/Android-rncli.cmake:6 (add_subdirectory):
    add_subdirectory given source
    "/home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/node_modules/@react-native-community/datetimepicker/android/build/generated/source/codegen/jni/"
    which is not an existing directory.
  Call Stack (most recent call first):
    /home/eduardo/Projetos/DavinTI/virtruvio/vitruvio-react-native/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:54 (include)
    CMakeLists.txt:7 (include)

`

## Environment info

`npx react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Linux 5.19 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 31.28 GB / 62.74 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 20220924.070135.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      Android NDK: 25.1.8937393
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 6.4.0

Android Version: 9.0

[CMakeOutput.log](https://github.com/react-native-datetimepicker/datetimepicker/files/9674559/CMakeOutput.log)

**Comment by vonovak** [comment]
Hello and thanks for reporting,
we do not have new architecture supported on android yet, so this is probably expected. Please track the progress here:https://github.com/react-native-datetimepicker/datetimepicker/issues/622
Thank you 🙂

**Comment by EduFrazao** [comment]
> Hello and thanks for reporting, we do not have new architecture supported on android yet, so this is probably expected. Please track the progress here:#622 Thank you slightly_smiling_face

Hi @vonovak . Thank you for your answer! Sure, I will follow #622. Do you prefer that I close this bug?

**Comment by vonovak** [comment]
yes, let's please track this in #622 
thanks
