### ISSUE TITLE
limit the hours available

### ISSUE THREAD

**Issue by yabasha** [react-native-datetimepicker/datetimepicker#672]
# Question

I want to set limit for hours from current time, I want to make an app the gives short period of time to interact with it from the time of setting the time value

For example: from `Date.now()` to display hours or allow to select 4 hours, so if now is 7 it will show 8, 9, 10, and 11 so user can only select from those hours.

Please Advice,

**Comment by vonovak** [comment]
Hello and thanks for asking,
this is not possible with this picker. I suggest you design your own picker for this purpose.
Thank you 🙂
