### ISSUE TITLE
Modal crashes and closes with "[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'prevDate.toLocaleDateString')]" when I press "Cancel" or dismiss it.

### ISSUE THREAD

**Issue by eatanga-git** [react-native-datetimepicker/datetimepicker#676]
# Bug report
When I open the modal, it looks fine. I can change the date and press OK, and the date will update.
![image](https://user-images.githubusercontent.com/55466881/197293421-9b002437-5180-41d1-bb66-3d0e484bfcd3.png)

But... when I dismiss it or press cancel, it crashes and I get: "Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'Date.toLocaleDateString')]" error.

![image](https://user-images.githubusercontent.com/55466881/197291816-5c0a32ab-efdc-48dc-a5af-2f32c60b21f6.png)
 

```bash
export function Datetime  ()  {
    const [date, setDate] = useState(new Date(1598051730000));
    const [mode, setMode] = useState('date');
    const [show, setShow] = useState(false);
  
    const onChange = (event, selectedDate) => {
      const currentDate = selectedDate;
      setShow(false);
      setDate(currentDate);
    };
  
    const showMode = (currentMode) => {
      if (Platform.OS === 'android') {
        setShow(true);
        // for iOS, add a button that closes the picker
      }
      setMode(currentMode);
    };
  
    const showDatepicker = () => {
      showMode('date');
    };
  
    const showTimepicker = () => {
      showMode('time');
    };
  
    return (
      <View  >
        <Pressable onPress={showDatepicker}>
            <Text>"Show date picker!"</Text> 
        </Pressable>
        <Pressable onPress={showTimepicker} title="Show time picker!" />
        <Text>selected: {date.toLocaleString()}</Text>
        {show && (
          <DateTimePicker
            testID="dateTimePicker"
            value={date}
            mode={mode}
            is24Hour={true}
            onChange={onChange}
          />
        )}
      </View>
    );
  };
```
![image](https://user-images.githubusercontent.com/55466881/197292374-d8524add-6349-4bf6-827a-e321f200727b.png)

expo:
![image](https://user-images.githubusercontent.com/55466881/197293022-85c29bc1-571b-4912-b705-0acc79436917.png)

node:
![image](https://user-images.githubusercontent.com/55466881/197292679-847c4cc2-f4c1-43f4-98f6-759a67b00753.png)

datetimepicker version:  
![image](https://user-images.githubusercontent.com/55466881/197292994-a2536e81-5f03-415a-8d88-b9cbd3273c97.png)

iOS / Android version: x.x

**Comment by vonovak** [comment]
Hello,
you're getting `TypeError: undefined is not an object` because you're calling `.toLocaleDateString` on `undefined`.
Thank you 🙂
