### ISSUE TITLE
Android date is always +1 from the actual chosen Date

### ISSUE THREAD

**Issue by RGDEV2022** [react-native-datetimepicker/datetimepicker#679]
# Bug report

## Summary

The date returned in the onChange for Android is always +1 day of the actual date. The component shows the correct date but the actual value returned is wrong. This works for iOS so you can see on iOS after picking a date on android that it is +1. 
2022-09-30T00:00:00.000Z ---- date returned on Android when you choose 09/29 (Component however on android shows 09/29)
2022-09-29T05:00:00.000Z ---- on iOS it returns the correct value.

## Reproducible sample code
```
 <DateTimePicker
            timeZoneOffsetInMinutes={timeZoneOffset}
            style={{ }}
            value={new Date()}
            mode='date'
            onChange={(event: any, value: any) => handleUpdate(value)}
          />
```
I have tried the timeZoneOffsetInMinutes `new Date().getTimezoneOffset() * -1` "fix" - this doesn't do anything. 
Also tried converting the onChange date value like this -  
```
new Date(date).toLocaleString('en-US', {
        timeZone: 'UTC'
      })
```
This doesn't fix it either.

## Steps to reproduce

Try picking the same date on iOS and Android and check the return value.

Describe what you expected to happen:

Same date returned on both.

## Environment info

datetimepicker version:  "6.1.2",

iOS / Android version: ALL

**Comment by RGDEV2022** [comment]
I don't understand how no one else has encountered this. This is a critical bug in the most popular date picker library library. I have also replicated this exact same behaviour in a new project so this is a big issue. The date on Android is +1 days but the component gives you the illusion that it is the correct day by adjusting it back -1 days for the UI.

**Comment by jessrichmond** [comment]
@RGDEV2022 did you close this because you figured out the solution? i am currently running into the same issue you opened this ticket with

**Comment by bmitioglov** [comment]
it's not only on Android, same for ios

**Comment by KenObie** [comment]
Has a solution been found for this? I am running into the same issue.  The date displays correctly in the DateTimePicker component as well as my custom Text Component...but it is +1 in logs and when pushing to a database...
