### ISSUE TITLE
Support for Linux & MacOS

### ISSUE THREAD

**Issue by anodynos** [react-native-datetimepicker/datetimepicker#681]
# Can this library ever support Linux & MacOS?

__Perhaps it's a silly question, forgive me I'm very new to React-Native!__  

* But, how possible would it be to support MacOS & Linux with this library? 

* Is it even possible & why not (if not)? 

* How much work would it involve?

**Comment by vonovak** [comment]
Hello and thanks for asking,
supporting mac should be possible with https://github.com/microsoft/react-native-macos but for linux, RN doesn't really have good support AFAIK.
If someone contributes the macOS support and is able to commit to support it at least in midterm, I'd merge it but doing it myself is, unfortunately, out of my time abilities.
Thank you 🙂

**Comment by josh-thompson13** [comment]
Are there any future plans to support macos?
