### ISSUE TITLE
compilation failed for android,  variable activityContext declaration

### ISSUE THREAD

**Issue by ravin-amplework** [react-native-datetimepicker/datetimepicker#687]
# Bug report

Summery
local variable activityContext is accessed from within inner class; needs to be declared final

## Reproducible sample code
node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:67: error: local variable activityContext is accessed from within inner class; needs to be declared final
        int textColorPrimary = getDefaultDialogButtonTextColor(activityContext);
                                                               ^
1 error

FAILURE: Build failed with an exception.

## Steps to reproduce
yarn android

1. …
2. …

Describe what you expected to happen:

1. compile android

## Environment info
  "react": "18.1.0",
   "react-native": "0.68.2",

`npx react-native info` output:

```bash
# paste it here
```

Time zone name (If the problem you have is related to unexpected time / date. See list in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

datetimepicker version: 6.5.4

iOS / Android version: 11
![image](https://user-images.githubusercontent.com/81961373/199915699-2655ead2-7590-4974-9005-896eefac2db1.png)

**Comment by ravin-amplework** [comment]
updating from this line worked for me --
 node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:67:

	public static DialogInterface.OnShowListener setButtonTextColor(@NonNull Context activityContext, final AlertDialog dialog) { 

TO

	public static DialogInterface.OnShowListener setButtonTextColor(@NonNull final Context activityContext, final AlertDialog dialog) {

**Comment by vikcodes** [comment]
Faced same issue using latest version of this package: ^6.7.0, had to downgrade to ^5.1.0 in order for the Android build to work

Using react-native: 0.64.0

**Comment by ravin-amplework** [comment]
> Faced same issue using latest version of this package: ^6.7.0, had to downgrade to ^5.1.0 in order for the Android build to work
> 
> Using react-native: 0.64.0

just put  this code if error is same it will work  untill we get latest update with this fix.

**Comment by jonshaw199** [comment]
Really need a permanent solution for our automated builds 🙏

**Comment by tsachit** [comment]
> updating from this line worked for me -- node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:67:
> 
> ```
> public static DialogInterface.OnShowListener setButtonTextColor(@NonNull Context activityContext, final AlertDialog dialog) { 
> ```
> 
> TO
> 
> ```
> public static DialogInterface.OnShowListener setButtonTextColor(@NonNull final Context activityContext, final AlertDialog dialog) {
> ```

This is still an issue, thanks to this solution i can make a build but do we have permanent solution for this?

```
> Task :react-native-community_datetimepicker:compileReleaseJavaWithJavac FAILED
/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/Common.java:76: error: local variable activityContext is accessed from within inner class; needs to be declared final
        int textColorPrimary = getDefaultDialogButtonTextColor(activityContext);
                                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```
