### ISSUE TITLE
I think Martin is asking if it's possible to only see the years. He doesn't have a solution.

### ISSUE THREAD

**Issue by anandstephan** [react-native-datetimepicker/datetimepicker#690]
I think Martin is asking if it's possible to only see the years. He doesn't have a solution.

_Originally posted by @Thembelani in https://github.com/react-native-datetimepicker/datetimepicker/issues/23#issuecomment-563943476_

**Comment by vonovak** [comment]
Hello and thanks for asking,
if you want to pick years only, use https://github.com/react-native-picker/picker
Thank you 🙂
