### ISSUE TITLE
Possibility of a modal picker in ios

### ISSUE THREAD

**Issue by johannesfau** [react-native-datetimepicker/datetimepicker#697]
Hey Johannes here,

is it possible to have just a modal picker in ios without the interim button? I would like to press on a Touchable Opacity in iOs and open the picker directly but i find no way how to do it.

Best regards
Johannes

**Comment by ThanhNam20** [comment]
Same issue, any update ?

**Comment by kerimylcn** [comment]
Hello everyone,

When I build with version 4.0.0, there is such an image on the normal device. There is no problem in the simulator, it's normal.

![WhatsApp Image 2022-10-27 at 17 37 02](https://user-images.githubusercontent.com/30003114/203790624-2d37acff-1b78-4f25-ace3-06aa767530f5.jpeg)

**Comment by vonovak** [comment]
Hello and thanks for reporting,
hello, yes, you can build this the following way:

- create a Touchable button
- upon pressing it, present a modal
- in the modal, render `<DateTimePicker />` with `display={'inline'}`

Thank you 🙂

**Comment by johannesfau** [comment]
Great thanks!!!
