### ISSUE TITLE
neutralButton not showing up

### ISSUE THREAD

**Issue by DianaKoenraadt** [react-native-datetimepicker/datetimepicker#712]
I've supplied the `neutralButton` prop but no button is showing up.

I'm using version 6.7.1

**Comment by DianaKoenraadt** [comment]
Also, `positiveButton` and `negativeButton` don't work. They always keep the default text value and color, regardless of props passed in.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I cannot reproduce the problem. Please note that the prop is android-only.
Thank you 🙂

![Screenshot_20230123_125950](https://user-images.githubusercontent.com/1566403/214034670-aa4a05a4-2848-428e-a8f8-73b1b7ec6b38.png)
