### ISSUE TITLE
[react-native-windows] Unable to override WindowsTargetVersion

### ISSUE THREAD

**Issue by NikhiRaya** [react-native-datetimepicker/datetimepicker#713]
On windows 11, DateTimePicker vcxproj defaults the WindowsTargetVersion to 10.0.18382 if no WindowsTargetVersion is specified. We are not able override it with a particular WindowsTargetVersion we are currently using in the parent project (where we use the DateTimePicker as a npm dependency).

**Comment by vonovak** [comment]
closed via https://github.com/react-native-datetimepicker/datetimepicker/pull/714
