### ISSUE TITLE
Is there anyway to change the appearance of the button ?

### ISSUE THREAD

**Issue by Helyios** [react-native-datetimepicker/datetimepicker#718]
Hi everyone,

Is there anyway to change the appearance of the button when setting the mode to "compact" ? I would like to create a custom button that displays an icon and the date which would open the date picker.

Or perhaps there is a way to open the date picker programmatically ? I've tried the solution from [issue #483](https://github.com/react-native-datetimepicker/datetimepicker/issues/483) which basically makes the date text button invisible through `opacity:0` but it's not pretty at all and kills the purpose of `<TouchableOpacity />`

Thank you in advance,

**Comment by vonovak** [comment]
Hello and thanks for asking,
I'm not aware of a way to style the component provided by apple beyond what the module already exposes.
Thank you 🙂
