### ISSUE TITLE
Add support for a more accessible datetimepicker in android

### ISSUE THREAD

**Issue by yalnader** [react-native-datetimepicker/datetimepicker#721]
# Feature request
I am working in a group for a university project using React Native for a mobile application. We currently require the datetimepicker so that users of our application can select their birthdate. However, they have pointed out that the year is not accessible. After doing research, there doesn't appear to be a way to implement an inline method (as is possible with iOS) or a way to show the Year date scroller first. Is there possibly a way to show the year option first for the date mode? If not, we were wondering if an inline version could be developed similar to the one for iOS, or have a way to show the inline version for android.

## Why it is needed

After doing a pilot study at our schools hospital, we received feedback that the date time picker on android is not accessible, and users found it difficult to change the year.

![image](https://user-images.githubusercontent.com/40676121/217692553-774da24f-826e-48aa-8c1b-6af5dc144677.png)
![image](https://user-images.githubusercontent.com/40676121/217692567-74619dea-63f1-4756-a69a-63b9fcee87da.png)
  

## Possible implementation

If possible it would be nice to have a similar inline option for the datetimepicker like IOS for user accessibility.
![image](https://user-images.githubusercontent.com/40676121/217693093-ef9c980a-73b8-4186-98eb-695bd6809231.png)

### Code sample

<DateTimePicker
    display="inline"
    mode="date"
    value={new date()}
    onChange={examplefunction}
/>

**Comment by AdnanNuruddin** [comment]
Hi, you can change the display to "spinner" for iOS like date picker.

**Comment by yalnader** [comment]
Thank you seems I have skipped over that when I was going through documentation.

**Comment by mehdinourollah** [comment]
> Hi, you can change the display to "spinner" for iOS like date picker.

When I do that it crashes all of a sudden
