### ISSUE TITLE
[iOS/iPadOS] - `themeVariant` property not fully applied on `datetime` picker

### ISSUE THREAD

**Issue by coolersham** [react-native-datetimepicker/datetimepicker#725]
# Bug report

## Summary

When using the `RNDateTimePicker` on iOS/iPadOS in `datetime` mode, while overwriting the `display` and `themeVariant` as shown below the time picker popover is not receiving the correct theming.

![issue](https://user-images.githubusercontent.com/123668138/218836714-28e80c9e-049f-46df-8935-a0f1dcfb28ff.jpeg)

## Reproducible sample code

```
import React from "react"

import { View } from "react-native"
import RNDateTimePicker from "@react-native-community/datetimepicker"

export default function App(): JSX.Element {
  return (
    <View
      style={{
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "white",
      }}
    >
      <RNDateTimePicker
        display={"inline"}
        mode={"datetime"}
        value={new Date()}
        themeVariant={"light"}
      />
    </View>
  )
}
```

## Steps to reproduce

1. Create a new `react-native` app with the help of the CLI (template)
1. Install this package and all other required dependencies via npm, yarn, etc.
1. Install pods and build the iOS/iPadOS application on a device
1. Paste the provided reproducible code into the correct file
1. Save and try to perceive the issue

### Describe what you expected to happen:

The time picker popover should also be overwritten by the specified `themeVariant` property.

## Environment info

react-native version: 0.71.3
datetimepicker version: 6.7.5
iOS / iPadOS version: 15.X and 16.X

... other version info is not relevant for this issue.

**Comment by mykelFITLG** [comment]
@coolersham same here

**Comment by vonovak** [comment]
Hello and thanks for reporting,
the uidatepicker exposes public api to control the themeVariant and we use that. If that doesn't work, that, unfortunately, is out of our control and you can report that to apple.

Did you try using the recommended package mentioned in the readme? https://github.com/react-native-datetimepicker/datetimepicker#themevariant-optional-ios-only

Thank you 🙂

**Comment by coolersham** [comment]
@vonovak yes, I did set the `themeVariant` to `light` however it seems like it is not applied correctly to the `UIDatePicker` either by you or on the side of Apple. I am not fully aware of the conventions of open-source packages, but wouldn't reporting such a case to Apple be in the best interest of the main devs of the package?

Anyway, I am using your package now to get around this issue and would like to compliment you on that one. Easy to use and works like a charm! Thanks!

**Comment by vonovak** [comment]
@coolersham as I said, we use apple's public api and controlling the `themeVariant` works for the spinner mode so I believe the bug is on Apple's side. 

>  I am not fully aware of the conventions of open-source packages, but wouldn't reporting such a case to Apple be in the best interest of the main devs of the package?

Well, sure, having the case reported would be in the best interest of the entire dev community, me included. Personally, I was not aware of the problem before.

> Anyway, I am using your package and would like to compliment you on that one.

Thank you. Happy that it helped. Forgive me that I'll ask so openly but as you probably noticed, the package is intended for my sponsors only. I may have missed something but I'm not aware of you / someone else becoming my new sponsor recently. As a sign of thanks, would you be so kind and sponsor me? The sponsorships help me maintain libraries for react native.

Thank you

**Comment by coolersham** [comment]
> Thank you. Happy that it worked and that it helped. Forgive me that I'll ask so openly but as you probably noticed, the package is intended for my sponsors only. I may have missed something but I'm not aware of you / someone else becoming my new sponsor recently. As a sign of thanks, would you be so kind and add the sponsorship? The sponsorships help me maintain libraries for react native.

@vonovak Honestly, I was not aware that the package is a Sponsorware because I skipped that part in the `README` and went straight for the `npm` package (is that common practice to provide such 'licenced' projects like that publicly?). Unfortunately, I cannot go with such a decision so I sadly have to remove and discontinue using your package. Thanks for letting me know!

**Comment by vonovak** [comment]
> I skipped that part in the README and went straight for the npm package

interesting, and how did you find the npm package?

**Comment by coolersham** [comment]
@vonovak it seems like you pushed it to the `npm` registry --> [@vonovak/react-native-theme-control](https://www.npmjs.com/package/@vonovak/react-native-theme-control).

As you published it publicly it is available to the public.

**Comment by vonovak** [comment]
> @vonovak it seems like you pushed it to the `npm` registry 

yes, I'm well aware. What I'm asking how you found it in the readme?

**Comment by coolersham** [comment]
> yes, I'm well aware. What I'm asking how you found it in the readme?

I did not, I just searched for it on npm :D

**Comment by vonovak** [comment]
So the idea is that if you skim over the public readme, you'll notice there are no installation instructions, and no usage docs. Those are available to sponsors only and I put the package out there in good faith that people would appreciate it and value the time that I had spent on it.

Gotta love open source 🤷‍♂️ 😅
