### ISSUE TITLE
[iOS/iPadOS] - `locale` property not fully applied on `datetime` picker translations

### ISSUE THREAD

**Issue by coolersham** [react-native-datetimepicker/datetimepicker#726]
# Bug report

## Summary

When using the `RNDateTimePicker` on iOS/iPadOS in `datetime` mode, while overwriting the `locale` with a supported local code and `display` with `inline` the `Time` label does not change its language.

![issue](https://user-images.githubusercontent.com/123668138/218836714-28e80c9e-049f-46df-8935-a0f1dcfb28ff.jpeg)

## Reproducible sample code

```
import React from "react"

import { View } from "react-native"
import RNDateTimePicker from "@react-native-community/datetimepicker"

export default function App(): JSX.Element {
  return (
    <View
      style={{
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "white",
      }}
    >
      <RNDateTimePicker
        locale={"es"}
        display={"inline"}
        mode={"datetime"}
        value={new Date()}
        themeVariant={"light"}
      />
    </View>
  )
}
```

## Steps to reproduce

1. Create a new `react-native` app with the help of the CLI (template)
1. Install this package and all other required dependencies via npm, yarn, etc.
1. Install pods and build the iOS/iPadOS application on a device
1. Paste the provided reproducible code into the correct file
1. Save and try to perceive the issue

### Describe what you expected to happen:

The label displayed for the time picker anchor (stating `Time`) should react to the configured `locale` property.

## Environment info

react-native version: 0.71.3
datetimepicker version: 6.7.5
iOS / iPadOS version: 15.X and 16.X

... other version info is not relevant for this issue.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
in the docs https://github.com/react-native-datetimepicker/datetimepicker#locale-optional-ios-only we state clearly that the prop does not work reliably. This is a bug with apple, not us.


Thank you 🙂
