### ISSUE TITLE
iOS value always reverting to today

### ISSUE THREAD

**Issue by jlag34** [react-native-datetimepicker/datetimepicker#727]
```
import React, { useState } from 'react';
import { Button, View, Text } from 'react-native';
import DateTimePickerModal from 'react-native-modal-datetime-picker';
import moment from 'moment';

const Example = () => {
  const [selectedDate, setSelectedDate] = useState();
  const [isDatePickerVisible, setDatePickerVisibility] = useState(false);

  const showDatePicker = () => {
    setDatePickerVisibility(true);
  };

  const hideDatePicker = () => {
    setDatePickerVisibility(false);
  };

  const handleConfirm = (date) => {
    setSelectedDate(date);
    hideDatePicker();
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>{`Date:  ${selectedDate? moment(selectedDate).format("MM/DD/YYYY"):"Please select date"}`}</Text>
      <Button title="Show Date Picker" onPress={showDatePicker} />
      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        value={selectedDate}
      />
    </View>
  );
};

export default Example;
```

Using the above code as an example you can see that any time I pick a date and reopen the picker, it reverts to today instead of the date I selected. To test quickly go to this link and just copy and paste my code (I took 99% of the code from this link, just added the value prop)

https://snack.expo.dev/@ahmetbasdan/react-native-modal-datetime-picker-example?platform=ios

Expected result:

When I select a date and reopen the picker, I want the selected date to be the date selected in the spinner/calender

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Please follow the issue template and open a new issue if the problem persists.

Namely, the problem needs to be reproducible with @react-native-community/datetimepicker, not some other library.
It's also not clear what platform and versions this is on.

Thank you 🙂
