### ISSUE TITLE
DateTimePicker is not working in Expo App for iOS

### ISSUE THREAD

**Issue by anishpatelyaadada** [react-native-datetimepicker/datetimepicker#733]
# Bug report
The date and time picker modal is not working in the expo app on iOS devices and throwing errors related to **constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.**

On Android, it's working great. 

## Reproducible sample code

I used the example sample code provided in the documentation. 

## Steps to reproduce

1. create a new react native expo project
2. install the library using the command **expo install @react-native-community/datetimepicker**
3. copy the sample code provided as example.

Describe what you expected to happen:

1. date and time modal is not working in iOS

## Environment info

datetimepicker version: 6.5.2
expo: ~47.0.9
iOS / Android version: 16.3/13

**Comment by mhazizk** [comment]
I also experience this problem. Is there any way to make it work on iOS?

**Comment by 20chad16** [comment]
Any fix for this?

**Comment by anishpatelyaadada** [comment]
The issue is solved if i warp with <View></View> in my case. Thanks

**Comment by Hassaan68** [comment]
> The issue is solved if i warp with in my case. Thanks

hi @anishpatelyaadada , can you please post the solution here? I am facing the same issue
