### ISSUE TITLE
Unable to launch the example app both iOS and android

### ISSUE THREAD

**Issue by wood1986** [react-native-datetimepicker/datetimepicker#741]
# Bug report

## Summary

Unable to launch the example app both iOS and android. 

![image](https://user-images.githubusercontent.com/5212215/226253565-0396e4ce-e2fe-4a56-8793-9c1d53d8fb0d.png)
![image](https://user-images.githubusercontent.com/5212215/226256444-e4618fc3-f769-4a05-9afe-c2286e525450.png)

## Reproducible sample code

just clone this repo

## Steps to reproduce

1. git clone https://github.com/react-native-datetimepicker/datetimepicker.git
2. yarn
3a. yarn start
3b. yarn start:ios
3b. yarn start:android

Describe what you expected to happen:

should launch the example

## Environment info

`npx react-native info` output:

```bash
System:
    OS: macOS 12.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 644.66 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.9.0/bin/yarn
    npm: 8.19.4 - ~/Desktop/datetimepicker/node_modules/.bin/npm
    Watchman: 2023.02.20.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/wood/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Time zone name (If the problem you have is related to unexpected time / date. See list in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

datetimepicker version: 7.0.0

iOS / Android version: x.x

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 7.2.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
