### ISSUE TITLE
positiveButtonLabel, negativeButtonLabel and neutralButtonLabel are deprecated.Use positive / negative / neutralButton prop instead. 

### ISSUE THREAD

**Issue by Akilramki** [react-native-datetimepicker/datetimepicker#743]
# Bug report

neutralButtonLabel are deprecated
 
        <DateTimePicker
          testID="date"
          value={date}
          mode={mode}
          is24Hour={true}
          onChange={onChange}
          maximumDate={new Date()}
         neutralButtonLabel={Strings.Reset}
/>

    "react": "18.2.0",
    "react-native": "0.71.4",
    "@react-native-community/datetimepicker": "^7.0.0",

**Comment by vonovak** [comment]
Hello,
please see https://github.com/react-native-datetimepicker/datetimepicker#neutralButton-optional-android-only
Thank you 🙂
