### ISSUE TITLE
Expo and Android: not using `developmentClient` with `eas build` makes `datetimepicker` spinner dark

### ISSUE THREAD

**Issue by newfylox** [react-native-datetimepicker/datetimepicker#746]
### Summary

Building app with `eas.json` without `developmentClient` and using library `@react-native-community/datetimepicker` with `display="spinner"` on Android and not touching at any code, modal becomes darker even if using `userInterfaceStyle: "light"` in `app.json`

with `developmentClient: true`
<img src="https://user-images.githubusercontent.com/3361669/229196415-05c147a5-91df-470a-a062-c8e919321b23.jpg" width=50%>

without `developmentClient`
<img src="https://user-images.githubusercontent.com/3361669/229196539-e0663314-ef86-448a-bef9-66eeb1ada04c.jpg" width=50%>

### Managed or bare?

managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.1 (Vera)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ^48.0.7 => 48.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

working eas.json
```json
{
  "build": {
    "development": {
      "channel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    }
  }
}
```

not working eas.json or even on production build
```json
{
  "build": {
    "development": {
      "channel": "development",
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    }
  }
}
```

same piece of code
```jsx
import DateTimePicker from "@react-native-community/datetimepicker"; // version 6.7.3 or even newer 7.0.0
...
<DateTimePicker
  testID="dateTimePicker"
  value={date}
  mode="date"
  locale={locale}
  display={"spinner"}
  is24Hour={false}
  onChange={onChange}
/>
```

**Comment by vonovak** [comment]
Hello and thanks for asking,
Expo dev client probably adds some theme-related code that influences the appearance in development (light mode is set), while in production, the date picker should follow the system settings.

It so happens that I have published a package that allows you to control the theme of the app: https://github.com/vonovak/react-native-theme-control

I'm quite sure it should be able to force the light (or dark) theme in your app, in production.
Please note that you need to sponsor me here on github to access the package 🙂.

I'm going to close the issue because I believe it is expo-related.

Thank you 🙂

**Comment by sharathbangera6** [comment]
@newfylox is this fixed ? Are u able to see System Set theme in calendar? For me it always shows light colors irrespective of the system theme both in production as well as local.
