### ISSUE TITLE
Error: SyntaxError unexpected Token on Android

### ISSUE THREAD

**Issue by Coffeegerm** [react-native-datetimepicker/datetimepicker#752]
error: SyntaxError: D:\user\app\node_modules@react-native-community\datetimepicker\src\DateTimePickerAndroid.js: Unexpected token, expected "]" (97:42)

error: SyntaxError: D:\user\app\node_modules@react-native-community\datetimepicker\src\androidUtil.js: Unexpected token, expected "]" (97:42)

95 | }
96 |

97 | function dismiss(mode: AndroidNativeProps['mode']) {
| ^
98 | // $FlowFixMe - AbstractComponent [1] is not an instance type.
99 | pickers[mode].dismiss();
100 | }

version:
"@react-native-community/datetimepicker": "^7.0.1",
"react-native-modal-datetime-picker": "^15.0.0",
"react-native": "0.68.5",

This was a previously mentioned issue as seen [here](https://github.com/react-native-datetimepicker/datetimepicker/issues/603). With the recommended steps being either upgrade to react native > 0.66 or use patch package to correct the package locally.

However even upgrading past 0.66 doesn't just fix the issue and i have had to use patch package still to get things running.

**Comment by Coffeegerm** [comment]
Thanks @vonovak I believe the fix we needed was bumping up the following packages for babel from these versions

```
"@babel/core": "^7.8.4",
"@babel/runtime": "^7.12.5",
```

to 

```
"@babel/core": "^7.20.0",
"@babel/runtime": "^7.20.0",
```

as the upgrade helper shows react-native moving to these versions in 71.

Does this package have any plans to move from Flow to TS considering the announcement of TS first for react native with the announcement for 71?

**Comment by vonovak** [comment]
@Coffeegerm it is possible that the babel packages have to be bumped too, perhaps it was the babel plugin that removes flow types from code.

As for TS, I'd love to have this lib written in TS but it's not going to happen without external contribution / financial sponsors (wanna become one? 😉).

There's no major change with RN 71 and TS - TS types were moved from the definitely typed repo to react native repo and that's it. The core code base itself is still written in flow. It's not a major change for the ecosystem 🙂

**Comment by Coffeegerm** [comment]
I'd love to try and contribute by moving this package over to TS! I've been trying to find ways to contribute in the open source world!

**Comment by vonovak** [comment]
Amazing, please feel free to give it a go! 🙂

**Comment by vonovak** [comment]
Would be nice if the setup was the same as when you create a new library using https://github.com/callstack/react-native-builder-bob

You can look at my package react native theme control for inspiration - it uses the builder bob package too and the setup is pretty much the same 🙂
