### ISSUE TITLE
Android locale property

### ISSUE THREAD

**Issue by KMathisGit** [react-native-datetimepicker/datetimepicker#755]
# Feature request

Add a `locale`  property for android, much like what is available for ios.

**Note:** This feature has been requested multiple times in past but all requests were closed because of v5.0.0 release where the `locale` prop was removed for ios devices - but `locale` prop was added back in v5.1.0.

## Why it is needed

Common use-case to want to toggle an app into a different language, without changing the actual device language.

## Possible implementation

Expose a new prop for `<DateTimePicker />` component that accepts a locale string and will render android calendar using specified locale (if valid).

### Code sample

```
<DateTimePicker
  value={datePickerVal}
  mode={"date"}
  onChange={handleChange}
  locale={"en-US"}
/>
```

**Comment by vonovak** [comment]
Hello and thanks for asking,
the PRs that added the functionality were closed because there's a good reason not to handle locale changing on the prop level on Android: https://github.com/react-native-datetimepicker/datetimepicker/pull/736#issuecomment-1474452930
Thank you 🙂
