### ISSUE TITLE
IOS is crashing

### ISSUE THREAD

**Issue by AndonMitev** [react-native-datetimepicker/datetimepicker#759]
Stack:

`"@react-native-community/datetimepicker": "6.7.3",`
`"react-native": "0.71.7"`
`"expo": "~48.0.15",`

Application is just crashing on iOS simulator and physical. No problem with android so far. Any suggestions what could resolve the issue

And this is the code that i'm using:
```
<HStack alignItems="center" justifyContent="space-between" bgColor="muted.50" px={2} height={50} borderRadius={12}>
    <Text color="textdark.tertiary" fontSize={12}>
      Date of birth*
    </Text>
    <RNDatePicker
      value={value ? new Date(parseInt(value)) : new Date()}
      onChange={(event) => {
        if (event.type === 'dismissed') {
          return;
        }
        const timestampAsStr = event.nativeEvent.timestamp?.toString() ?? '';

        setValue('dateOfBirthTS', timestampAsStr);
      }}
    />
  </HStack>
  ```

**Comment by RyanGst** [comment]
i'm having a similar issue, preventing re-renders on the component (in my case, memoizing the `value` prop) helped. **I haven't fix this issue yet.**

two things may help:

1 - [datetimepicker version should be at least 7.0.1 to be used with RN 0.70+](https://github.com/react-native-community/datetimepicker/compare/v7.0.0...v7.0.1)
2 - [Base options typing was updated on e3c05a8](https://github.com/react-native-datetimepicker/datetimepicker/blob/73db785c6540a2ff65eb5b4f9aa43d9bb0430eed/src/index.d.ts#L26)
