### ISSUE TITLE
Auto open component and invisible field on Android phones.

### ISSUE THREAD

**Issue by muhammadawais05** [react-native-datetimepicker/datetimepicker#760]
I am working on a React native app. I am using @react-native-community/datetimepicker for selecting a date. I have used this component on the ApplyLeave screen. Whenever the ApplyLeave screen component renders, the date time picker automatically pops up. The second issue is, when I close that pop-up modal, the datetimepicker field is not visible. I am facing these issues only on Android phones. It is working as intended on iPhones. Can you help me in this regard?

Here is the code for DateTimePicker:

<DateTimePicker
  mode="date"
  autoOpen={false}
  value={new Date(leaveEndDate)}
  onChange={handleEndDateChange}
  minimumDate={new Date(leaveStartDate)}
/>

Note:
I have also set the autoOpen={false} but it does not fix the auto-open issue on Android phones. 

<img width="317" alt="Screenshot 2023-05-22 at 4 32 28 PM" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/65153732/2ce3da4a-94d7-44b6-984d-4a99f36b4aab">

**Comment by IcemenUa** [comment]
the same issue happens only on android

**Comment by betocolon23** [comment]
I have this issue as well. Did you fix it?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
please have a look at the screenshots: https://github.com/react-native-datetimepicker/datetimepicker#screenshots

we currently don't have an "inline" version of the date picker on Android. This feature request is tracked here https://github.com/react-native-datetimepicker/datetimepicker/issues/14
Thank you 🙂
