### ISSUE TITLE
DateTimePicker is not showing in React Native Expo application. TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.dismiss')].

### ISSUE THREAD

**Issue by MilicaLicinar97** [react-native-datetimepicker/datetimepicker#763]
I am using DateTimePicker from @react-native-community/datetimepicker, but DateTimePicker is not showing in my application. I followed steps how to use it, but still nothing.
I got warning something like: [Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.dismiss')].

Here is the code:

```
import { useState } from "react";
import { Button, Platform, StyleSheet, Text, View } from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";

const AddInterviewDateScreen = () => {
    const [date, setDate] = useState(new Date());
    const [showPicker, setShowPicker] =  useState(false);


    return ( 
        <View>
            <DateTimePicker
                testID="dateTimePicker"
                mode="date"
                display={Platform.OS == 'ios' ? "inline" : "default"}
                value={date}
                style={{width:200, height:200}}
                
            />
        </View>
     );
}
```

 I am starting my application with expo start --dev-client and then I scan QR code that is generated in terminal of visual code with Expo Go on my phone.

I expect that I can see DateTimePicker after starting application and that I can set date and time on it, but DateTimePicker is not showing.

Versions:
  "expo": "^47.0.14",
 "react-native": "0.70.8"
"typescript": "^5.0.4",
 "@react-native-community/datetimepicker": "6.5.2"

**Comment by vonovak** [comment]
Hello and thanks for reporting,
to me, this sounds like you didn't build the android project after installing the dependency, but can't say for sure without a repro.
Thank you 🙂

**Comment by vonovak** [comment]
just for the record, this is what I get when I copy your code :)

![Screenshot_1686691348](https://github.com/react-native-datetimepicker/datetimepicker/assets/1566403/50a1ce6f-c240-48e8-9651-08dc4bbf987e)
