### ISSUE TITLE
gradle getExtOrIntegerDefault question

### ISSUE THREAD

**Issue by ArcherLucky** [react-native-datetimepicker/datetimepicker#766]
# Question

`def getExtOrIntegerDefault(name) {
    return rootProject.ext.has(name) ? rootProject.ext.get(name) : (project.properties['ReactNativeDateTimePicker_' + name]).toInteger()
}`

can you give a int default value? for now, I must added some properties for sdk version

**Comment by vonovak** [comment]
Hello and thanks for asking,
yes, you can use the `ReactNativeDateTimePicker_` prefix to specify a value that is different from the default one, but I don't imagine it should be necessary.

Thank you 🙂
