### ISSUE TITLE
Add AM/PM restriction to DateTimePicker

### ISSUE THREAD

**Issue by cewidiupleek** [react-native-datetimepicker/datetimepicker#770]
Feature that allows for restricting the time of day to either AM or PM.

This feature would be particularly useful in scenarios where an app has different behaviors or functionalities based on the time of the day. For example, a restaurant reservation app might only allow bookings for breakfast in the AM and dinner in the PM. 

New prop: timeOfDayRestriction accepts 'AM', 'PM', or 'none' (default)

**Comment by vonovak** [comment]
Hello and thanks for asking,
unfortunately, the underlying native components we use here don't support this. We'd need to build new components on top of https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker to allow this.

That's only possible if there's strong backing (which there's not), see https://github.com/react-native-datetimepicker/datetimepicker/issues/313


Thank you 🙂
