### ISSUE TITLE
Is it it anyhow possible to style the button on which one presses to open the actual datetime picker? 

### ISSUE THREAD

**Issue by zlobizlobi** [react-native-datetimepicker/datetimepicker#771]
# Question

Is it it anyhow possible to style the button on which one presses to open the actual datetime picker? 

![Screenshot 2023-06-19 at 14 35 27](https://github.com/react-native-datetimepicker/datetimepicker/assets/40123953/3d8048af-1024-42b8-a58f-5d80c95c0854)

For my use case, I need to get rid of the slight grey, default background of the button and introduce just a pressable text. I've tried using the `style` prop but to no avail.

**Comment by vonovak** [comment]
Hello and thanks for asking,
unfortunately, it's not possible.

Thank you 🙂
