### ISSUE TITLE
Using TWO Date Time Pickers Doesn't Work?

### ISSUE THREAD

**Issue by eatanga-git** [react-native-datetimepicker/datetimepicker#775]
# Bug report
 

## Summary

I am trying to use two different date time pickers. I want it to be that the user can select a range i.e choose the beginning date, then choose the ending date.
However, it is glitching up. The 2nd datepicker works fine. But the first one does not change the date onChange. The button for the first one stops working as well. And lastly, if I open the first picker first, the 2nd picker will no longer work correctly - the date will keep in resetting before closing it.

## Reproducible sample code
    export default function CurrentPage( {stockname, stocksymbol}) {
 
  
        //console.log(stockname);
         console.log(stocksymbol, "wow");
       
        
        const [mode, setMode] = useState('date');
      
        const [date, setDate] = useState(new Date());
        const [prevDate, setPrevDate] = useState((function(d){ d.setDate(d.getDate()-1); return d})(new Date));
      
        const [show, setShow] = useState(false);
        const [showPrev, setShowPrev] = useState(false);
      
      
         const prevOnChange = (event, prevselectedDate) => {
          const newDate = prevselectedDate;
          console.log(event.type, event)
          setPrevShow(false);
          setPrevDate(newDate);
        }; 
        
        const onChange = (event, selectedDate) => {
          const newDate = selectedDate;
          setShow(false);
          setDate(newDate);
        };
      
        const showModePrev = (currentMode) => {
          setShowPrev(true); 
        };
        const showMode = (currentMode) => {
          setShow(true); 
        };
      
       
        const showPrevDatepicker = () => {
          showModePrev('date');
        };
        const showDatepicker = () => {
          showMode('date');
        };
      
        const startDate = prevDate.toLocaleDateString('fr').replace(/\b(\d)\b/g, '0$1')
        const endDate = date.toLocaleDateString('fr').replace(/\b(\d)\b/g, '0$1')
        
        console.log(prevDate, startDate)
        console.log(date, endDate)
        
       <SafeAreaView s>
         
            {/*The Datepicker*/}
            <View > 
              <Pressable onPress={()=> showPrevDatepicker() } > 
                <Text > {startDate} </Text> 
              </Pressable>
              <Pressable   > 
                <Text style ={localStyles.datePickerText}>Update</Text> 
              </Pressable>  
              <Pressable onPress={()=> showDatepicker()} > 
                <Text> {endDate} </Text> 
              </Pressable>

              {show && (
                <DateTimePicker
                  testID="dateTimePicker"
                  dateFormat="dayofweek day month"
                  display={"spinner"}
                  value={date}
                  mode={mode}
                  is24Hour={true}
                  onChange={onChange} 
                />
              )}

              {showPrev && (
                <DateTimePicker
                  testID="dateTimePicker"
                  dateFormat="dayofweek day month"
                  display={"spinner"}
                  value={prevDate}
                  mode={mode}
                  is24Hour={true}
                  onChange={prevOnChange }
                />
              )}
              
         </SafeAreaView>

}

## Steps to reproduce

Hopefully just running the above code will work. 

I just expected each date time picker to work normally: I press the button to open the picker, chose the date, and the picker will close with the date updated on the button.
 

## Environment info
  
 
"expo": "^46.0.0",
datetimepicker version: 6.1.2
 
react: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
react-native-windows: Not Found

**Comment by vonovak** [comment]
Hello and thanks for reporting,
this doesn't appear to be a runnable repro, what is `localStyles.datePickerText`? Please add everything to make this runnable, thank you.
What platform do you see this on?
Thank you 🙂
