### ISSUE TITLE
Native module RNDatePicker tried to override RNDatePicker

### ISSUE THREAD

**Issue by wmonecke** [react-native-datetimepicker/datetimepicker#787]
# Bug report

## Summary

Installing react-native-datetimepicker on a new project with latest react-native (`"react-native": "0.72.1"`) fails with the following error: 

<img width="315" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/24256469/f27c6490-9338-4f41-82a1-c99c5ccdc1b0">

This started happening after doing a `./gradlew clean` after installation

I am unable to remove it from the `getPackages` method because libs don't show there any longer.

Any ideas?

## Environment info

`npx react-native info` output:

```bash
System:
  OS: macOS 13.0.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 139.02 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.8.0
    path: ~/.nvm/versions/node/v16.8.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v16.8.0/bin/npm
  Watchman:
    version: 2023.04.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/wmonecke/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/wmonecke/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by havoanhnguyen** [comment]
same issue. 
"react-native": "0.71.12",

**Comment by adarsh1pandey** [comment]
I am getting the same issue

**Comment by adarsh1pandey** [comment]
SomeOne please help

**Comment by wmonecke** [comment]
I solved the issue.

Please check out my answer here: https://stackoverflow.com/a/76679079/7323010

**Comment by havoanhnguyen** [comment]
I solved the problem, in my package.json there are 2 dependencies `'@react-native-community/datetimepicker'` and `'react-native-date-picker'`, I think they try to overwrite each other. Remove one of them., problem solved

**Comment by allanfael** [comment]
> I solved the problem, in my package.json there are 2 dependencies `'@react-native-community/datetimepicker'` and `'react-native-date-picker'`, I think they try to overwrite each other. Remove one of them., problem solved

Thanks for save my life

**Comment by PiusLucky** [comment]
> I solved the problem, in my package.json there are 2 dependencies `'@react-native-community/datetimepicker'` and `'react-native-date-picker'`, I think they try to overwrite each other. Remove one of them., problem solved

Thank you. We should get a coffee sometime. :) ✅🔥🔥🔥
