### ISSUE TITLE
jest/setup.js is empty

### ISSUE THREAD

**Issue by douglasjunior** [react-native-datetimepicker/datetimepicker#788]
# Bug report

## Summary

Why the `jest/setup.js` file was empty in this commit?

https://github.com/react-native-datetimepicker/datetimepicker/commit/a34f667cce4157d3676be975e33a67976424a030#diff-759a02c8fa99d555891bb2a2d3ae2495a2295dc1e1183dc8ba6281b0e172208a

## Reproducible sample code

Just try to import jest/setup.js file and nothing happens.

## Steps to reproduce

N/A

## Environment info

datetimepicker version: 7.4.0

**Comment by vonovak** [comment]
Hello and thanks for asking,
there used to be some code there but it was no longer needed and so the code was removed, but the file was kept so that it doesn't break people who were consuming it.

It can be removed from the repo for sure, with a new major bump.
Thank you 🙂

**Comment by douglasjunior** [comment]
Nice, thank you!
