### ISSUE TITLE
No Cancel or Ok button on IOS

### ISSUE THREAD

**Issue by MrFarhan** [react-native-datetimepicker/datetimepicker#802]
# Bug report

## Summary

I can not find any Ok or Close buttons for IOS where on the other hand those buttons are available on Android.

I don't understand why there are buttons for Android and not for IOS ?

If there are buttons then it should be available for both not just Android.

## Steps to reproduce

Use the package for Android and IOS, you will see the difference.

## Describe what you expected to happen:

The default functionality should be same for both Android and IOS, there should be a Ok and Cancel button for IOS as like in the Android.

**Comment by vonovak** [comment]
Hello and thanks for asking,
the iOS components do not have cancel and okay button out of the box, which is why they are not rendered. 
you can try https://github.com/mmazzarolo/react-native-modal-datetime-picker
Thank you 🙂
