### ISSUE TITLE
Mode to display years as options

### ISSUE THREAD

**Issue by arielclement** [react-native-datetimepicker/datetimepicker#809]
# Question

Hi, I was wondering is it possible to display years only as options using this library?

**Comment by Nasseratic** [comment]
This option is not available for native [iOS date picker](https://developer.apple.com/design/human-interface-guidelines/pickers/#Platform-considerations).
<img width="559" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/18466484/2c72641b-ab32-4798-aff5-bde9b600cd2c">

You would need to use a custom picker using [react native picker](https://github.com/react-native-picker/picker)

But in my opinion, this is out of the scope of this library
