### ISSUE TITLE
Date Picker on iOS returns a date that is one day before the selected date (ex. picked 2023-08-27 returns 2023-08-26T23:15:00.000Z)

### ISSUE THREAD

**Issue by TaulantAvdili** [react-native-datetimepicker/datetimepicker#813]
# Bug report

## Steps to reproduce

1. Pick date on iOS ex. 2023-08-27
2. DateTimePicker returns 2023-08-26T23:15:00.000Z

Describe what you expected to happen:

1. Pick date on iOS ex. 2023-08-27
2. DateTimePicker should return 2023-08-27T00:15:00.000Z (this is what DTP on android returns)

## Environment info

`npx react-native info` output:

```bash
# System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 6600H with Radeon Graphics 
  Memory: 4.94 GB / 15.21 GB
Binaries:
  Node:
    version: 18.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.10121639
  Visual Studio:
    - 17.6.33712.159 (Visual Studio Community 2022)
Languages:
  Java:
    version: 18.0.2.1
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

Time zone name (If the problem you have is related to unexpected time / date. See list in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

datetimepicker version: 7.2.0

iOS / Android version: 16.6

**Comment by Nasseratic** [comment]
Hello @TaulantAvdili

It might be just how you are logging it. In Recat-native when you print a date to console it will be printed in ISO time ( will be UTC )
Can you try to log using the `new Date().toLocaleString()`

**Comment by skendergashi** [comment]
The same occurred to me. The exact same behavior, also with and without logging. Plz help :(

**Comment by TaulantAvdili** [comment]
> Hello @TaulantAvdili
> 
> It might be just how you are logging it. In React-native when you print a date to the console it will be printed in ISO time ( UTC ) Can you try to log it using : `console.log(new Date().toLocaleString())`

This solver the issue, thank you for the fast response!

**Comment by TaulantAvdili** [comment]
> Hello @TaulantAvdili
> 
> It might be just how you are logging it. In React-native when you print a date to the console it will be printed in ISO time ( UTC ) Can you try to log it using : `console.log(new Date().toLocaleString())`

This solved the issue, thank you for the fast response!
