### ISSUE TITLE
Empty View or No Date

### ISSUE THREAD

**Issue by KarthikeyanEmis** [react-native-datetimepicker/datetimepicker#817]
In some scenarios, I need to show the empty view, instead of default today date. Right now, there is no straight way to achieve this in iOS. Kindly need to support this scenario too.

**Comment by vonovak** [comment]
Hello and thanks for asking,
please use if condition: if date is today, render the empty view. Otherwise, render the DatePicker view.


Thank you 🙂

**Comment by KarthikeyanEmis** [comment]
What if I want to change the date...? how to trigger the action to show the DatePicker View..?

**Comment by JB712** [comment]
Same problem here, on iOS when the picker is not displayed it is not possible to open it (as far as I know)
