### ISSUE TITLE
[react-native-windows] Missing Publisher Details in the details tab under dll Properties 

### ISSUE THREAD

**Issue by NikhiRaya** [react-native-datetimepicker/datetimepicker#818]
# Bug report

## Summary

The DateTimePicker.dll is missing versioning/publisher details set in their metadata. 

Currently, the publisher information is not available in the properties (screenshot below), and this absence of publisher details is causing issues with AppLocker (a security tool). AppLocker can sometimes block updates to DLLs if they do not have proper versioning/publisher details set in their metadata. 

<img width="501" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/110552664/d79d9348-f987-4830-accd-7a9b11cf707b">

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 7.6.1 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:
