### ISSUE TITLE
how can user choose only future time, and not past time

### ISSUE THREAD

**Issue by tazo-nebieridze** [react-native-datetimepicker/datetimepicker#819]
it is very bad experience when user can choose past time from timePicker , it is not practical, my app is all about planning future events and i do not need user to choose past time for his event,

 how can i make that, user can only choose future time form timePicker

**Comment by vonovak** [comment]
Hello,
please take a look at this prop: https://github.com/react-native-datetimepicker/datetimepicker#minimumdate-optional

thank you! 🙂
