### ISSUE TITLE
locale prop for android devices

### ISSUE THREAD

**Issue by ArturDabrowski** [react-native-datetimepicker/datetimepicker#82]
# Feature Request

It would be nice to have an option to change picker language by passing a locale prop

## Why it is needed

Picker has device language regardless of the app language settings

### Code sample

            <DateTimePicker
              mode="date"
              value={date}
              onChange={handleDateChange}
              locale={language}
              minimumDate={minDate}
              maximumDate={maxDate}
            />

**Comment by Legi0n1138** [comment]
Any chances for this feature?

**Comment by alecpo** [comment]
Any chances for this feature? [2]

**Comment by vonovak** [comment]
Hello, thanks for the feature request. There is no plan to implement this by the maintenainers, but we will accept a pull request for this feature.

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
