### ISSUE TITLE
Calendar start from monday instead of sunday

### ISSUE THREAD

**Issue by andib0** [react-native-datetimepicker/datetimepicker#820]
Have the ability to make the calendar start from monday instead of sunday:
![Capture](https://github.com/react-native-datetimepicker/datetimepicker/assets/129665998/57d3d3d3-e667-476a-9b33-c87c621ec922)

**Comment by vonovak** [comment]
Hello and thanks for asking,
this is a duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/196
Thank you 🙂
