### ISSUE TITLE
Publish my own components to NPM using your package

### ISSUE THREAD

**Issue by sofizambrano** [react-native-datetimepicker/datetimepicker#821]
# Question
I'm having an issue when publishing my components. As a company, we have our own components library which is published to the Github Package Registry(this is like a private version of NPM). As your library uses native platform pickers, when publishing my component, which, in turn, uses your DateTimePicker, it is not able to use when consuming it from our React Native mobile app. Neither in Android nor in iOS devices: it says it is not supported.

Can you guide me on how to fix this, please? What additional configuration do I need on my side to make it work? 🙏 

**Screenshots**
<img src="https://github.com/react-native-datetimepicker/datetimepicker/assets/11342785/bdecb20a-492d-4866-9eb0-be097f4ae2d4" height="700"><img src="https://github.com/react-native-datetimepicker/datetimepicker/assets/11342785/f3b04041-8afb-4676-8e74-95b829eaebbe" height="700">

**Comment by Nasseratic** [comment]
You can look at https://github.com/mmazzarolo/react-native-modal-datetime-picker
They are doing something similar. Seems like they have `@react-native-community/datetimepicker` as a `peerDependencies`
![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/18466484/61414f4b-d022-48c7-95f8-f495b0ca7031)

**Comment by vonovak** [comment]
Hello and thanks for asking,
something is not right with your bundling, it seems.

It appears this code is being run instead of the native code https://github.com/react-native-datetimepicker/datetimepicker/blob/master/src/datetimepicker.js

With that, I believe this question is out of scope for this issue tracker.
Thank you 🙂
