### ISSUE TITLE
iOS App build failed - method '+UIDatePickerMode:' conflicts with same method from another category - expo managed workflow

### ISSUE THREAD

**Issue by Giacomo92** [react-native-datetimepicker/datetimepicker#828]
# Bug report

## Summary

The app build failed on step "Run fastlane" with the following error:
```bash
 ld: duplicate method '+moduleName' in
┌─[category]: ExpoBridgeModule-0242f64b062de3cd0d4ec0caf3f410f5.o ExpoModulesCore/libExpoModulesCore.a
└─[class]: ExpoBridgeModule-98b5d0e7531e485a1b18f0b3b4664911.o ExpoModulesCore/libExpoModulesCore.a

⚠️  ld: method '+UIDatePickerMode:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/onehournestreactnative-cutbugfszifdlzanmamnpaehbtxa/Build/Intermediates.noindex/ArchiveIntermediates/onehournestreactnative/BuildProductsPath/Release-iphoneos/React-Core/libReact-Core.a(RCTDatePickerManager.o) conflicts with same method from another category
```
This is an expo app with managed workflow

## Reproducible sample code
import React, {useEffect, useState} from 'react';
import {Box, Button, FormControl, Text, View, WarningOutlineIcon} from "native-base";

import moment from "moment";
import RNDateTimePicker from "@react-native-community/datetimepicker";

export default function Birthdate({}) {
  
    const [date_of_birth, set_date_of_birth] = useState(new Date());
    const [error, setError] = React.useState('');

    const [date, setDate] = useState(new Date(1598051730000));
    const [mode, setMode] = useState('date');
    const [show, setShow] = useState(false);

    const {t} = useTranslation();

    const onChange = (event, selectedDate) => {
        const currentDate = selectedDate;
        setShow(false);
        setDate(currentDate);
    };

    const showMode = (currentMode) => {
        setShow(true);
        setMode(currentMode);
    };

    const showDatepicker = () => {
        showMode('date');
    };

    const showTimepicker = () => {
        showMode('time');
    };

    const saveBirthdate = async () => {
       //TODO: save
    };

    useEffect(() => {
       //
    }, []);

    return (
            <Box mt={10}>
                     <FormControl isInvalid alignItems={'center'}>
                        <RNDateTimePicker accentColor={'white'}
                                          textColor="white"
                                          mode="date"
                                          display="spinner"
                                          onChange={(event, date_of_birth) => set_date_of_birth(date_of_birth)}
                                          value={date_of_birth}
                                          minimumDate={new Date(1950, 0, 1)}/>
                        <FormControl.ErrorMessage
                            leftIcon={error ? <WarningOutlineIcon color={'black'} size="xs"/> : ''}>
                            <Text color={'black'}>{error}</Text>
                        </FormControl.ErrorMessage>
                    </FormControl>
            </Box>
 );
};

## Environment info

`npx react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 115.63 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.13 => 0.71.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
datetimepicker version: 6.7.3 (I cannot update with my current dependencies setup)
"expo": "^48.0.0",

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I belive this should be fixed if you use expo 49.
Please open an issue if not.
Thank you 🙂
