### ISSUE TITLE
[iOS] Not compatible with latest React Native 0.73 RC 4

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-native-datetimepicker/datetimepicker#838]
# Bug report

<!--
## Summary

I am building the app against React Native 0.73.0-rc-.4, but on iOS I get build issues for DateTimePicker in ComponentDescriptors.h

## Reproducible sample code

Just build app with Latest RC.

## Steps to reproduce

Build with latest RN RC version

Describe what you expected to happen:

1. App should build

**Comment by ravindraguptacapgemini** [comment]
`Here is the patch to fix issue:


diff --git a/node_modules/@react-native-community/datetimepicker/android/build/tmp/compileDebugJavaWithJavac/previous-compilation-data.bin b/node_modules/@react-native-community/datetimepicker/android/build/tmp/compileDebugJavaWithJavac/previous-compilation-data.bin
new file mode 100644
index 0000000..ad018b4
Binary files /dev/null and b/node_modules/@react-native-community/datetimepicker/android/build/tmp/compileDebugJavaWithJavac/previous-compilation-data.bin differ
diff --git a/node_modules/@react-native-community/datetimepicker/ios/fabric/cpp/react/renderer/components/RNDateTimePicker/ComponentDescriptors.h b/node_modules/@react-native-community/datetimepicker/ios/fabric/cpp/react/renderer/components/RNDateTimePicker/ComponentDescriptors.h
index 4a1a8e2..0df2c3d 100644
--- a/node_modules/@react-native-community/datetimepicker/ios/fabric/cpp/react/renderer/components/RNDateTimePicker/ComponentDescriptors.h
+++ b/node_modules/@react-native-community/datetimepicker/ios/fabric/cpp/react/renderer/components/RNDateTimePicker/ComponentDescriptors.h
@@ -18,20 +18,20 @@ class RNDateTimePickerComponentDescriptor final : public ConcreteComponentDescri
   public:
     using ConcreteComponentDescriptor::ConcreteComponentDescriptor;
 
-    void adopt(ShadowNode::Unshared const &shadowNode) const override {
-      react_native_assert(std::dynamic_pointer_cast<RNDateTimePickerShadowNode>(shadowNode));
-      auto pickerShadowNode = std::static_pointer_cast<RNDateTimePickerShadowNode>(shadowNode);
+    void adopt(ShadowNode &shadowNode) const override {
+      react_native_assert(&static_cast<RNDateTimePickerShadowNode&>(shadowNode));
+      auto& pickerShadowNode = static_cast<RNDateTimePickerShadowNode&>(shadowNode);
 
       react_native_assert(
-        std::dynamic_pointer_cast<YogaLayoutableShadowNode>(pickerShadowNode));
-      auto layoutableShadowNode =
-        std::static_pointer_cast<YogaLayoutableShadowNode>(pickerShadowNode);
+        &static_cast<YogaLayoutableShadowNode&>(pickerShadowNode));
+      auto& layoutableShadowNode =
+        static_cast<YogaLayoutableShadowNode&>(pickerShadowNode);
 
-      auto state = std::static_pointer_cast<const RNDateTimePickerShadowNode::ConcreteState>(shadowNode->getState());
+      auto state = std::static_pointer_cast<const RNDateTimePickerShadowNode::ConcreteState>(shadowNode.getState());
       auto stateData = state->getData();
         
       if(stateData.frameSize.width != 0 && stateData.frameSize.height != 0) {
-        layoutableShadowNode->setSize(Size{stateData.frameSize.width, stateData.frameSize.height});
+        layoutableShadowNode.setSize(Size{stateData.frameSize.width, stateData.frameSize.height});
       }
 
       ConcreteComponentDescriptor::adopt(shadowNode);`

**Comment by ravindraguptacapgemini** [comment]
Patch for the fix: 
[Uploading @react-native-community+datetimepicker+7.6.1.patch…]()

**Comment by grgmo** [comment]
@ravindraguptacapgemini any reason pr hasn't been raised with the patch? seems to work on 0.73

**Comment by Obhenimen** [comment]
This does not still work on the latest version of this library 7.6.2. My react native version is 0.76.1. I get this error when i tried to build for the ios device using "yarn run ios"
The following build commands failed:
        CompileC /Users/obhenimen/Library/Developer/Xcode/DerivedData/poscholarsgstapp-dmzpseuzzmhmeocifevlpgaevsaj/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNDateTimePicker.build/Objects-normal/arm64/RNDateTimePickerComponentView.o /Users/obhenimen/Documents/poscholarsgstapp/node_modules/@react-native-community/datetimepicker/ios/fabric/RNDateTimePickerComponentView.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNDateTimePicker' from project 'Pods')
(1 failure)

**Comment by brandon-austin-lark** [comment]
@Obhenimen same

**Comment by pjohn71** [comment]
@brandon-austin-lark Nope

**Comment by niklashaug** [comment]
Had the same issue and got it working again by upgrading to v7.6.3:
`npm i @react-native-community/datetimepicker@7.6.3`

**Comment by abdulqadir-117** [comment]
Issue still persists. I am already using this version "@react-native-community/datetimepicker": "^7.6.3",

**Comment by vonovak** [comment]
Hello this should be fixed in v8 https://github.com/react-native-datetimepicker/datetimepicker/releases/tag/v8.0.0

Please open a new issue if the problem persists

Thank you!
