### ISSUE TITLE
react-native-community/datetimepicker, Direct Calendar View is not working

### ISSUE THREAD

**Issue by LokeshWoodside** [react-native-datetimepicker/datetimepicker#846]
# Question

Hi Guys, 

I am trying to use this library from two days only, I have installed it using expo, and integrated that in my project, I have one touchableOpacity in my component, on clicking I am showing the datePicker, but instead of showing or opening a calendar directly it's open a dateBox first, and after clicking on dateBox it open calendar. I am thinking that is because of mode, I am using mode 'date' here, but it should open a calendar directly as of my knowledge, It should open a calendar Modal.

so please help me to understand the solution of it. see attach images:-

version's I am using:-
"expo": ">=47.0.0-0 <48.0.0"
"@react-native-community/datetimepicker": "6.5.2"

![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/129941786/31a9574c-0133-4d3a-a346-a649566cb960)
![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/129941786/45c37046-4647-4ad9-b1bb-946e815f1348)

Thanks in Advance.

**Comment by Nasseratic** [comment]
Hello 👋🏼 
This is not a bug it's what is expected behaviour :) 

Thats because that you are using `compact` or `inline` display mode. Try to use `spinner` 
https://github.com/react-native-datetimepicker/datetimepicker#display-optional
