### ISSUE TITLE
Hide default buttons and display customised buttons for cancel and confirm actions. 

### ISSUE THREAD

**Issue by makalaravikiran** [react-native-datetimepicker/datetimepicker#863]
Is there any possibility to have the custom buttons passed as a props to display in spinner type time/date picker.

**Comment by Nasseratic** [comment]
Hello 👋🏼 
Are you using react-native-modal-datetime-picker? :) 
If so there is props to customise buttons, you can find them here: https://github.com/mmazzarolo/react-native-modal-datetime-picker#available-props

![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/18466484/59e5946e-4e4e-4f66-9502-8c58e7a74d9c)

**Comment by makalaravikiran** [comment]
Thanks for your response @Nasseratic , But i wanted to have custom buttons for Android.

**Comment by vonovak** [comment]
Hello and thanks for asking,
the only props we offer for button labels are these https://github.com/react-native-datetimepicker/datetimepicker?tab=readme-ov-file#positivebutton-optional-android-only

Thank you 🙂
