### ISSUE TITLE
On iOS device, we cannot select the same date on spinner dialog box, need to select different date and then select the old date as the onChange is not triggered when clicking on same date.

### ISSUE THREAD

**Issue by ksodhithentia** [react-native-datetimepicker/datetimepicker#886]
# Bug report

## Steps to reproduce

1. open a spinner dialog box on ios device for datepicker

Describe what you expected to happen:

1. clicking/tap on same/cuurent date should close the dialog box after invoking the onChange function

## Environment info

`npx react-native info` output:

```bash
# paste it here
```

Time zone name (If the problem you have is related to unexpected time / date. See list in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

datetimepicker version: "^7.6.2"

iOS / Android version: "^17.4"

**Comment by vonovak** [comment]
Hello and thanks for asking,
this package does offer a spinner picker, but not in a dialog so I'm not sure what you're asking TBH.
Please open a new issue with more information.
Thank you 🙂
