### ISSUE TITLE
`minimumDate` and `maximumDate` not working for `mode={'time'}` on Android?

### ISSUE THREAD

**Issue by the-devbear** [react-native-datetimepicker/datetimepicker#894]
# Question

Hello, my question is if this feature is supported for Android, because on IOS it works perfectly fine.
But on Android I can still set a time in future/past even with the minimumDate and maximumDate props set.

This is what I use:
```
<RNDateTimePicker
          mode='time'
          minimumDate={new Date('2024-05-12 16:00')}
          maximumDate={new Date()}
          display={Platform.OS === 'android' ? 'default' : 'default'}
          value={time}
/>
```

Am I doing something wrong? 
Any help is appreciated. Thanks

**Comment by hevi08** [comment]
In the docs ([maximumDate & minimumDate props](https://github.com/react-native-datetimepicker/datetimepicker?tab=readme-ov-file#maximumdate-optional)), it's clearly mentioned that Android doesn't support this feature.

**Comment by the-devbear** [comment]
Ohhh, yea it totally does. You could have dropped a RTFM 🤣.
Thank you!
