### ISSUE TITLE
feature: Imperative API for iOS

### ISSUE THREAD

**Issue by hichemfantar** [react-native-datetimepicker/datetimepicker#906]
# Feature request

## Why it is needed

Right now we can build a custom button on Android, but on iOS, we are forced to use the iOS button design.
I would like to have a single custom button that launches both android and ios pickers.

## Possible implementation

Exactly like the existing imperative android api.
It would be possible to create something like this: https://github.com/henninghall/react-native-date-picker?tab=readme-ov-file#modal

### Code sample

```ts
import { DateTimePickeriOS } from '@react-native-community/datetimepicker';

DateTimePickeriOS.open(params: iOSNativeProps)
DateTimePickeriOS.dismiss(mode: iOSNativeProps['mode'])
```

**Comment by vonovak** [comment]
Hello and thanks for asking,
this library exposes the native primitives in their simplest form. If you want anything on top of it, like a different API, you need to build it yourself.

Thank you 🙂

**Comment by ishaangandhi** [comment]
Its not clear that the library does expose the native primitives. What primitive can you use to open the time picker?
