### ISSUE TITLE
Warning: support for defaultProps will be removed

### ISSUE THREAD

**Issue by Kaosc** [react-native-datetimepicker/datetimepicker#925]
I have swithced to expo sdk 51 with react native 0.74.5 on Android 14. 
The below warning started to popup on render of the `<DateTimePickerModal />` 

 > ## Warning: Unknown: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

## Environment info

```bash
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google Play Intel x86_64 Atom
      - android-35 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
Languages:
  Java: 17.0.11
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-windows: Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

datetimepicker version: 8.2.0

**Comment by aljadan** [comment]
@Kaosc if you are using react-native-modal-datetime-picker, make sure to update to the [latest version](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v18.0.0), it solves this issue

**Comment by jathnamas** [comment]
Is anyone looking into this? 

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops
