### ISSUE TITLE
macOS Sequoia and Xcode 16 build issue

### ISSUE THREAD

**Issue by therealkh** [react-native-datetimepicker/datetimepicker#932]
# Bug report

## Summary

library is failing build process for iOS in Xcode 16. with following error: 
```@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m:8:41 Incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')```

## Steps to reproduce

try building on Xcode 16.

## Environment info

`npx react-native info` output:

```bash
System:
  OS: macOS 15.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 319.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.3
    path: ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm:
    version: 10.2.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/uktam/.rvm/gems/ruby-2.7.8/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/uktam/.rvm/rubies/ruby-2.7.8/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

datetimepicker version: 8.2.0

iOS 18

**Comment by vonovak** [comment]
Hello and thanks for reporting,
it seems you're using RN 0.72.

For that version you'll need to use an older version of the library, please check the release notes.
Thank you 🙂
