### ISSUE TITLE
Incompatible function pointer types passing 'YGSize(YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode , float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize ()(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')

### ISSUE THREAD

**Issue by deepanshuprabhatkhabar** [react-native-datetimepicker/datetimepicker#934]
Incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')

**Comment by ntv19398** [comment]
I changed YGNodeConstRef to YGNodeRef in line 44. It helped me to resolve this error.
<img width="966" alt="Screenshot 2024-10-07 at 10 07 47" src="https://github.com/user-attachments/assets/f1cf5acf-52dc-4a38-a1c5-c2c56be7e795">

**Comment by Sanket8304** [comment]
@ntv19398 which version of `@react-native-community/datetimepicker` and  Xcode currently you are using?

**Comment by deepanshuprabhatkhabar** [comment]
> I changed YGNodeConstRef to YGNodeRef in line 44. It helped me to resolve this error. <img alt="Screenshot 2024-10-07 at 10 07 47" width="966" src="https://private-user-images.githubusercontent.com/43595104/374012404-f1cf5acf-52dc-4a38-a1c5-c2c56be7e795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzM0NTAsIm5iZiI6MTcyODM3MzE1MCwicGF0aCI6Ii80MzU5NTEwNC8zNzQwMTI0MDQtZjFjZjVhY2YtNTJkYy00YTM4LWExYzUtYzJjNTZiZTdlNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA3MzkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhY2MxNDhjNjk2ODcwZGRiODFjN2VlMTk0ZWQ4MjM4OTA4OGMyYWVkNTkxODlmNzc5OWNjYTk4NTk3ZGM0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gv36xdW6BNjy0Sg_mAKKDYQ1TCCnLShnCTt9iXTLsyc">

i have already applied this solution but it is not working with xcode 16

**Comment by ntv19398** [comment]
> @ntv19398 which version of `@react-native-community/datetimepicker` and Xcode currently you are using?

I'm using Xcode 16 and @react-native-community/datetimepicker version 7.6.1

**Comment by vonovak** [comment]
Hello and thanks for asking,
this is the same as https://github.com/react-native-datetimepicker/datetimepicker/issues/911
Thank you 🙂
