### ISSUE TITLE
Unable to force light mode

### ISSUE THREAD

**Issue by TimHi** [react-native-datetimepicker/datetimepicker#937]
The app I'm working on does not offer a dark mode, hence I need to ignore the system set dark mode. In Android it's looking like this:

<img width="149" alt="Screenshot 2024-10-21 at 13 13 22" src="https://github.com/user-attachments/assets/dbf897a0-f55e-4a67-9f08-9f22eabeb6e1">

So far I've tried to edit the styles.xml. Neither `forceDarkAllowed` or the `timePickerDialogTheme/datePickerDialogTheme` seem to. make any difference.

```xml
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:spinnerItemStyle">@style/SpinnerItem</item>
        <item name="android:spinnerDropDownItemStyle">@style/SpinnerDropDownItem</item>
        <item name="android:timePickerDialogTheme">@style/DialogDatePicker.Theme</item>
        <item name="android:datePickerDialogTheme">@style/DialogDatePicker.Theme</item>
    </style>

    <style name="DialogDatePicker.Theme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorAccent">@color/primary_blue</item>
        <item name="android:textColor">@color/primary_dark</item>
        <item name="android:textColorPrimary">@color/colorBottomNavigationNotification</item>
    </style>
```

I'm on the latest version 8.2.0. Is there something I'm missing?

**Comment by vonovak** [comment]
Hello and thanks for asking,
Please use the theme-control library that's recommended in https://github.com/react-native-datetimepicker/datetimepicker#themevariant-optional-ios-only

That should work best,
Thank you 🙂

**Comment by TimHi** [comment]
Hello @vonovak , thank you for the suggestion, I saw the themevariant prop but it is marked as iOS only, this is an issue with Android, does the prop work for Android as well?

**Comment by vonovak** [comment]
Hi Tim,
My comment above, as well as the prop documentation mention the theme/control library.

Did you have a look at it too?

**Comment by TimHi** [comment]
I apologize, I missread the part in the doc. Using the theme-control library worked.
Thank you for the quick support!

**Comment by vonovak** [comment]
Actually, for your use case this might be enough 

https://reactnative.dev/docs/next/appearance#setcolorscheme
