### ISSUE TITLE
Don't work with Expo Go SDK52

### ISSUE THREAD

**Issue by dulyts** [react-native-datetimepicker/datetimepicker#939]
# Bug report

## Summary

On Android with ExpoGo(2.32.5) SDK52 I get the following error at startup:
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDatePicker' could not be found. Verify that a module by this name is registered in the native binary.

## Reproducible sample code

```
npx create-expo-app@latest --template default@beta
cd {project}
npx expo install @react-native-community/datetimepicker
```

Add following to index.ts
```
import RNDateTimePicker from "@react-native-community/datetimepicker";
[...]
<RNDateTimePicker mode="date" value={new Date()} />
```

## Environment info

@react-native-community/cli do not available from react native 76.0

datetimepicker version: 8.2.0
Android version: 14

**Comment by adam-sajko** [comment]
They undo their changes 3 days ago:
https://github.com/expo/expo/pull/32591/files#diff-a0c9a0a67a4de40c55378979734685b9de162a7d2fa81fe41c1235160578cd41R14

**Comment by dulyts** [comment]
Works with newer Expo Go.

**Comment by Little6thingys** [comment]
> > They undid their changes 3 days ago. https://github.com/expo/expo/pull/32591/files#diff-a0c9a0a67a4de40c55378979734685b9de162a7d2fa81fe41c1235160578cd41R14
> > Should work now with the latest Expo Go.
> 
> This works only inside Expo Go app, but returns mentioned error inside development build.

I'm still having this error inside the development build.
