### ISSUE TITLE
react-native-date-picker crashes in release build on Android

### ISSUE THREAD

**Issue by kgroshev** [react-native-datetimepicker/datetimepicker#953]
The app crashes immediately after the splash screen in the release build when using react-native-date-picker. The error indicates the library is not installed correctly, even though it works fine in the debug build.

**React Native Version**: 0.76.3
**react-native-date-picker Version**: 5.0.8
**Platform**: Android (Release build only)
**Node Version**: v23.4.0
**Emulator**: Pixel_6_Pro_API_33(AVD) - 13

Proguard rules aren't enabled. Attempted to enable with the below flags, same behaviour:
```
-keep class com.henninghall.date_picker.** { *; }
-dontwarn com.henninghall.date_picker.**
```

Ignoring the warning also has no effect. iOS debug and release are not affected. Android debug release is unaffected.

Relevant Logcat logs: 
```
FATAL EXCEPTION: mqt_v_native
com.facebook.react.common.JavascriptException: Error: react-native-date-picker is not installed correctly. Make sure you: 

1. Rebuilt the app (by for instance 'npx react-native run-ios')

Please reply in this thread if this solved your issue or not: 
https://github.com/henninghall/react-native-date-picker/issues/404
```

**Comment by devchandhana12** [comment]
Bro, how do you solved this
